- docs/app/components/components.ts
- docs/app/components/navigation-bar/navigation-bar.component.html
- docs/app/components/navigation-bar/navigation-bar.component.less
- docs/app/components/navigation-bar/navigation-bar.component.ts
- docs/app/components/section-select/section-select.component.html
- docs/app/components/section-select/section-select.component.ts
- docs/app/components/side-navigation/side-navigation.component.ts
- docs/app/pages/charts/charts.component.html
- docs/app/pages/components/components.component.html
- docs/app/pages/css/css.component.html
- docs/styles.less
Adding navigation menu on small displays and adding section dropdown on the top of css, components and charts pages on small displays
Note: The select control to select sections does not use the dynamic select component on purpose, as the native browser select control is specifically supported on mobile devices and will provide a better user experience on these devices
> EL-2441 - Navigation on small displays

- bower.json
- configs/webpack.library.config.js
- docs/app/app.module.ts
- src/index.ts
- src/services/color/color.module.ts
- src/services/color/color.service.ts
- src/tsconfig-build.json
Outputting type definitions and updating bower.json with new output file. Also removing main ux-aspects module as this is now considered bad practice as it can break tree shaking.
No bower dependencies to be updated, Angular 4 doesnt have a bower package, nor does ngx-bootstrap. I have raised a jira to public an NPM package where we can specify these dependencies
> EL-2462 - Bower Dependencies

- docs/app/pages/components/sections/search/search-builder-ng1/templates/insetPanels.html
- docs/app/pages/components/sections/search/search-builder-ng1/templates/launchingModal.html
- docs/app/pages/components/sections/search/search-builder-ng1/templates/searchBuilder.html
- docs/app/pages/components/sections/search/search-builder-ng1/templates/searchComponents.html
- docs/app/pages/components/sections/search/search-builder-ng1/templates/services.html
They were binding to html so they were rendering the contents of the code sample rather than displaying the code
> Fixing search builder code samples

- src/components/checkbox/checkbox.component.less
- src/styles/input-controls.less
Checked in Chrome Firefox and IE, the checkbox style is now consistent throughout
> EL-2455 - Fixing checkbox alignment in Firefox

- docs/app/pages/components/sections/tables/sorting-ng1/sorting-ng1.component.html
- src/ng1/directives/sorters/sorter/sorter.controller.js
- src/ng1/directives/sorters/sorterOption/sorterOption.controller.js
- src/ng1/directives/sorters/sorterOption/sorterOption.directive.js
- src/ng1/directives/sorters/sorterOption/sorterOption.html
- src/styles/filters.less
- test/ng1-app/app/app.ts
- test/ng1-app/app/controller.ts
- test/ng1-app/index.html
- test/ng1-app/package.json
- test/ng1-app/tsconfig.json
- test/ng1-app/webpack.config.js
- tsconfig.json
Added option to disable sorter option. Also added test page under "text/ng1-app" which allows us to test Angular 1 components again. To use the test page navigate to the folder in cmd and run `npm install` then `npm start` to launch local webserver. Output can be viewed at localhost:8080.
Also refactored sorter option code to make use of some of the newer ES6 syntax improving readability
> EL-2377 - Allow Sorter Options to be Disabled

- src/styles/controls.less
On firefox the date picker was alot wider than on the other browers, this makes them consistent
> EL-2385 - Fixing firefox date picker size

- src/ng1/directives/sorters/detailRowHeader/detailRowHeaderPopover.directive.js
This line resets the 'inState.click' variable for the popover which the hide method isn't doing. This fixes the double click required to open the popover after we manually hide it.
> EL-2471 - Fixing detail row header popover issue

- src/styles/buttons.less
- src/styles/tables.less
- src/styles/variables.less
Added mixins for some button states to aid consistency.
Changed @btn-active-shadow to provide the inset box shadow effect.
Fixed btn focus so that it always overrides bootstrap default.
Moved some :hover rules so that they override .active styles.
Fixed .btn-group to use standard button styles for hover.
Replaced .pagination rules with the standard button styles.
Added active colors to pagination.
Fixed secondary active border.
Removed obsolete rules.
https://jira.autonomy.com/browse/EL-2478
> S 57/el 2478

- src/ng1/directives/helpCenter/helpCenter.spec.js
- src/ng1/directives/helpCenter/helpCenterMenu.directive.js
- src/styles/theme.less
Removing replace true caused some issues with the help center menu, I will raise a ticket to add a wrapper for this instead.
> EL-2467 - Added replace true back into help center menu

- docs/app/pages/components/sections/tables/detail-row-header-ng1/wrapper/detail-row-header-wrapper.directive.ts
- src/ng1/directives/sorters/detailRowHeader/detailRowHeaderPopover.directive.js
The popovers were throwing errors in codepen, this solves fixes the errors allow the popover to be opened and closed correctly, autoReinitialize delay has been increased however the performance on IE is too poor to make much of an improvement, I have raised a ticket to migrate the fixed header table
> EL-2471 - Fixing codepen issue

- docs/app/pages/components/sections/popover/popover-ng1/popover-ng1.component.html
- docs/app/pages/components/sections/popover/popover-ng1/popover-ng1.component.less
- docs/app/pages/components/sections/popover/popover-ng1/snippets/styles.css
- src/ng1/external/ui-bootstrap/ui-bootstrap-tpls.js
The popover now runs outside angular and only when the popover is open, this has a significant improvement on performance so should be a lot more responsive now.
> EL-2482 - Adding popover example

- docs/app/components/usage-link/usage-link.component.html
- docs/app/components/usage-link/usage-link.component.ts
Popover now closes when you click elsewhere on the page and when you press escape. Tabbing onto copy buttons has been left out as it will come with a performance hit and is not required
> EL-2507 - Adding close of click and close on escape

- src/components/column-sorting/column-sorting.component.ts
- src/components/slider/slider.component.ts
- src/components/spark/spark.module.ts
Spark module was import tooltip from 'ngx-bootsrap' rather than 'ngx-bootstrap/tooltip' adding ~800kb on to our library build output size.
Column sorting and Slider were using unexported enums & interfaces which preventing typescript from creating type definitions for them.
> EL-2534 - Fixing library build

- docs/app/data/components-page.json
- docs/app/pages/charts/sections/organization-chart/organization-chart-ng1/organization-chart-ng1.component.html
- docs/app/pages/components/sections/input-controls/radio-button/radio-button.component.html
- docs/app/pages/components/sections/input-controls/radio-button/snippets/app.html
- src/components/checkbox/checkbox.component.less
- src/components/radiobutton/radiobutton.component.less
- src/components/radiobutton/radiobutton.component.ts
Varying uses of 'radiobutton' and 'radio button' now made them consistently two word in Angular 4 radio button section.
Also fixed IE issue:
> EL-2537 - Fixing QA issues

- src/ng1/directives/displayPanels/displayPanel/displayPanel.directive.js
If the node is 'HTML' then it was triggered by scroll event and should not close panel. Also changed to use parent element instead of parent node and parent node will return a #document node above the HTML tag whereas parentElement will return null - due to trying to access attributes on the #document element which throws an error
> EL-2543 - Item display panel fix

- docs/app/pages/components/sections/dashboard/dashboard/dashboard.component.html
- docs/app/pages/components/sections/dashboard/dashboard/snippets/app.html
Fixing typos, taking new lines in HTML to avoid scrollbar. Scrollbar still appears in CSS but taking a new line in the CSS would technically make it incorrect
> EL-2533- Dashboard - Fixing typos, taking new line in code

- src/index.ts
There were a few duplicate entries in the index.ts file which caused exporting of duplicated components to fail
> Fixing index file

- src/components/typeahead/typeahead.component.less
- src/ng1/directives/draggableCards/cards/draggableCard.html
- src/ng1/directives/tooltipOnOverflow/tooltipOnOverflow.directive.js
- src/ng1/directives/tooltipOnOverflow/tooltipOnOverflow.module.js
- src/ng1/ux-aspects-ng1.module.js
- src/styles/cards.less
Replaced overflow-tooltip in the draggable card with a new directive
which only applies the tooltip. Since it will be deprecated soon I
decided not to make changes to the current directive.
Changed the card header layout to use the available width.
Fixed a lint issue in another stylesheet.
https://jira.autonomy.com/browse/EL-2566
> S 60/el 2566

- src/ng1/external/angular-scrollable-table/angular-scrollable-table.js
Before if a parent element had a height of 0 then the table would think it is hidden. Added a check to see if a parent element has a height of 0 but has overflow set to visible then still render the table.
Before:
[https://codepen.io/anon/pen/mwEdOb](https://codepen.io/anon/pen/mwEdOb)
After:
[https://codepen.io/ashh640/pen/dRRgqE](https://codepen.io/ashh640/pen/dRRgqE)
> EL-2608 - Marquee Modal fixed header table

- docs/app/pages/components/sections/input-controls/number-picker/number-picker.component.html
- src/components/number-picker/number-picker.component.html
- src/components/number-picker/number-picker.component.ts
1) Fixing typo
2) Using arrows now consistent with scrolling
3) Before disabled had to be set by either the html attribute `disabled="disabled"` or angular input `[disabled]="true"`. Made it more lenient to allow `disabled`, `disabled=""` and `disabled="true"`
> EL-2614 - Number Picker - Making QA changes

- src/components/media-player/extensions/controls/controls.component.less
Repositioning volume low icon so it doesn't shift when it changes to mute or high volume
> EL-2652 - Fixing media player icon positioning

- docs/app/pages/components/sections/help-center/help-center/snippets/app.html
- docs/app/pages/components/sections/help-center/help-center/snippets/app.ts
- docs/app/pages/components/sections/tables/layout-switching/layout-switching.component.html
- docs/app/pages/components/sections/tables/layout-switching/snippets/app.html
- docs/app/pages/components/sections/tables/layout-switching/snippets/app.ts
- src/components/page-header/navigation/navigation.component.ts
- src/components/page-header/page-header.component.html
- src/components/page-header/page-header.component.less
Fixing typos and line lengths for layout switcher and help center. Also fixing some weird IE issue where ngIf wouldn't work in help center plunker. Used hidden attribute instead, no idea what caused this.
> Fixing typos and IE issue

- docs/app/data/components-page.json
- docs/app/pages/components/sections/tables/hover-actions-ng1/hover-actions-ng1.component.ts
- docs/app/pages/components/sections/tables/hover-actions/hover-actions.component.html
- docs/app/pages/components/sections/tables/hover-actions/hover-actions.component.less
- docs/app/pages/components/sections/tables/hover-actions/hover-actions.component.ts
- docs/app/pages/components/sections/tables/hover-actions/snippets/app.css
- docs/app/pages/components/sections/tables/hover-actions/snippets/app.html
- docs/app/pages/components/sections/tables/hover-actions/snippets/app.ts
- docs/app/pages/components/sections/tables/tables.module.ts
- src/components/spark/spark.module.ts
- src/directives/hover-action/hover-action-container.directive.ts
- src/directives/hover-action/hover-action.directive.less
- src/directives/hover-action/hover-action.directive.ts
- src/directives/hover-action/hover-action.module.ts
- src/directives/hover-action/hover-action.service.ts
- src/directives/hover-action/index.ts
- src/index.ts
- src/styles/ux-aspects.less
Create hover action directives. I have deprecated both hover actions and list hover actions AngularJS components as these directives cover both use cases, no need for two separate components.
> EL-2641 - Hover Actions

- src/styles/controls.less
All text inputs (not just date pickers) now retain the error color when focused and in error state. The icon beside the date pickers will no longer be affected by the error styling. (Also removed some old dark styling)
> EL-2623 - Date Picker Invalid Styling

- src/ng1/directives/marqueeWizard/marqueeWizard.controller.js
Issue was caused due to hidden step logic happening before checking if we should move to the next step, checking if we should move first fixed the issue.
> EL-2657 - Fixed issue with onchanging false and hidden steps

- Gruntfile.js
- grunt/copy.js
Component less files should now be copied into the dist folder as well. The will be in the lib folder under the corresponding component/directive folder.
Added as part of the grunt library task
> EL-3692 - Copy component/directive less files

- Gruntfile.js
- grunt/copy.js
- grunt/execute.js
- grunt/less.js
- scripts/inline-less.js
- src/components/column-sorting/column-sorting.component.less
- src/components/dashboard/dashboard.component.less
- src/components/page-header/navigation/navigation-item/navigation-item.component.less
- src/components/page-header/page-header.component.less
- src/components/tag-input/tag-input.component.less
- src/components/typeahead/typeahead.component.less
Tried the inlining approach which is exactly what we need but did cause a few problems with our current setup. When the import statements are marked as "inline" the less compiler outputs a less file rather than a CSS file, which breaks our webpack builds as it is expecting CSS from the less-loader.
An alternate would be to have a separate `ux-aspects-inline.less` file which would have all the imports marked as inline, however this would mean having to maintain two "entry" less files which will no doubt cause problems when someone forgets to update one.
The approach that was the easiest to get working was to write a node script that grunt runs as part of the build. The script converts all the imports to "inline" and then gets less to compile it. This produces the single less file with all …
> EL-2692 - Inlining Less files

- scripts/inline-less.js
Inline less script was failing when trying to create the dist/less directory. Its possible the dist folder didn't exist so adding additional check in to create dist folder if required.
> Attempting to fix build issue

- src/components/slider/slider.component.html
This is required so we can change the height of the active and inactive parts of the track, without this we cant style for both normal sliders and range sliders correctly
> EL-2688 - Adding required slider class for Quantum mapping

- package.json
Being more specific about which files are included in package. List only the required subdirectories in the docs/app folder. Didn't want to negate just the app.*.ts and wrapper.module.ts files as it mentions on the npm wiki:
"The consequences are undefined" if you try to negate any of the files entries (that is, "!foo.js"). Please don't.
> EL-2758 - Limiting files included

- docs/app/pages/components/sections/tree-view/tree-grid-ng1/tree-grid-ng1.component.html
- docs/app/pages/components/sections/tree-view/tree-grid-ng1/wrapper/tree-grid-wrapper.directive.html
- docs/app/pages/components/sections/tree-view/tree-grid-ng1/wrapper/tree-grid-wrapper.directive.ts
selectChildren is designed to work with the check option. Since there are issues with row selection and selectChildren I have disabled this combination for now.
https://jira.autonomy.com/browse/EL-2770
> Disabled selectChildren when row selection is enabled

- package.json
- src/ng1/directives/backButtonHeader/backButtonHeader.module.js
- src/ng1/external/angular-ui-router/angular-ui-router.js
- src/ng1/ux-aspects-ng1.module.js
- src/package.json
Removing this is potentially a breaking change for basic applications which do not have an implementation of `require`. The showcases highlighted this problem.
https://jira.autonomy.com/browse/EL-2807
> Reinstated embedded ui-router

- scripts/inline-less.js
- src/styles/ux-aspects.less
Discovered one potential issue with including styles from a third party library in our stylesheet. Before it was a relative path, however if a team tried to import our less file (instead of the css file), the relative path would no longer be correct due to NPM flattening the folder structure and cause a compilation error.
Webpack supports the tilde to resolve this issue, but less.js which we use doesn't support that, so I have added a function to resolve the tilde for the less.js bit, this way anyone import the less directly will get the benefit of the tilde path resolution.
> Build Improvements - Less Tilde Support

- Gruntfile.js
- grunt/execute.js
- scripts/shim.js
Added a script to the grunt build task to place files in the locations before the package structure changed to import the new version of the file maintaining backwards compatibility
> EL-2814 - Maintaining backwards compatibility with file path changes

- docs/app/services/plunker/templates/config_js.txt
- package-lock.json
Updating package lock file to include angular-tree-component.
Also updated plunker assets url
Initially I thought the shim was missing, however it seems the shim did exist and wasn't working because SystemJS expects a umd module, whereas the shim is designed to work with bundlers tools.
> Updating package lock and plunker

- src/components/dashboard/dashboard.service.ts
Changing the dashboard to use pageX and pageY rather than .x and .y values on mouse event as these are not always as consistent they are in other browsers, especially when the page is scrolled or when dragging a widget and the mouse goes over the scrollbar or off the page
> IE Dashboard Fix

- src/ng1/directives/overflowTooltip/singleLineOverflowTooltip.directive.js
This seems to be the only way we can reliably remove a specific tooltip. When the tooltip is applied to the body it gets an ID which matches the aria-describedBy attribute on the element so we can use this to remove the specific tooltip if it gets left behind.
> Fixing issue with tooltip being left after element is removed

- src/components/slider/slider.component.ts
- src/ng1/plugins/flot/jquery.flot.resize.js
Improving slider component performance. The initial investigation was wrong, the slider was not in fact getting into an infinite loop, there was a jquery plugin that checked if flot charts needed resized and this was firing over and over again triggering change detection.
I have:
- Changed slider to use OnPush change detection
- Trigger change detection manually only when we know we need to
- Improved memory usage as the `clone` method seemed to be leaking memory, now releases the object once we no longer need it.
- Changed the flot plugin to check if NgZone is available and if so use it to run outside of angular preventing it from firing change detection.
> Fixing slider infinite loop

- src/components/slider/slider.component.ts
https://jira.autonomy.com/browse/EL-2751
Discovered that there was a case where IE can still crash (originally suspected to be an infinite loop but it actually appears to just be a crash as there was no memory leak and call stack did come to an end when I stepped through it entirely).
The issue appears when you go the the MF filtering showcase example and slide one of sliders to the very maximum value. This causes IE to crash. I believe this is due to some high precision values causing issues, fixing them to a specific precision as well as some further optimizations regarding detecting changes seems to resolve this issue.
> EL-2751 - Fixing slider IE issue

- docs/app/data/components-page.json
- docs/app/pages/components/sections/scrollbar/custom-scrollbar-ng1/custom-scrollbar-ng1.component.html
- docs/app/pages/components/sections/search/search-builder-ng1/snippets/modalController.js
- docs/app/pages/components/sections/search/search-builder-ng1/wrapper/search-builder-wrapper.directive.js
- src/ng1/plugins/customscroll/jquery.jscrollpane.js
jscrollpane should now resize correctly when popovers and dropdowns are toggled. See the search builder, popovers would be cut off when added close to the bottom of the modal.
Jira: https://jira.autonomy.com/browse/EL-2810
> S 69/el 2810

- docs/app/pages/components/sections/scrollbar/infinite-scroll-ng1/infinite-scroll-ng1.component.html
- docs/app/pages/components/sections/scrollbar/infinite-scroll-ng1/snippets/reset.js
- docs/app/pages/components/sections/scrollbar/infinite-scroll/infinite-scroll.component.ts
- src/ng1/directives/infiniteScroll/infiniteScroll.directive.js
Added the event `infiniteScroll.reset` which clears the list and starts from page 0 again. This avoids the need to use the query string as a hack to reload the list.
(This is already available on the Angular 4 equivalent via exporting the directive.)
https://jira.autonomy.com/browse/EL-2726
> Added reset event handler to ng1 infinite scroll

- src/components/slider/slider.component.ts
https://jira.autonomy.com/browse/EL-2751
If you used the text input to set the lower slider to a value above the max slider then try to enter a new value, the slider failed to update
Fixing some slider logic, also ensuring that we always emit a clone of the values and never the same instance
> EL-2751 - Fixing slider bug

- src/ng1/directives/splitter/splitter.directive.js
https://jira.autonomy.com/browse/EL-2828
The splitter that used a button to expand did not take into account the sizes specified on the panel elements.
Codepen of issue before:
https://codepen.io/donnamarijne/pen/boKWRN?&editors=111
Simply build locally and change url of ux-aspects script in codepen to point to you local machine to see fix
> EL-2828 - Fixing side inset panel splitter to use the specified sizes initially

- src/components/slider/slider.component.ts
https://jira.autonomy.com/browse/EL-2850
It was possible using the text inputs to set the value of the upper thumb to a minus number and the lower thumb to a value higher than the range of the slider and things get weird.
Should now be fixed
> EL-2850 - Fixing slider boundaries

- docs/app/services/navigation/navigation.service.ts
Click items on the right navigation in the MF site cut off the section header.
Updated this section to use non deprecated apis for getting scroll position. To test simply copy this navigation service file into the @ux-aspects/ux-aspects-docs folder so that it overrides the one there. You should now see the functionality works as expected in both the regular & MF docs sites
> EL-2841 - Scrolling to a subsection breaks in MF site

- docs/app/pages/components/sections/splitter/side-inset-panel-splitter-ng1/side-inset-panel-splitter-ng1.component.html
- docs/app/pages/components/sections/splitter/splitter-ng1/splitter-ng1.component.html
- docs/app/pages/components/sections/splitter/splitter-ng1/wrapper/splitter-wrapper.directive.js
- src/ng1/directives/splitter/splitter.directive.js
Adding an `on-toggle` attribute to a splitter which allows the user to specify a function to be called whenever a splitter inset panel is expanded or collapsed.
Jira: https://jira.autonomy.com/browse/EL-2853
> EL-2853 - Splitter panel toggle event

- docs/app/pages/components/sections/date-time-picker/date-time-picker/date-time-picker.component.html
- docs/app/pages/components/sections/date-time-picker/date-time-picker/date-time-picker.component.ts
- docs/app/pages/components/sections/date-time-picker/date-time-picker/snippets/app.html
- docs/app/pages/components/sections/date-time-picker/date-time-picker/snippets/app.ts
- src/components/date-time-picker/time-view/time-view.component.html
- src/components/date-time-picker/time-view/time-view.component.less
- src/components/date-time-picker/time-view/time-view.component.ts
Jira: https://jira.autonomy.com/browse/EL-2805
Fixing QA issues
1. Suggested rewording. Change "If not defined the users current timezone will try to be used. If their timezone is not available it will revert to GMT." to "If not defined the picker will try to use the user's timezone. If that is not available, it will revert to GMT."
**FIXED**
2. Update date and/or time in text box and the picker component is not updated. Should it be?
**FIXED**
3. Unexpected behaviour when showMeridian is Off.
UXAspects
Set time in picker to 23:57. Click down minutes. Time changes to 01:50. Should be 23:56?
Set time in picker to 23:59. Click up minutes. Time changes to 01:01. Should be 00:00?
Set time in picker to 00:00. Click down minutes. Time changes to 11:59. Should be 23:59?
Micro Focus
Set time in …
> Fixing date picker feedback

- src/ng1/directives/slider/slider.html
https://jira.autonomy.com/browse/EL-2800
Active class now gets added when AngularJS sliders are being dragged, this works the same as in the Angular version and no addition styling is required.
> EL-2800 - Adding active class to ng1 sliders

- configs/webpack.docs.dev.config.js
- configs/webpack.docs.prod.config.js
- configs/webpack.lib-assets.dev.config.js
- docs/vendor.ts
For development mode reverting back to old webpack loaders as ngtools/webpack loader seems to be the cause of the HTTPS disconnect issue (possibly due to its high memory usage).
For production version, module chunks were not getting minified - now fixed. Still using ngtools in production build as it gives us AOT compilation and type checking in our views.
Removed angular imports from vendor.ts as CommonChunksPlugin will now optimise these for us without out having to explicitly put them here. In fact keeping them here was causing them to be included in some chunks, bloating their size unnecessarily.
> Fixing webpack dev server issue

- configs/webpack.docs.dev.config.js
- configs/webpack.docs.prod.config.js
- docs/environments/environment.prod.ts
- docs/environments/environment.ts
Angular compiler plugin for some reason wasn't setting the environment property correctly in production build. Changed to use webpack DefinePlugin to set the production value
> Fixing environment property

- src/ng1/directives/multipleSelect/multipleSelect.provider.js
- src/ng1/directives/treegrid/treegrid.controller.js
- src/ng1/directives/treegrid/treegridMultipleSelectItem.directive.js
Switched tree grid to use separate multiple select instances per component. This solves the problems caused by multiple tree grids on a single page.
(Reported for the MF documentation but also applies to the two tree grid examples - previously selecting a row in one would clear the selection in the other.)
https://jira.autonomy.com/browse/EL-2871
> Added the option to create component-specific multiple select providers

- docs/app/pages/components/components-sections/search/search-builder/search-builder.component.ts
- docs/app/pages/components/components-sections/search/search-builder/snippets/app.ts
- src/components/search-builder/search-builder-group/search-builder-group.component.less
Addresses Roland's Comments:
•	The Add buttons should be vertically aligned with the bottom of the field to their left
•	There should be at least one Text Keyword field in there by default
•	Change the placeholder text for "Enter a keyword" to "Enter keywords"
> Search Builder - Changes for Roland's suggestions

- docs/app/pages/components/components-sections/scrollbar/infinite-scroll-ng1/infinite-scroll-ng1.component.html
- docs/app/pages/components/components-sections/scrollbar/infinite-scroll-ng1/snippets/reset.js
- src/ng1/directives/infiniteScroll/adapters/element-scroll.adapter.js
- src/ng1/directives/infiniteScroll/adapters/scroll-pane.adapter.js
- src/ng1/directives/infiniteScroll/adapters/scroll.adapter.js
- src/ng1/directives/infiniteScroll/adapters/window-scroll.adapter.js
- src/ng1/directives/infiniteScroll/infiniteScroll.controller.js
- src/ng1/directives/infiniteScroll/infiniteScroll.directive.js
Reworked the infinite scroll directive. Rather than manually create all the elements, I have now changed it to use ng-repeat for the list of items and ng-if for showing/hiding items. This allows us to easily update data by letting angular handle all the diffing - and this also reduced the amount of code required significantly.
Added two new broadcast events. One allows the user to reload all currently loaded pages - essentially if there are 5 pages loaded this will call the paging function for pages 1-5 and update the data when it is returned. I also added a reloadPage event that can be passed a specific page number - this will only request the data for that page and update that page only.
Also split out scrollbar handling. We supported scrolling on an element, on a scroll pane and on the …
> EL-2904 - Infinite Scroll Refresh

- src/data/micro-focus-colors.json
- src/ng1/services/colorService/colorService.service.js
- src/services/color/color.service.ts
- Adding missing hash from color map
- Renaming functions to follow naming conventions
- The getColor function now returns a new instance of a ThemeColor rather than the same instance each time. This previously caused issues if I was to use the setAlpha method, which meant any time that color was used in future had the alpha applied to it.
> Fixing issues with color service

- src/ng1/directives/marqueeWizard/marqueeWizard.controller.js
- src/ng1/directives/marqueeWizard/marqueeWizard.html
A URL can be passed to the wizard-icon attribute. If unset, previous behavior is maintained.
https://jira.autonomy.com/browse/EL-2917
> Implemented the marquee-wizard wizard-icon attribute

- src/components/slider/slider.component.ts
JIRA: https://jira.autonomy.com/browse/EL-2937
Related PRs: https://github.houston.softwaregrp.net/caf/quantum/pull/339 & https://github.houston.softwaregrp.net/caf/ux-aspects-micro-focus/pull/122
Normally a minor tick will not appear when a major tick is in the same position - this is expected, however if major ticks are set to be hidden, minor ticks in the same position are still hidden which is incorrect.
> EL-2937 - Fixing slider bug

- src/hybrid/components/slider-chart/slider-chart.directive.ts
- src/hybrid/hybrid.module.ts
- src/hybrid/index.ts
- src/ng1/directives/sliderChart/sliderChart.controller.js
- src/ng1/directives/sliderChart/sliderChart.directive.js
Adding a wrapper for sliders with charts. Initially also intended to add a wrapper for modal inset panel but upon closer inspection discovered that it uses the transclude function to perform manual transclusion which is not supported, raised a separate ticket to cover the migration of it.
> EL-2961 - Adding wrapper for Sliders with Charts

- src/components/page-header/page-header.component.html
- src/components/page-header/page-header.component.ts
- src/components/page-header/page-header.module.ts
- src/services/color/color.service.ts
JIRA: https://jira.autonomy.com/browse/EL-2922
Related: https://github.houston.softwaregrp.net/caf/ux-aspects-micro-focus/pull/128
Adding option to set the family background and foreground colors via attributes on the element. They can either be names from the color palette or css color values.
No documentation required as this is only suitable for MF docs
> EL-2922 - Adding support for setting family colors in page header

- docs/app/data/components-page.json
- docs/app/pages/components/components-sections/wizard/wizard/wizard.component.html
- src/components/wizard/wizard.component.ts
Updated documentation and clarified some other events.
Deprecated the remaining ng1 wizard sections.
https://jira.autonomy.com/browse/EL-2988
> Added stepChanging event to ux-wizard

- src/hybrid/hybrid.module.ts
- src/hybrid/services/navigation-menu/navigation-menu.service.ts
- src/hybrid/services/notification/notification.service.ts
- src/hybrid/services/pdf/pdf.service.ts
- src/hybrid/services/time-ago/time-ago.service.ts
I notice we have recently been getting the following error during build:
```diff
-ERROR in ..\@ux-aspects\ux-aspects\ux-aspects.ts(60,25): 
-Error during template compile of 'HybridModule'. 
-Function calls are not supported in decorators.
```
This fix will prevent this error from occurring
> Fixing Build Error

- src/hybrid/components/marquee-wizard/marquee-wizard.component.ts
- src/ng1/directives/selectTable/selectTable.controller.js
Marquee wizard selector used hyphen instead of camel case.
The select table component was trying to fire a scope.digest whenever the select function is called. This function is only ever called by ng-click, which already does a digest so we were getting errors in the console about multiple digest cycles - this wasn't related to any changes to the wrappers but just discovered while testing them.
> EL-2961 - Fixing wrapper issues

- docs/app/pages/components/components-sections/wizard/marquee-wizard/marquee-wizard.component.ts
The component was looking for snippets folder - but as there are no snippets yet the folder did not exist causing a build error.
> Fixing Build

- docs/app/pages/components/components-sections/wizard/marquee-wizard/marquee-wizard.component.html
- src/components/marquee-wizard/marquee-wizard.component.ts
Related PR: https://github.houston.softwaregrp.net/caf/ux-aspects-micro-focus/pull/135
- Fixing typo
- Removing restriction where you can't go to the previous step if there is an error on the current step - this now matches the functionality of the standard wizard
> Marquee wizard fixes

- src/components/marquee-wizard/marquee-wizard.component.ts
Removing validation requirement to click on previous steps. Now matches standard wizard.
> Marquee Wizard - QA Fix

- docs/app/pages/components/components-sections/dashboard/dashboard/dashboard.component.html
- docs/app/pages/components/components-sections/dashboard/dashboard/snippets/app.html
- src/components/dashboard/dashboard.component.html
- src/components/dashboard/dashboard.component.less
- src/components/dashboard/dashboard.component.ts
- src/components/dashboard/dashboard.module.ts
- src/components/dashboard/dashboard.service.ts
- src/components/dashboard/drag-handle/drag-handle.directive.ts
- src/components/dashboard/widget/dashboard-widget.component.html
- src/components/dashboard/widget/dashboard-widget.component.ts
- src/components/page-header/navigation/navigation.component.ts
- src/components/virtual-scroll/virtual-scroll.component.ts
- src/directives/drag/drag.directive.ts
- src/directives/drag/drag.module.ts
- src/directives/drag/index.ts
- src/directives/layout-switcher/layout-switcher.directive.ts
- src/directives/resize/resize.directive.ts
- src/directives/resize/resize.service.ts
- src/index.ts
- Simplified a lot of the dashboard code
- Separated drag functionality into a separate directive as we were duplicating this code quite a lot, and there are also many other future uses for this functionality
- Updated sample code - it was using attribute before rather than binding to the property value
- No longer using the doCheck lifecycle hook, much more efficient to use setters/getters
- Now using observables in many places. Before there were lots of values that were somewhat dependant on each other, this now ensures values are kept in sync. This allow allows us to use OnPush change detection for better performance, and also prevents the 'Expression has changes after check' error.
- Also fixed bug when resizing downwards past the lower bound of the dashboard
- Updated resize service …
> EL-3015 - Dashboard Improvements

- src/components/spark/spark.component.ts
- src/ng1/directives/spark/spark.directive.js
- src/ng1/directives/spark/spark.html
- src/services/color/color.service.ts
JIRA: https://jira.autonomy.com/browse/EL-3027
- Angular JS spark chart throws an error when a multi spark chart has two values the same. Now fixed
- Error thrown when type property not specified - made this optional as it is not always application now we support multi spark charts
- Made Angular Spark chart to use OnPush change detection
- Added default value to color service to prevent errors
> EL-3027 - Fixing spark chart issues

- src/directives/focus-if/focus-if.directive.ts
JIRA: https://jira.autonomy.com/browse/EL-2977
The ticket was to make a focus when shown directive, this is not needed as we have a focusIf directive which does this already.
In this PR I have moved the focus logic to a setter rather than having this code run every time change detection occurs which is less efficient
> EL-2977 - Improving performance of FocusIf directive

- src/package.json
In response to the issue Thomas was having on slack I have relaxed the ngx-bootstrap version requirement to prevent multiple versions of it being installed.
His app depended on ngx-bootstrap "^2.0.0-beta.8" which was installing version 2.0.2. The ux-aspects package depended on "2.0.0-beta.8" exact - so it was installing multiple versions causing StaticInjectorErrors in a production build
> Removing fixed ngx-bootstrap version to allow newer versions

- docs/app/pages/components/components-sections/buttons/floating-action-button-ng1/floating-action-button-ng1.component.html
- docs/app/pages/components/components-sections/buttons/floating-action-button-ng1/floating-action-button-ng1.component.ts
- docs/app/pages/components/components-sections/buttons/floating-action-button-ng1/snippets/floating-action-button.html
- docs/app/pages/components/components-sections/buttons/floating-action-button-ng1/snippets/floating-action-button.js
- src/hybrid/components/floating-action-button/floating-action-button.component.ts
- src/ng1/directives/floatingActionButton/floatingActionButton.directive.js
- src/ng1/directives/floatingActionButton/floatingActionButton.html
Had to rename the directive property, it was previously using tooltip and tooltip placement but as they are attributes also used by ui-bootstrap, tooltips were being created and shown twice.
> EL-3028 - Floating Action Button Tooltips

- src/components/dashboard/dashboard.service.ts
Added safety check to ensure the widgets are not wider than the number of columns in the dashboard.
Previously this would have resulted in an infinite loop, crashing the page - now it throws an exception with a useful message indicating how to resolve the issue
> EL-3010 - Dashboard Infinite Loop fix

- src/ng1/directives/infiniteScroll/infiniteScroll.controller.js
There was a chance the setter (which sets this._query) was getting called before the constructor. Currently the constructor sets this._query to null initially which could cause the search query to be missing when the page is loaded.
Added a minor change to only set the initial value if one hasn't already been set.
> Fixing infinite scroll issue for victor

- docs/app/services/plunker/templates/config_js.txt
- ng-package.json
- src/directives/reorderable/dragula.ts
- src/directives/reorderable/reorderable.directive.ts
Turns out ng-packagr keeps `require` statements dynamic so I had to use a different workaround to allow us to use the dragula library. Should work as expected now.
> Fixing dragula plunker issue

- docs/app/services/plunker/templates/config_js.txt
Updated the dragula plunker link to use the prebuilt version of the library.
**Ignore my comments below - seems to have resolved itself by now**
Note Im currently getting errors in plunker eg:
This is not related to this ticket - if you look in the released site the plunkers are also currently not working. This is an issue with unpkg.com - this happened one time before and resolved itself after a short while.
To test plunker is working you can temporarily edit the config to specify the exact version of any packages giving errors, eg:
```
'@angular/core': 'https://unpkg.com/@angular/core@5.2.9/bundles/core.umd.js',
```
> Updating dragula plunker url

- src/services/color/color.service.ts
This does not appear in the color palette, but is referred to in the Family Logos section: http://everythingux.net/styleguide/corporate-brand/families-product-icons/
https://jira.autonomy.com/browse/EL-2748
> Added "forest green"

- package.json
I noticed that my npm installed 1.6.0 and the build machine installed 1.7.0.
> Trying an older version of ng-packagr

- docs/app/pages/components/components-sections/tables/selection/selection.component.html
- docs/app/pages/components/components-sections/tables/selection/snippets/app.html
- e2e/tests/components/page-header/page-header.e2e-spec.ts
- src/components/page-header/page-header.service.ts
- Selection example missing hover styling on rows (added .table-hover class)
- Masthead if you click the "Showcase" tab when one of its children are currently selected it will deselect the child. This no longer happens and added a test to cover this case
> Fixing QA/Acceptance Comments

- configs/loaders/uglifyjs-loader.js
- configs/webpack.docs.prod.config.js
- configs/webpack.ng1-assets.dev.config.js
- configs/webpack.ng1.config.js
- package-lock.json
- package.json
Did a bit of digging and the build issue seems to be being caused by ng-packagr which has a dependency on uglify-js^3.0.7.
One of the recent uglify releases seems to have broken this. I have fixed the version of uglify so we don't use a broken version. Fixes the issue at least when I try it on my local machine
> Fixing build issue

- docs/app/data/components-page.json
- docs/app/pages/components/components-sections/panels/panels.module.ts
- docs/app/pages/components/components-sections/panels/side-panel/side-panel.component.html
- docs/app/pages/components/components-sections/panels/side-panel/side-panel.component.ts
This should be able to replace the deprecated components. `ux-item-display-panel` will remain but relevant functionality would be factored out into the generic component.
https://jira.autonomy.com/browse/EL-2972
> Documentation for generic side modal component

- docs/app/data/components-page.json
- docs/app/pages/components/components-sections/input-controls/expanding-text-area/expanding-text-area.component.html
- docs/app/pages/components/components-sections/input-controls/expanding-text-area/expanding-text-area.component.less
- docs/app/pages/components/components-sections/input-controls/expanding-text-area/expanding-text-area.component.ts
- docs/app/pages/components/components-sections/input-controls/expanding-text-area/snippets/app.css
- docs/app/pages/components/components-sections/input-controls/expanding-text-area/snippets/app.html
- docs/app/pages/components/components-sections/input-controls/expanding-text-area/snippets/app.ts
- docs/app/pages/components/components-sections/input-controls/input-controls.module.ts
- e2e/pages/app/app.module.ts
- e2e/pages/app/expanding-text-area/expanding-text-area.module.ts
- e2e/pages/app/expanding-text-area/expanding-text-area.testpage.component.html
- e2e/pages/app/expanding-text-area/expanding-text-area.testpage.component.less
- e2e/pages/app/expanding-text-area/expanding-text-area.testpage.component.ts
- e2e/tests/components/expanding-text-area/expanding-text-area.e2e-spec.ts
- e2e/tests/components/expanding-text-area/expanding-text-area.po.spec.ts
- src/directives/auto-grow/auto-grow.directive.ts
- src/directives/auto-grow/auto-grow.module.ts
- src/directives/auto-grow/index.ts
- src/index.ts
- Created new Angular directive
- Added documentation section and deprecated old section
- Added protractor tests
Old component had two attributes which I have removed:
- max lines - This is better just set using css as that gives more flexibility eg, flexbox and % etc..
- disable return - This was fairly useless before as you could paste stuff in that had multiple lines. In the rare case that they would want this, this should be handled using ngModel rather than part of this directive.
> EL-2970 - Expanding textarea migration

- src/styles/splitter.less
- Fixing icon alignment all browsers
- Note: The animation in IE is an issue with the angular-split library, I tried visiting their example page: https://bertrandg.github.io/angular-split/#/examples/split-transitons in IE and was getting the same issue. I have raised an issue on the library github regarding this issue: https://github.com/bertrandg/angular-split/issues/103
> EL-2973 - Side inset splitter QA fixes

- e2e/tests/components/hierarchy-bar/hierarchy-bar.e2e-spec.ts
- e2e/tests/components/hierarchy-bar/hierarchy-bar.po.spec.ts
- src/components/hierarchy-bar/hierarchy-bar.component.html
- src/components/hierarchy-bar/hierarchy-bar.component.less
- Firefox doesn't seem to like having elements with a click event as a child of a button. Replaced it will a div with a tabindex
> EL-2942 - Hierarchy bar firefox fix

- docs/app/pages/components/components-sections/drag-and-drop/drag-and-drop-cards/snippets/app.ts
- src/directives/reorderable/reorderable.service.ts
* Changed ReorderableGroup.config to be private to avoid exposing the DragulaOptions type.
* Also noticed an omission in the example snippet.
> Fixed dragula type error

- src/components/dashboard/dashboard.service.ts
Using pageX & pageY instead of x & y. Also taking into account the scroll position
> EL-3137 - Dashboard - IE resize fix

- Gruntfile.js
- configs/webpack.docs.dev.config.js
- docs/app/pages/components/components-sections/page-header/page-header/page-header.component.html
- docs/app/pages/components/components-sections/page-header/page-header/page-header.component.ts
- docs/app/pages/components/components-sections/page-header/page-header/snippets/app.ts
- e2e/tests/components/page-header/page-header.po.spec.ts
- src/components/breadcrumbs/breadcrumbs.component.html
- src/components/page-header/icon-menu/icon-menu.component.html
- src/components/page-header/icon-menu/icon-menu.component.less
- src/components/page-header/icon-menu/icon-menu.component.ts
- src/components/page-header/navigation/navigation-dropdown-item/navigation-dropdown-item.component.html
- src/components/page-header/navigation/navigation-dropdown-item/navigation-dropdown-item.component.ts
- src/components/page-header/navigation/navigation-item/navigation-item.component.html
- src/components/page-header/navigation/navigation-item/navigation-item.component.less
- src/components/page-header/navigation/navigation-item/navigation-item.component.ts
- src/components/page-header/navigation/navigation.component.ts
- src/components/page-header/page-header.component.html
- src/components/page-header/page-header.component.less
- src/components/page-header/page-header.component.ts
- src/components/page-header/page-header.module.ts
- src/directives/menu-navigation/index.ts
- src/directives/menu-navigation/menu-navigation-item.directive.ts
- src/directives/menu-navigation/menu-navigation-toggle.directive.ts
- src/directives/menu-navigation/menu-navigation.directive.ts
- src/directives/menu-navigation/menu-navigation.module.ts
- src/directives/menu-navigation/menu-navigation.service.ts
- src/index.ts
- src/styles/breadcrumbs.less
* Changed navigation and navigation dropdown items to have distinct toggle buttons. These have different layouts depending on whether they have children.
* Added keyboard support for the navigation menu via new directive `uxMenuNavigation`.
* Added roles to the page header sections.
* Added `grunt build:library` for a library-only build.
* Added `uxMenuNavigationToggle` which can be exported and attached to `uxMenuNavigation` to handle keyboard navigation.
* Applied keyboard navigation to the icon menu component.
* Added `label` property to `PageHeaderIconMenu` which attaches an aria-label. Documented this.
* Added standard focus rings to focusable header components.
* Updated code snippets and documentation.
https://jira.autonomy.com/browse/EL-3060
> EL-3060 - WCAG Page Header

- configs/webpack.docs.dev.config.js
- package.json
- src/components/page-header/icon-menu/icon-menu.component.html
- src/components/page-header/icon-menu/icon-menu.component.less
- src/components/page-header/icon-menu/icon-menu.component.ts
- src/components/page-header/index.ts
- src/components/page-header/interfaces.ts
- src/components/page-header/page-header.component.ts
- src/components/page-header/page-header.service.ts
* Added currently active icon menu to the service to ensure only one is open at a time.
* Changed the icon dropdown item layout to flexbox to resolve float issue in Firefox.
* Removed https from the webpack config and added `npm run start:https` task.
https://jira.autonomy.com/browse/EL-3060
> WCAG Page Header fixes

- src/directives/focus-if/focus-if.directive.ts
Adding support for delay in focusIf directive. Useful for animated modals so we can delay the focus until the elements are visible
> Adding support for a delay in focusIf directive

- src/components/select/select.component.html
- src/components/select/select.component.ts
- src/components/tag-input/tag-input.component.ts
- src/components/typeahead/typeahead.component.ts
* Added a `clicking` property to ux-typeahead to indicate when the mouse is down over the element.
* Added a check for the typeahead clicking property in the blur handlers for ux-select and ux-tag-input.
* Also added subscription cleanup to ux-tag-input.
Sorry, I don't know why the diffs aren't working correctly.
https://jira.autonomy.com/browse/EL-3156
> Fixed a focus issue with IE11

- guides/angular-update-guide.md
Adding guide covering the steps required to update from v4 -> v5 and v5 -> v6 (both using the CLI and Webpack)
> EL-3134 - Adding Angular update guide

- src/directives/selection/selection-item.directive.ts
- src/directives/selection/selection.directive.ts
- src/directives/selection/selection.service.ts
This was caused by the selection container receiving focus when the user clicks on the scroll bar. Instead of the container being focusable, similar functionality has been provided by managing the tabindex property of the selection items. It's possible to override this by specifying the tabindex property.
* Added focusTarget$ observable to the service, which differs from active$ in that it is never null after initialization. This determines the item which has tabindex="0"; all others are tabindex="-1".
* Changed the default tabindex on the container to null (not focusable).
* Changed the default tabindex on the item to be null (managed by the component).
Plunker to assist verification (using localhost):
https://plnkr.co/edit/0A717su2PL57seReQJUk?p=preview …
> Fixed uxSelection focus issue

- src/components/dashboard/drag-handle/drag-handle.directive.ts
- src/directives/drag/drag.directive.ts
- src/directives/observers/index.ts
- src/directives/observers/observers.module.ts
- src/directives/observers/overflow/overflow-observer.directive.ts
- src/directives/resize/resize.service.ts
- src/index.ts
Related PR: https://github.houston.softwaregrp.net/caf/quantum/pull/496 & https://github.houston.softwaregrp.net/caf/ux-aspects-micro-focus/pull/216
- Added option to uxDrag directive to show a clone of the element while dragging
- Added overflow observer directive to easily determine if there is any overflow occuring
- Updated resize directive to ensure added elements are not detected by a screen reader
> EL-3142 - Calendar Month View

- src/components/page-header/page-header.module.ts
I trialled using ux-tabset for secondary nav but removed it so this import is not required at all.
https://jira.autonomy.com/browse/EL-3168
> Fixed a build issue caused by recent page header changes

- .gitignore
- docs/app/data/components-page.json
- docs/app/pages/components/components-sections/conduits/conduit/conduit.component.ts
- docs/app/pages/components/components-sections/conduits/conduits.module.ts
- docs/app/pages/components/components-sections/conduits/multiple-zones/example/example.component.ts
- docs/app/pages/components/components-sections/conduits/multiple-zones/multiple-zones.component.ts
- docs/app/pages/components/components-sections/conduits/multiple-zones/snippets/app.component.ts
- e2e/pages/app/app.module.ts
- e2e/pages/app/conduits/conduit.component.html
- e2e/pages/app/conduits/conduit.component.ts
- e2e/pages/app/conduits/conduits.module.ts
- e2e/pages/app/conduits/zones/zone-one/zone-one.component.html
- e2e/pages/app/conduits/zones/zone-one/zone-one.component.ts
- e2e/pages/app/conduits/zones/zone-three/zone-three.component.html
- e2e/pages/app/conduits/zones/zone-three/zone-three.component.ts
- e2e/pages/app/conduits/zones/zone-two/zone-two.component.html
- e2e/pages/app/conduits/zones/zone-two/zone-two.component.ts
- e2e/tests/components/conduits/conduits.e2e-spec.ts
- e2e/tests/components/conduits/conduits.po.spec.ts
- src/components/conduit/conduit-subject.ts
- src/components/conduit/conduit-zone.service.ts
- src/components/conduit/conduit.module.ts
- src/components/conduit/index.ts
Adding conduit tests and fixing some bugs revealed when creating tests:
- Issue with dynamically adding conduit, it would not get an initial value. To fix this I removed the need for a root zone, which got a bit complex injecting and passing data up and down the zone hierarchy, instead we now just have two static fields shared across all zones. Also needed to move the position of the getInitialValue() call to get called earlier.
- With the changes mentioned above, I also removed the ConduitModule as it is now no longer needed - it originally just registered a root zone. Updated docs and examples to remove ConduitModule.
- Also issue when destroying a zone - it was destroying all conduits except the ones in the zone, when it should have been doing the opposite.
> EL-3153 - Adding Conduit Tests

- src/components/floating-action-buttons/floating-action-button.component.html
Clicking on the primary button a second time should close the floating action button list. Currently clicking repeatedly does nothing. You must click off the button in order to close the menu.
> Click on primary button should toggle open state

- src/directives/observers/overflow/overflow-observer.directive.ts
As it turns out, sometimes IE decides to add a pixel to the height of something, which can cause overflow to be detected incorrectly.
Added a tolerance option to allow a specific amount of overflow before it emits that there is overflow.
> EL-3142 - Calendar Overflow

- docs/app/pages/components/components-sections/buttons/floating-action-button/floating-action-button.component.html
- src/components/floating-action-buttons/floating-action-buttons.component.ts
I have a component that consumes the FloatingActionButtonsComponent and needs to track the open state. There was no way that I could find to do this with the current API. So, I added a get property to return the open$ observable from the FloatingActionButtonsService.
> Add openChange event to floating action button

- src/ng1/directives/multipleSelect/multipleSelect.provider.js
- src/ng1/directives/treegrid/treegrid.controller.js
- src/ng1/directives/treegrid/treegrid.html
- src/ng1/directives/treegrid/treegridMultipleSelectItem.directive.js
* For pre-determined data, traverse the source data tree and update the items in the multipleSelectProvider directly.
* For lazy loaded data, update the items in the multipleSelectProvider as soon as they are loaded (after expanding parent).
https://jira.autonomy.com/browse/EL-3181
> Ensure the selectChildren option applies to rows that are not visible

- docs/app/pages/components/components-sections/flippable-cards/flippable-cards.module.ts
- docs/app/pages/components/components-sections/flippable-cards/flippable-cards/flippable-cards.component.html
- docs/app/pages/components/components-sections/flippable-cards/flippable-cards/flippable-cards.component.less
- docs/app/pages/components/components-sections/flippable-cards/flippable-cards/flippable-cards.component.ts
- docs/app/pages/components/components-sections/flippable-cards/flippable-cards/snippets/app.css
- docs/app/pages/components/components-sections/flippable-cards/flippable-cards/snippets/app.html
- docs/app/pages/components/components-sections/flippable-cards/flippable-cards/snippets/app.ts
- src/components/flippable-card/flippable-card.component.html
- src/components/flippable-card/flippable-card.component.less
- src/components/flippable-card/flippable-card.component.ts
- src/ng1/directives/nestedDonut/nestedDonut.directive.js
- src/styles/utilities.less
JIRA: https://jira.autonomy.com/browse/EL-3051
- Reworked Example Code - the layout spilled outside it container a lot causing focus ring to have weird bits sticking out. Now reworked to be simpler and container within the flippable card (with the exception of the icon at the top). Also improved accessibility.
- Made cards focusable and added support for enter/spacebar
- Updated code snippets
- Nested donut chart - IE by default focuses SVGs on tabbing whereas other browsers do not. Added `focusable="false"` attribute to have consistent tabbing behavior
> EL-3051 - Flippable Cards WCAG

- src/ng1/directives/overflowTooltip/singleLineOverflowTooltip.controller.js
- src/ng1/directives/overflowTooltip/singleLineOverflowTooltip.spec.js
Jane raised a ticket on single line overflow performance (https://jira.autonomy.com/browse/EL-3193). Roland happy to include in current sprint.
- Removed use of $timeout as this was running a $rootScope.$digest after each tooltip was applied.
- We were initially determining if all tooltips needed to be shown when the directive initialised and we also were re-checking any time the content changed or the element resized which was unnecessary. Instead we now only check when the tooltip would normally be shown, so when the mouse enters the element we do the check.
> EL-3193 - Single Line Overflow Tooltip Performance

- configs/webpack.docs.prod.config.js
- package.json
Attempting to fix the webpack out of memory error.
- Turning of Uglify mangling as this can be quite an intensive task
- Increasing Webpack's memory cap. I noticed when I was getting this error the build took forever, probably due to all the garbage collection. Bumping this up should make the build go a lot quicker than what you were seeing, usually the docs site production build takes ~4 mins on my machine when the memory error did not occur.
> Webpack Memory Issue

- docs/app/data/components-page.json
- docs/app/pages/components/components-sections/date-time-picker/date-time-picker.module.ts
- docs/app/pages/components/components-sections/date-time-picker/time-picker/snippets/app.html
- docs/app/pages/components/components-sections/date-time-picker/time-picker/snippets/app.ts
- docs/app/pages/components/components-sections/date-time-picker/time-picker/time-picker.component.html
- docs/app/pages/components/components-sections/date-time-picker/time-picker/time-picker.component.ts
- src/components/time-picker/time-format.pipe.ts
- src/components/time-picker/time-picker.component.html
- src/components/time-picker/time-picker.component.less
- src/components/time-picker/time-picker.component.ts
- src/styles/documentation.less
* Added documentation and deprecated the ng1 section.
* Fixed an issue where time values were not padded in Firefox, this is an issue with type="number" in FF so I changed the type to text.
* Also changed the padding for hours, this is conventionally not padded in 12-hour mode.
* Fixed an alignment issue with the customize section styling.
https://jira.autonomy.com/browse/EL-3046
> Added time picker documentation

- src/components/media-player/extensions/controls/controls.component.html
- src/components/media-player/extensions/controls/controls.component.less
- src/components/media-player/extensions/controls/controls.component.ts
- src/components/media-player/media-player.component.html
- src/components/media-player/media-player.component.ts
- src/components/media-player/media-player.service.ts
- Making controls remain visible until focus leaves the controls
- Removing faded tick on focus to meet wcag contrast requirements
- Positioning subtitles higher to avoid being behind the controls
> EL-3057 - Media Player QA Fixes

- guides/angular-upgrade-guide.md
After working on the enterprise search upgrade, I have updated the guide to reflect some improvements I came across.
- Adding in `rxjs-compat` for Angular 6 support
- Added RXJS path mappings to ensure the `rxjs-compat` library is used in development mode.
- Changed `html-loader` to `raw-loader`. Its likely that an existing grunt task is handling the copying of assets. Using `raw-loader` continues allowing seamless integration with the existing task, whereas `html-loader` tries to handle all assets it discovers.
- Added `to-string-loader`, using the `css-loader` on its own can cause an issue in production mode.
- Added AngularJS type definitions for better VS Code development experience and auto complete.
- Added information on using `PurifyPlugin` in production mode, in enterprise search …
> Angular upgrade guide improvements

- src/ng1/directives/marqueeWizard/marqueeWizard.html
- src/styles/wizard.less
I've found another issue with the Marquee Wizard which should be easy to fix for 1.6.1: the `wizard-icon` property is not working because the markup is checking for a property named `icon` instead (see [here](https://github.com/UXAspects/UXAspects/blob/develop/src/ng1/directives/marqueeWizard/marqueeWizard.html#L7-L8). I changed the code to check for `wizardIcon` and I was able to see the proper icon. However, once that happened, I noticed the custom icon size is not the same as the default icon (48px). This is because the `marquee-wizard-user` class is not applied in both cases. To address that, I created a class named `marquee-wizard-icon` and applied to both the default and custom marquee wizard icons.
> Fixing issue with Marquee Wizard icon and its size

- docs/app/pages/components/components-sections/page-header/page-header/page-header.component.html
- docs/app/pages/components/components-sections/page-header/page-header/page-header.component.ts
- src/components/page-header/page-header.component.html
- src/components/page-header/page-header.component.less
- src/components/page-header/page-header.component.ts
* Removed the upper and lower containers of the non-condensed page header. This makes it easier to style the MF layout.
* Added an alternate `header` element in the logo container. which is not shown by default. This is to be used in the MF layout.
* Added `title` property and a title template option.
* Added `crumbsStyle` to allow the old breadcrumb style.
* Renamed `family*` properties to `logo*` with aliases for backward compatibility.
https://jira.autonomy.com/browse/EL-3219
> EL-3219 - Masthead icon and title

- src/components/tag-input/tag-input.component.ts
Since we could not get a repro, added a property `trackAriaDescendant` which can be set to false to omit the tracking altogether. This issue will be resolved in a future ticket after a repro case can be put together.
https://jira.autonomy.com/browse/EL-3224
> EL-3224 - workaround for "Expression has changed after it was checked"

- src/components/table/table-column-resize/resizable-table-column.component.html
I recently renamed the events that uxDrag emits as they used to be `(dragstart)`, `(drag)` and `(dragend)` which are also native browser events which clashed, causing errors. I updated all usages, but as this wasn't merged at the time this got missed. The outputs should now be updated to use the correct names.
> Fixing column resizing

- docs/app/pages/components/components-sections/panels/item-display-panel-ng1/item-display-panel-ng1.component.html
- src/ng1/directives/displayPanels/displayPanel.service.js
- src/ng1/directives/displayPanels/displayPanel/displayPanel.directive.js
- src/ng1/directives/displayPanels/displayPanelItem/displayPanelItem.directive.js
- src/ng1/directives/displayPanels/displayPanels.module.js
The display panel listens for a document mouse up event to check if an outside click has occurred. To prevent clicks within a modal from closing a display panel you can use `ng-mouseup="$event.stopPropagation()"`. I have documented this.
> EL-3221 - Item Display Panel

- src/components/table/table-column-resize/resizable-table-column.component.ts
- src/components/table/table-column-resize/resizable-table.directive.ts
Angular 5 doesn't support the generic type on ElementRef causing build errors. Fixing the issue
> Fixing Angular 5 Issue

- src/ng1/directives/splitter/splitter.directive.js
When inserting the toggle button a search was performed for `.gutter`, however when there is a nested splitter in the first splitter panel, it was detecting the gutter in the nested splitter rather than the parent splitter.
Altered the query to only perform the search on immediate children
> EL-3226 - Splitter Panel Bug Fix

- src/components/popover/popover.component.less
Reverted change that previously removed the max-width. This change was made as part of the colour picker ticket, however the colour picker ended up using the dropdown instead of the popover anyway so this change has no effect on the colour picker.
> EL-3237 - Static Tooltip Width

- docs/app/pages/components/components-sections/buttons/dropdowns/dropdowns.component.less
- src/styles/navigation.less
- Ensuring that there is always enough spacing between the dropdown item and the shortcut hint
- Ensuring that the scrollbar does not appear in the middle of the menu
> EL-3227 - Button Dropdown Spacing

- docs/app/pages/components/components-sections/tables/column-resizing/column-resizing.component.html
- docs/app/pages/components/components-sections/tables/column-resizing/column-resizing.component.less
- docs/app/pages/components/components-sections/tables/column-resizing/snippets/app.css
- docs/app/pages/components/components-sections/tables/column-resizing/snippets/app.html
- src/components/checkbox/checkbox.component.less
- Changed example class name to avoid conflicting with existing class with that name
- Also added a class to our checkbox component so that the margin can easily be removed as it was causing some alignment issues which meant having to use ::ng-deep or changing the ViewEncapsulation and we shouldn't be forcing either of these
> EL-3242 - Resizable Table QA Fixes

- bower.json
- docs/app/data/config.dev.json
- docs/app/data/config.json
- docs/app/pages/changelog/changelog.component.ts
- docs/app/pages/changelog/logs/release-v1.6.5.md
- docs/app/services/app-configuration/app-configuration.service.ts
- docs/app/services/codepen/codepen.service.ts
- docs/app/services/plunker/plunker.service.ts
- package-lock.json
- package.json
- src/package.json
To accommodate the Stack B hosting of the site, as well as future CI builds, I have removed the explicit `assetsUrl` config setting and instead derived the URL from the active location.
This also means that plunker can load in Firefox in development mode by accessing the documentation at http://127.0.0.1:8080.
https://autjira.microfocus.com/browse/EL-3251
> Release 1.6.5

- docs/app/services/app-configuration/app-configuration.service.ts
The path was empty, causing getBaseUrl() to return an empty string.
https://autjira.microfocus.com/browse/EL-3251
> Fixed an issue which appeared when navigating to the base URL directly

- docs/app/pages/components/components-sections/date-time-picker/date-time-picker/date-time-picker.component.html
- docs/app/pages/components/components-sections/date-time-picker/date-time-picker/date-time-picker.component.ts
- src/components/date-time-picker/date-time-picker.component.ts
- src/components/date-time-picker/date-time-picker.config.ts
- src/components/date-time-picker/date-time-picker.module.ts
- src/components/date-time-picker/date-time-picker.service.ts
- src/components/date-time-picker/date-time-picker.utils.ts
- src/components/date-time-picker/day-view/day-view.component.ts
- src/components/date-time-picker/day-view/day-view.service.ts
- src/components/date-time-picker/month-view/month-view.service.ts
- Added month and monthShort properties to our date picker config service
- Added a forRoot function on our module to ensure this service is only imported in the app module, otherwise this will not work in lazy loaded modules.
- Updated components to always use the value from the config service when it is available - otherwise fallback on default values
- Documented the configuration service
- Added month properties to the component to change it only for a specific instance of the component rather than setting it as the global default
Additional Issue Reported. The day headers were showing Friday when the day was actually a Thursday. It turns out we had an array of day names. The array started at Monday, when Sunday would be day 0 so I have reordered the array to display correctly. We may …
> EL-3268 - Adding Date Picker Localization Support

- package.json
The updated version of highlight.js was causing a build error, so I have removed the range operator.
> Fixed a dependency which was causing build problems

- src/ng1/directives/hoverActions/hoverAction.directive.js
The linter expected ternary expressions to be part of an assignment.
> Fixed lint issue

- docs/app/pages/changelog/changelog.component.ts
- docs/app/pages/changelog/logs/release-v1.6.6.md
- docs/app/services/app-configuration/app-configuration.service.ts
Updated the changelog component to replace `{{baseUrl}}` with the application's base URL. This is mostly for the MF site to allow links to work for stack B users as well.
https://autjira.microfocus.com/browse/EL-3276
> Release 1.6.6

- src/components/date-time-picker/index.ts
The interface got moved due to it causing a circular dependency, however where it was moved to wasn't getting exported by the index.ts
> Adding missing export

- docs/app/pages/components/components-sections/search/search-builder-ng1/snippets/custodianComponent.html
- docs/app/pages/components/components-sections/search/search-builder-ng1/snippets/custodianComponent.js
- docs/app/pages/components/components-sections/search/search-builder-ng1/snippets/custodianPanel.html
- docs/app/pages/components/components-sections/search/search-builder-ng1/snippets/custodianPanel.js
- docs/app/pages/components/components-sections/search/search-builder-ng1/wrapper/search-builder-wrapper.directive.ts
- docs/app/pages/components/components-sections/select/select-ng1/snippets/sample.html
- src/ng1/directives/dynamicSelect/dynamicSelect.controller.js
Updated the Search Builder example to use objects for Custodians to demonstrate this use case.
Added track by to avoid adding the $$hashKey to the source object.
https://autjira.microfocus.com/browse/EL-3291
> EL-3291 - fixing errors when ngModel is null/undefined

- src/components/navigation/index.ts
- src/components/select-list/multiple-select-list.strategy.ts
- src/components/select-list/select-list-item/select-list-item.component.ts
- src/components/select-list/select-list.component.ts
- src/components/select-list/single-select-list.strategy.ts
- src/directives/menu-navigation/index.ts
- src/directives/selection/selection-item.directive.ts
- src/directives/selection/selection.directive.ts
- src/directives/selection/selection.service.ts
- src/directives/selection/strategies/row-alt-selection.strategy.ts
- src/directives/selection/strategies/row-selection.strategy.ts
- src/directives/selection/strategies/selection.strategy.ts
- src/directives/selection/strategies/simple-selection.strategy.ts
- src/directives/tree-grid/index.ts
- src/hybrid/index.ts
- src/tsconfig-build.json
- Select list now updates selected items when the input changes
- Now using `tick` operator to avoid expression changed error
Also made a few additional changes:
- Removed the use of `any` and instead used a generic for all selection classes to help typescript flow types better. For example, as we were using `any` TypeScript was not able to detect that one of our selection strategies did not correctly follow the base Selection Strategy api, which I have corrected.
- After yesterdays release issue I went through our public API and found a few things that were not getting exported (note these were never getting exported so it is not a regression) but some directives for example were not getting exported so consuming applications could not use `@ViewChildren` to reference these directives if …
> EL-3278 - Select List

- docs/app/app.component.ts
- docs/app/data/components-page.json
- docs/app/data/css-page.json
- docs/app/data/team-page.json
- docs/app/pages/components/components-sections/buttons/buttons.module.ts
- docs/app/pages/components/components-sections/buttons/split-button-dropdowns/snippets/app.html
- docs/app/pages/components/components-sections/buttons/split-button-dropdowns/snippets/app.ts
- docs/app/pages/components/components-sections/buttons/split-button-dropdowns/split-button-dropdowns.component.html
- docs/app/pages/components/components-sections/buttons/split-button-dropdowns/split-button-dropdowns.component.ts
- Adding Split Button Dropdown section to buttons section on components page
- Deprecating Button Dropdowns and Split Button Dropdowns on CSS page as these are using Bootstrap.js, not even Angular
- Marking a lot of sections in CSS as AngularJS as the example code is using AngularJS and this could be confusing if someone using Angular copies and pastes the code and it doesn't work.
- Updating our email addresses on Team page to be `@microfocus.com`
Related Pr: https://github.houston.softwaregrp.net/caf/ux-aspects-micro-focus/pull/293
> EL-3286 - Split Button Dropdown

- docs/app/pages/components/components-sections/tree-view/tree-grid-ng1/tree-grid-ng1.component.html
- src/hybrid/components/tree-grid/tree-grid.component.ts
- src/ng1/directives/multipleSelect/multipleSelect.provider.js
- src/ng1/directives/pageTitle/pageTitle.directive.js
- src/ng1/directives/selectTable/selectTable.controller.js
- src/ng1/directives/selectTable/selectTable.spec.js
- src/ng1/directives/treeView/treeView.spec.js
- src/ng1/directives/treegrid/treegrid.controller.js
- src/ng1/directives/treegrid/treegrid.directive.js
- src/ng1/directives/treegrid/treegrid.spec.js
- src/styles/tables.less
- Adding 2 way binding to tree view selected property
- Exposing the multipleSelectProvider instance
- List hover actions - I noticed when hovering on a focused and selected item in the tree grid the list hover actions got the wrong background colour. While looking into this we had styles setting the background colour to match the various states. This was completely unnecessary, removing the background colour all together ensures they will not differ from the table row colour
- Fixing up unit tests (they all should now pass)
- Found two minor issues when fixing unit tests - page header didn't explicitly state its injectable which causes it not to work when minified and select table reselect option didn't work as it was clearing the selection before storing it.
> EL-3299 - Tree Grid Selection

- src/ng1/directives/treegrid/treegridMultipleSelectItem.directive.js
Fixing selectAll issue where selection state is not presented on the tree grid items
> EL-3299 - Tree Grid Selection Fix

- package.json
- src/package.json
If consumers pick up the latest version of angular-split with removed `minSize` property on `SplitAreaDirective` then our accessibility directive will not work.
https://github.com/bertrandg/angular-split/commit/896f923896029750733c31806d6fe647ebcac6d3#diff-45d2b69149c3063c36bd7d65505d25a8
> Fixed angular-split version in the library dependencies

- Gruntfile.js
- bower.json
- grunt/clean.js
- grunt/copy.js
- grunt/run.js
- official-build.props
- package-lock.json
- package.json
- pom.xml
- src/package.json
* Renamed grunt tasks to more accurately identify what they do.
* Added release-staging task to pom.xml:
* Strips prerelease identifier from the package.json for both built NPM packages.
* Creates the release packages.
* Moves the release packages to `target/release-staging`.
* Added new build properties (to be uncommented when implemented).
* Also bumped the version for the next release.
https://autjira.microfocus.com/browse/EL-3266
> EL-3266 - SEPG release staging

- docs/app/pages/components/components-sections/tree-view/tree-grid-ng1/snippets/sample.html
- docs/app/pages/components/components-sections/tree-view/tree-grid-ng1/snippets/sample.js
- docs/app/pages/components/components-sections/tree-view/tree-grid-ng1/tree-grid-ng1.component.html
- docs/app/pages/components/components-sections/tree-view/tree-grid-ng1/tree-grid-ng1.component.ts
- docs/app/pages/components/components-sections/tree-view/tree-grid-ng1/wrapper/actions.html
- docs/app/pages/components/components-sections/tree-view/tree-grid-ng1/wrapper/displayPanelFooter.html
- src/ng1/directives/treegrid/treegrid.controller.js
- src/ng1/directives/treegrid/treegrid.spec.js
* Added `expandedProperty` option which allows binding a source data property to the `row.expanded` property, thus allowing the initial expanded state to be provided and changes to be persisted.
* Update the documentation with the above.
* Cleaned up some snippets to avoid overflow.
Testing plunkers:
https://codepen.io/donnamarijne/pen/QJrLZj?editors=1010
https://codepen.io/donnamarijne/pen/PxeqWx?editors=1010
https://autjira.microfocus.com/browse/EL-3293
> EL-3293 - tree grid expand state

- docs/app/pages/components/components-sections/tables/fixed-header-table/fixed-header-table.component.html
- Added documentation to mention that when using a percentage value for `tableHeight` the table element needs a height set.
I did look into doing this automatically but there are conditions where just setting 100% height on the table if they specify a percentage value still doesn't solve the problem. If you have any other suggestions I'm happy to try them.
> EL-3298 - Fixed Header Table Documentation

- configs/webpack.dev.config.js
- configs/webpack.ng1-assets.dev.config.js
- configs/webpack.ng1.config.js
- Webpack `mode` was set to production which minifies the bundle by default
- Now set to development mode and lets the existing grunt task minify the bundle as it used to
> EL-3316 - AngularJS Fixing Minification Issue

- src/components/select-list/select-list.component.ts
- src/components/select-list/strategies/multiple-select-list.strategy.ts
- src/components/select-list/strategies/single-select-list.strategy.ts
- src/directives/selection/selection.service.ts
- src/directives/selection/strategies/selection.strategy.ts
The setter was always calling deselectAll before storing the new selection whenever any change was made, which resulted in a large amount of events getting emitted.
Now we only deselect and update the selection whenever the selection has actually changed. Also added an additional check to see if the array are different but both have 0 items then also do nothing.
Now instead of like 80 events emitted each click, we get 1 during multiple selection and 2 in single selection (single selection must first deselect the previously selected item then select the new one which results in 2 emissions).
> EL-3311 - Select List Event Emitter Fix

- docs/app/pages/components/components-sections/tables/column-resizing/column-resizing.component.html
- docs/app/pages/components/components-sections/tables/column-resizing/snippets/app.html
- docs/app/pages/components/components-sections/tables/selection/selection.component.html
- docs/app/pages/components/components-sections/tables/selection/snippets/app.html
Related PR: https://github.houston.softwaregrp.net/caf/quantum/pull/598
Updating documentation examples to consistently use .checkbox-column class
https://autjira.microfocus.com/browse/EL-3306
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3306-Checkbox-Alignment-QA
> EL-3306 - Checkbox Alignment QA

- docs/app/pages/components/components-sections/date-time-picker/date-time-picker/date-time-picker.component.html
- e2e/pages/app/app.module.ts
- e2e/pages/app/date-time-picker/date-time-picker.module.ts
- e2e/pages/app/date-time-picker/date-time-picker.testpage.component.html
- e2e/pages/app/date-time-picker/date-time-picker.testpage.component.less
- e2e/pages/app/date-time-picker/date-time-picker.testpage.component.ts
- e2e/tests/components/date-time-picker/date-time-picker.e2e-spec.ts
- e2e/tests/components/date-time-picker/date-time-picker.po.spec.ts
- src/components/date-time-picker/date-time-picker.component.ts
- src/components/date-time-picker/date-time-picker.module.ts
- src/components/date-time-picker/date-time-picker.service.ts
- src/components/date-time-picker/day-view/day-view.component.html
- src/components/date-time-picker/day-view/day-view.service.ts
- src/components/date-time-picker/pipes/weekday-sort.pipe.ts
- Adding support for `startOfWeek` input which allows the user to define which day of the week should be in the first column.
- Added test case to cover this new feature.
https://autjira.microfocus.com/browse/EL-3336
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3336-Date-Start-Of-Week
> EL-3336 - Date Time Picker

- docs/app/pages/components/components-sections/tree-view/tree-view/snippets/app.snippet.html
- docs/app/pages/components/components-sections/tree-view/tree-view/snippets/app.snippet.ts
- docs/app/pages/components/components-sections/tree-view/tree-view/tree-view.component.html
- docs/app/pages/components/components-sections/tree-view/tree-view/tree-view.component.ts
Bug where focus on a tree view node then press tab. The node is no longer focused by left and right arrow keys would still expand/collapse the node.
Updated documentation to fix this example.
https://autjira.microfocus.com/browse/EL-3361
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3361-Tree-Accessibility-Documentation
> EL-3361 - Tree Node Accessibility

- src/components/tabset/tab/tab.component.ts
The Tab Component is causing the error when the active property is set on initialisation. It can be easily be reproduced, eg: https://plnkr.co/edit/NWlz3Z8C2J4LfDXIzHaV?p=preview
Just added the tick operator to the `active$` observable in the tab component.
https://autjira.microfocus.com/browse/EL-3366
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3366-Masthead-Expression-Changed
> EL-3366 - Masthead Expression Changed

- src/ng1/directives/spark/spark.controller.js
- src/ng1/directives/spark/spark.html
If there is a multi-value spark chart and then I change the segment values, the bar isn't updated.
Here's a codepen to reproduce the issue:
https://codepen.io/ashh640/pen/JwZBXq
Essentially all the values in this component were only getting set/calculated when the component was instantiated. I have changed it to now use getters instead so values are calculated on digest in case anything has changed.
https://autjira.microfocus.com/browse/EL-3370
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3370-Sparkline-Not-Updating
> EL-3370 - Spark Chart Not Updating

- docs/app/pages/components/components-sections/scrollbar/virtual-scroll/snippets/app.html
- docs/app/pages/components/components-sections/scrollbar/virtual-scroll/snippets/app.ts
- docs/app/pages/components/components-sections/scrollbar/virtual-scroll/virtual-scroll.component.html
- docs/app/pages/components/components-sections/scrollbar/virtual-scroll/virtual-scroll.component.ts
- docs/app/pages/components/components-sections/utilities/tabbable-list/tabbable-list.component.html
- src/components/virtual-scroll/virtual-scroll.component.html
- src/components/virtual-scroll/virtual-scroll.component.ts
- src/directives/accessibility/tabbable-list/tabbable-list-item.directive.ts
- src/directives/accessibility/tabbable-list/tabbable-list.directive.ts
- src/directives/accessibility/tabbable-list/tabbable-list.service.ts
Virtual Scrolling did not work well with tabbable list. This was for a number of reasons:
- The number of cells in the dom above and below the visible range were sometimes 0 which meant pressing arrow led to no dom node. I have increased the number of DOM cells on each side of the virtual list.
- The ListKeyManager, when the QueryList of TabbableListItem changes tries to see if the previously focused item is still in the list and refocuses it. However, the way the virtual scroll works meant a new tabbable list item instance is created each time a cell is redrawn meaning it never got reselected when the virtual scroll visible range changed. So I have updated this to allow for a `key` input on tabbable list items so we can identify when an item is the same even if it is a different …
> EL-3344 - Virtual Scroll Improvements

- docs/app/pages/components/components-sections/input-controls/number-picker/number-picker.component.html
- src/components/number-picker/number-picker.component.html
- src/components/number-picker/number-picker.component.ts
Adding `id` and `aria-labelledby` bindings to the number input picker. Also updated setters to use the Angular CDK coercion functions rather than rolling our own for each setter.
https://autjira.microfocus.com/browse/EL-3358
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3358-Number-Picker-Id
> EL-3358 - Number Picker Improvements

- src/components/select/select.component.html
- src/components/select/select.component.ts
- src/components/tag-input/tag-input.component.html
- src/components/tag-input/tag-input.component.ts
- src/components/typeahead/typeahead-key.service.ts
Pressing shift+tab when select is focused was not moving to the previous tabbable element.
The issue was we had a focus hostlistener on the `ux-select` element which focused the child input. The purpose of this was if the user clicked here:
This is inside the component but not inside the input, so we programmatically focused the child input for them.
However this meant if we are focused on the input, then shift+tab this now focuses the `ux-select` which triggers the host listener and refocuses the input, preventing us from ever leaving focus that way. I have changed it to a click listener so we get the same behaviour without the error.
Additionally I have updated the component to use generics instead of any for better type inference and changed to use CDK keycodes for key presses. I also …
> EL-3343 - Select Focus Issue Fix

- docs/app/pages/components/components-sections/hierarchy-bar/hierarchy-bar/hierarchy-bar.component.html
- docs/app/pages/components/components-sections/hierarchy-bar/hierarchy-bar/hierarchy-bar.component.ts
- docs/app/pages/components/components-sections/hierarchy-bar/hierarchy-bar/snippets/app.html
- src/components/hierarchy-bar/hierarchy-bar-collapsed/hierarchy-bar-collapsed.component.html
- src/components/hierarchy-bar/hierarchy-bar-standard/hierarchy-bar-standard.component.html
- Making overflow nodes available in the implicit template context so they can be accessed
- Removing the customize example accordion from the example code
https://autjira.microfocus.com/browse/EL-3367
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3367-Hierarchy-Bar-Qa
> EL-3367 - Hierarchy Bar QA Fixes

- src/directives/accessibility/accessibility.module.ts
- src/directives/accessibility/focus-indicator/default-focus-indicator.directive.ts
I'm really not sure how to go about fixing this, essentially there is a check in the CDK to determine if the window has focus or not, (if it does not have focus then it detects any focus event as "programmatic" origin instead of keyboard). For some strange reason Firefox can sometime detect the window as not focused when it is - I can only assume its based on the order event are triggered.
As a workaround I have set it so buttons will show a focus ring when triggered programmatically in Firefox. It will still prevent the focus ring on click, but I suppose there may now be a few cases in Firefox where the focus ring shows up. My thinking was it is better to show a focus ring in a few extra cases than cause accessibility issues by potentially not showing it.
I'm open to any feedback or …
> EL-3322 - Firefox Focus Issue

- src/directives/resize/resize.directive.ts
- Changing the resize directive to use the `_onDestroy` unsubscription method.
https://autjira.microfocus.com/browse/EL-3373
(see the project attached to the jira for repro environment, also CI build is giving out of space errors)
> EL-3373 - Resize Directive Destroy Improvement

- src/directives/selection/selection.directive.ts
Added `debounceTime(0)` to the subscription. This has to be used instead of `tick` as the selection array may change multiple times during the course of the selection/deselection and we only want to emit the final finished result rather than all the intermediate ones (which was actually the source of the expression changed error)
https://autjira.microfocus.com/browse/EL-3385
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3385-Selection-Expression-Changed
> EL-3385 - Selection Expression Has Changed Error

- docs/app/pages/components/components-sections/tables/column-resizing/column-resizing.component.html
- e2e/pages/app/app.module.ts
- e2e/pages/app/column-resizing/column-resizing.module.ts
- e2e/pages/app/column-resizing/column-resizing.testpage.component.html
- e2e/pages/app/column-resizing/column-resizing.testpage.component.ts
- e2e/tests/components/column-resizing/column-resizing.e2e-spec.ts
- e2e/tests/components/column-resizing/column-resizing.po.spec.ts
- src/components/table/table-column-resize/resizable-table.directive.ts
- Adding function to force the layout to update. Also placed this in a requestAnimationFrame to allow any UI updates to happen before updating the layout.
Plunker Showing Original Issue:
https://plnkr.co/edit/uXj3rnZOk75WgOYiz9Go?p=preview
Plunker Showing Fixed Issue
https://plnkr.co/edit/BvZVK1awy2U104Rdtfc5?p=preview
https://autjira.microfocus.com/browse/EL-3377
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3377-Column-Resizing
> EL-3377 - Column Resize Update Layout

- docs/app/pages/components/components-sections/search/toolbar-search/toolbar-search.component.html
- e2e/pages/app/toolbar-search/toolbar-search.module.ts
- e2e/pages/app/toolbar-search/toolbar-search.testpage.component.html
- e2e/pages/app/toolbar-search/toolbar-search.testpage.component.ts
- e2e/tests/components/toolbar-search/toolbar-search.e2e-spec.ts
- e2e/tests/components/toolbar-search/toolbar-search.po.spec.ts
- src/components/toolbar-search/toolbar-search-button.directive.ts
- src/components/toolbar-search/toolbar-search-field.directive.ts
- src/components/toolbar-search/toolbar-search.component.ts
Related PR: https://github.houston.softwaregrp.net/caf/ux-aspects-micro-focus/pull/338
- Added `alwaysExpanded` option to make sure the input never closes
- Updated documentation to include the new property
- The placeholder element was being created using `document.createElement`, now switched to use renderer and correctly dispose of the element. Also added a safety check so we don't try to use `getComputedStyle` in a Server Side Rendered environment.
- Changed toolbar search component to use `OnPush` change detection
- There were quite a few subscriptions that were never disposed of so I have added in the teardown code
- We supported ngModel however we did not support ReactiveForms so I have changed this to use the `ControlValueAccessor` allowing us to target both
- Added new tests to …
> EL-3378 - Toolbar Search - Always Expanded

- docs/app/pages/components/components-sections/notifications/notifications/notifications.component.less
- docs/app/pages/components/components-sections/notifications/notifications/snippets/app.css
Increasing the right margin of the Keppel notification example by 3px as per Rolands request
https://autjira.microfocus.com/browse/EL-3376
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3376-Notification-Padding
> EL-3376 - Notification Padding

- docs/app/pages/components/components-sections/notifications/notifications/notifications.component.less
- docs/app/pages/components/components-sections/notifications/notifications/snippets/app.css
- Fixing IE Flex issue (needed to specify an exact width or content doesn't wrap onto new line)
- I previously increased the margin-right, however this didn't actually visually increase the spacing due to where the line breaks, I have updated the example to increase the spacing to make it visually as Roland wanted it.
https://autjira.microfocus.com/browse/EL-3376
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3376-Dynamic-Height-Fix-2
> EL-3376 - Notifications IE Fix

- src/components/toolbar-search/toolbar-search.component.ts
According to the Angular API docs the destroyNode function can sometimes be null or undefined, so I have added checks to only call the function if it is available.
https://autjira.microfocus.com/browse/EL-3378
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3378-Toolbar-Search-Fix
> EL-3378 - Toolbar Search Fix

- docs/app/pages/components/components-sections/date-time-picker/date-time-picker/date-time-picker.component.html
- docs/app/pages/components/components-sections/date-time-picker/date-time-picker/snippets/app.html
- docs/app/pages/components/components-sections/utilities/focus-indicator/focus-indicator.component.html
- docs/app/pages/components/components-sections/utilities/focus-indicator/snippets/component-config.ts
- docs/app/pages/components/components-sections/utilities/focus-indicator/snippets/local-options.html
- src/components/date-time-picker/month-view/month-view.component.html
- src/components/date-time-picker/year-view/year-view.component.html
- src/components/floating-action-buttons/floating-action-button.component.html
- src/components/floating-action-buttons/floating-action-button.component.ts
- src/components/hierarchy-bar/hierarchy-bar-collapsed/hierarchy-bar-collapsed.component.html
- src/components/hierarchy-bar/hierarchy-bar-popover-item/hierarchy-bar-popover-item.component.html
- src/directives/accessibility/accessibility.module.ts
- src/directives/accessibility/focus-indicator/default-focus-indicator.directive.ts
- src/directives/accessibility/focus-indicator/focus-indicator-options/focus-indicator-options.directive.ts
- src/directives/accessibility/focus-indicator/focus-indicator-options/focus-indicator-options.ts
- src/directives/accessibility/focus-indicator/focus-indicator-origin/focus-indicator-origin.directive.ts
- src/directives/accessibility/focus-indicator/focus-indicator-origin/focus-indicator-origin.service.ts
- src/directives/accessibility/focus-indicator/focus-indicator.directive.ts
- src/directives/accessibility/focus-indicator/focus-indicator.service.ts
- src/directives/accessibility/focus-indicator/focus-indicator.ts
Related PR: https://github.houston.softwaregrp.net/caf/ux-aspects-micro-focus/pull/354
- Fixing Hierarchy Bar focus ring showing in collapsed mode
- Adding `uxFocusIndicatorOptions` directive (instead of the previous inject the ACCESSIBILITY_OPTIONS_TOKEN). You can now just add this directive to any element and you can override all the options that are available to the uxFocusIndicator (note `checkChildren` is not an option as this is something that the component itself would need to decide). This gives us much more fine grained control than with the injection token.
Your date picker plunker showing the issue can be updated like this:
```html
<ux-date-time-picker
uxFocusIndicatorOptions
[mouseFocusIndicator]="true"
[(date)]="date"
[(timezone)]="timezone"
[showTime]="showTime" …
```
> EL-3406 - Focus Indicator Rework QA Fixes

- docs/app/pages/components/components-sections/wizard/marquee-wizard/marquee-wizard.component.html
- docs/app/pages/components/components-sections/wizard/marquee-wizard/snippets/app.html
- docs/app/pages/components/components-sections/wizard/wizard.module.ts
- src/components/color-picker/color-picker.component.html
- src/components/color-picker/color-picker.component.less
- src/components/color-picker/color-picker.component.ts
- src/components/facets/base/facet-header/facet-header.component.ts
- src/components/pagination/pagination.component.html
- src/components/table/table-column-resize/resizable-table-column.component.html
- src/components/table/table.module.ts
- src/components/wizard/wizard-step.component.ts
- src/components/wizard/wizard.component.html
- src/components/wizard/wizard.component.ts
- src/directives/accessibility/accessibility.module.ts
- src/directives/accessibility/contrast-ratio/color-contrast.directive.ts
- src/directives/accessibility/contrast-ratio/contrast.service.ts
- src/directives/accessibility/index.ts
Related PR: https://github.houston.softwaregrp.net/caf/ux-aspects-micro-focus/pull/355 & https://github.houston.softwaregrp.net/caf/quantum/pull/625
- Created a `ContrastService` that can be used to get the best contrasting colours. I found the WCAG AA Contrast Ratio algorithm in the spec and have implemented it so the contrast will be accurate according to the spec.
- Also created a `uxColorContrast` directive to set the color based on the background color automatically.
- Improved facet header focus behavior
- Improved pagination focus behavior (previous using CDK focus directives, now using `uxFocusIndicator` for consistency)
- Wizard now using focus-indicator. Also found a bug where the first wizard step was not initially tabbable, as we were basing the tab index of whether or not the …
> EL-3404 - Focus Visual Rework

- e2e/pages/app/selection/selection.testpage.component.html
- e2e/tests/components/selection/selection.e2e-spec.ts
- e2e/tests/components/selection/selection.po.spec.ts
I don't think there are tests for hover actions and tabbable list yet.
https://autjira.microfocus.com/browse/EL-3342
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3342-table-navigation-e2e
> Added uxSelection test for the ManagedFocusContainer functionality

- src/components/tooltip/tooltip.directive.ts
Fixing timeout logic in tooltip to ensure that it is correctly cleared when we "hide" a tooltip before it has been shown.
https://autjira.microfocus.com/browse/EL-3429
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3429-Tooltip-Cancel-Delay
> EL3429 - Tooltip Cancel Delay

- src/components/tooltip/tooltip.directive.ts
Fixing issue where clicking did not cancel the tooltip
https://autjira.microfocus.com/browse/EL-3429
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3429-Tooltip-Delay-2
> EL-3429 - Tooltip Delay - Click Fix

- docs/app/data/charts-page.json
- docs/app/pages/charts/charts-sections/timeline-chart/timeline-chart.module.ts
- docs/app/pages/charts/charts-sections/timeline-chart/timeline-chart/snippets/app.ts
- docs/app/pages/charts/charts-sections/timeline-chart/timeline-chart/timeline-chart.component.html
- docs/app/pages/charts/charts-sections/timeline-chart/timeline-chart/timeline-chart.component.ts
- src/plugins/chartjs/timeline/timeline-chart.interface.ts
- src/plugins/chartjs/timeline/timeline-chart.module.ts
- src/plugins/chartjs/timeline/timeline-chart.ts
- src/plugins/index.ts
I remember getting this issue before when we added the tick operator (which we removed the public export to fix). There seems to be an issue sometimes when directly exporting a file that doesn't contain and Angular component/service/pipe etc.. To fix this I have introduced a `TimelineChartModule` ngModule which registers the plugin for them. This way we can avoid directly exporting the file, and it also is probably easier for the consumer than before as this is the way we include all other components.
I haven't been able to test whether or not this fixes the build issue as I am not able to reproduce the issue on my machine.
https://autjira.microfocus.com/browse/EL-3430
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3430-Timeline-Chart-2
> EL-3430 - Timeline Chart Build Issue

- src/components/dashboard/dashboard.component.ts
- src/components/dashboard/widget/dashboard-widget.component.less
- src/components/dashboard/widget/dashboard-widget.component.ts
Updating dashboard so animations are disabled when resizing a dashboard widget fixing the weird movements on resize.
https://autjira.microfocus.com/browse/EL-3449
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3449-Dashboard-Resizing-Issue
> EL-3449 - Dashboard Resizing Issue

- src/styles/buttons.less
- src/styles/controls.less
- Changing secondary button border colour when used as an input addon to match the textbox border color
https://autjira.microfocus.com/browse/EL-2869
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-2869-Addon-Styles
> EL-2869 - Input Addon Styles

- src/components/table/table-column-resize/resizable-table-column.component.ts
Fixing issue with column resizing reset functionality. Essentially the max-width property was not getting initially set on disabled columns allowing them to grow to large, potentially offsetting subsequent columns
https://autjira.microfocus.com/browse/EL-3469
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3469-Column-Resizing-Fix
> EL-3469 - Column Resizing Issue

- docs/app/pages/components/components-sections/input-controls/number-picker/number-picker.component.html
- e2e/pages/app/number-picker/number-picker.testpage.component.html
- e2e/tests/components/number-picker/number-picker.e2e-spec.ts
- e2e/tests/components/number-picker/number-picker.po.spec.ts
- src/components/number-picker/number-picker.component.ts
- Ensuring that we limit number picker precision otherwise incrementing/decrementing in steps of 0.1 can result in strange numbers like `0.30000000000000004` due to Javascripts weird handling of floating point numbers. Eg: https://plnkr.co/edit/kPyFlZ7PL8XasCRq6Sjk?p=preview
- Updated tests to use async/await and changed to cover this precision issue
https://autjira.microfocus.com/browse/EL-3462
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3463-Number-Picker-Precision
> EL-3463-Number-Picker-Precision

- src/directives/accessibility/focus-indicator/focus-indicator.ts
The `FocusOptions` interface that is part of the standard `lib.d.ts` is not present in older versions of TypeScript that were used in Angular CLI v5 & v6 causing a compiler error. I have updated the code to avoid using the interface.
N/A
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_Fixing-Build-Focus-Options
> Fixing Build - Focus Option Interface

- src/components/table/table-column-resize/resizable-table.directive.ts
Issue was that column resizing does not work within a modal.
The issue was caused because the contents of a modal are initialized before they are visible on the screen. This caused the table width to be `0` and all columns widths to be `0`. We do percentage calculations so `column width`/`table width` -> `0/0` = `NaN` causing some problems.
I have changed this to now delay initialization of the column resizing until the table has a width greater than 0.
Here is a plunker with referencing the library with the fix:
https://next.plnkr.co/edit/Hm3F6BK5Ncw69X0H
https://autjira.microfocus.com/browse/EL-3460
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3460-Column-Resizing-Modal
> EL-3460 - Column Resizing in a Modal

- src/directives/fixed-header-table/fixed-header-table.directive.ts
- src/directives/fixed-header-table/fixed-header-table.module.ts
Turns out the fixed header table directive had the same issue as column resizing, it sets the layout when the modal appears but it obviously has no width. Changed it to automatically update the layout when the modal resizes (or appears for the first time)
https://autjira.microfocus.com/browse/EL-3460
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3460-Column-Resizing-QA
> EL-3460 - Column Resizing QA

- src/components/select/select.component.less
- src/components/select/select.component.ts
- src/components/select/select.module.ts
- src/components/tag-input/tag-input.component.less
Fixing styling issues in Firefox and IE. the `:read-only` selector only works in Chrome, switched to `[readonly]` instead.
https://autjira.microfocus.com/browse/EL-3458
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3458-Select-Enhancement-QA
> EL-3548 - Select Enhancements QA

- docs/app/pages/components/components-sections/hierarchy-bar/hierarchy-bar/hierarchy-bar.component.html
- e2e/pages/app/hierarchy-bar/hierarchy-bar.module.ts
- e2e/pages/app/hierarchy-bar/hierarchy-bar.testpage.component.html
- e2e/pages/app/hierarchy-bar/hierarchy-bar.testpage.component.ts
- e2e/tests/components/hierarchy-bar/hierarchy-bar.e2e-spec.ts
- e2e/tests/components/hierarchy-bar/hierarchy-bar.po.spec.ts
- src/components/hierarchy-bar/hierarchy-bar-collapsed/hierarchy-bar-collapsed.component.html
- src/components/hierarchy-bar/hierarchy-bar-standard/hierarchy-bar-standard.component.html
- src/components/hierarchy-bar/hierarchy-bar.component.html
- Added option to have a custom element trailing the last visible node.
An example of this can be seen here:
https://plnkr.co/edit/DjlEIMF5BjKmBylOY8Ov?p=preview
https://autjira.microfocus.com/browse/EL-3456
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3456-Hierarchy-Bar-Inline-Addon
> EL-3456 - Hierarchy Bar Inline

- src/components/select/select.component.less
- src/components/select/select.component.ts
- Fixing styling issue when both readonly and disabled
- Also fixed an issue where clicking on the chevron would show the dropdown even when disabled
https://portal.digitalsafe.net/browse/EL-3458
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3458-Select-Readonly-QA2
> EL-3458 - Select Readonly Input

- docs/app/pages/components/components-sections/buttons/dropdowns/dropdowns.component.less
- docs/app/pages/components/components-sections/buttons/dropdowns/snippets/app.css
- src/styles/buttons.less
Moving `.dropdown-open` class to our global stylesheet, addressing the comment here: https://github.houston.softwaregrp.net/caf/ux-aspects-micro-focus/pull/390#discussion_r146273
https://portal.digitalsafe.net/browse/EL-3426
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3426-Button-Dropdown-2
> EL-3426 - Button Dropdown

- e2e/tests/components/tabbable-list/tabbable-list.e2e-spec.ts
- src/directives/accessibility/tabbable-list/tabbable-list-item.directive.ts
- src/directives/accessibility/tabbable-list/tabbable-list.service.ts
I have just discovered a bug in the tabbable list that I would like to get fixed before release. 
It is hard to reproduce, but i can get it to happen consistently when hiding a wizard step. Essentially, previously any time the tab indexes in a tabbable list changed we updated the tabindex attributes by running change detection, which seems to cause an issue in this case as change detection was already running. Switching to setting the tabindex using the renderer instead of relying on CD seems to resolve this issue.
https://plnkr.co/edit/uit7Wgd4wTdUDXdjLwGs?p=preview
https://portal.digitalsafe.net/browse/EL-3479
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_Tabbable-List-Issue-Fix
> Tabbable List Fix

- src/styles/buttons.less
Making selector more specific as the default quantum style for `.dropdown-menu` where overriding it.
https://portal.digitalsafe.net/browse/EL-3426
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3426-Button-Dropdown-Fix
> EL-3426 - Button Dropdown Fix

- src/components/marquee-wizard/marquee-wizard.component.less
- src/ng1/directives/marqueeWizard/marqueeWizard.html
- src/styles/wizard.less
Scrollbars should now appear when wizard steps overflow in marquee wizards
https://portal.digitalsafe.net/browse/EL-3475
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3475-Marquee-Wizard-Overflow
> EL-3475 - Marquee Wizard Overflow

- e2e/pages/app/wizard/wizard.module.ts
- e2e/pages/app/wizard/wizard.testpage.component.html
- e2e/pages/app/wizard/wizard.testpage.component.ts
- e2e/tests/components/wizard/wizard.e2e-spec.ts
- e2e/tests/components/wizard/wizard.po.spec.ts
- src/components/wizard/wizard.component.ts
* Added `tick` operator to the steps change handler, to allow the view to update.
* Also added an `update` call to keep the step index accurate.
* Added a test case for adding and removing a final step.
* Consolidated a number of wizard tests into one test case for efficiency.
https://portal.digitalsafe.net/browse/EL-3467
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3467-wizard-step-modifications
> EL-3467 - Wizard - step modifications not updating UI

- docs/app/pages/components/components-sections/tables/multiple-column-sorting-ng1/multiple-column-sorting-ng1.component.html
- docs/app/pages/components/components-sections/tables/single-column-sorting-ng1/single-column-sorting-ng1.component.html
- src/ng1/directives/sorters/multiSortableHeader/multiSortableHeader.controller.js
- src/ng1/directives/sorters/multiSortableHeader/multiSortableHeader.html
- src/ng1/directives/sorters/sorterHeader/sortableHeader.controller.js
- src/ng1/directives/sorters/sorterHeader/sortableHeader.html
- src/styles/tables.less
- Adding option to inline the icon so it appears immediately after the text rather than right aligned
https://portal.digitalsafe.net/browse/EL-3466
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3466-Inline-Sort-Icon
> EL-3466 - Sortable Header Icon Alignment

- src/components/number-picker/number-picker.component.less
- src/components/number-picker/number-picker.component.ts
Since the "compact" variant of the number picker will be the most used style, I'm adding a new selector for it. This should aid with code completion instead of having to remember the class name when implementing the number picker.
https://portal.digitalsafe.net/browse/EL-3470
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3470-number-picker
> EL-3470 - Number Picker - "underline" style for the compact variant

- docs/app/pages/charts/charts-sections/partition-map/partition-map/partition-map.component.html
- docs/app/pages/charts/charts-sections/partition-map/partition-map/partition-map.component.less
- docs/app/pages/charts/charts-sections/partition-map/partition-map/snippets/app.css
- docs/app/pages/charts/charts-sections/partition-map/partition-map/snippets/app.html
- src/components/partition-map/partition-map.component.less
- src/components/partition-map/partition-map.component.ts
As discussed yesterday during storytime, I have updated the partition map to use pixel values for the collapsed height rather than a percentage.
https://portal.digitalsafe.net/browse/EL-3117
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3117-Partition-Map-Collapse-Height
> EL-3117 - Partition Map Collapse Height

- e2e/pages/app/column-picker/column-picker.testpage.component.html
- e2e/pages/app/column-picker/column-picker.testpage.component.ts
- e2e/tests/components/column-picker/column-picker.e2e-spec.ts
- e2e/tests/components/column-picker/column-picker.po.spec.ts
- src/components/table/column-picker/column-picker.component.html
- Fixing issue (was just an ngIf needed the condition inverted)
- Adding test to cover this
https://portal.digitalsafe.net/browse/EL-3484
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3484-Column-Picker-Title-Template
> EL-3484 - Column Picker Title Template

- src/ng1/directives/treegrid/accessibility/treegrid-navigation-item.controller.js
- src/ng1/directives/treegrid/treegrid.controller.js
- src/ng1/directives/treegrid/treegrid.html
- src/ng1/directives/treegrid/treegrid.spec.js
- Showing indicator whenever keyboard is used to expand/contract nodes
https://portal.digitalsafe.net/browse/EL-3496
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3496-Tree-Grid-Fix
> EL-3496 - Tree Grid Keyboard Fix

- src/ng1/directives/dynamicSelect/dynamicSelect.controller.js
- src/ng1/directives/infiniteScroll/infiniteScroll.controller.js
- src/ng1/directives/infiniteScroll/infiniteScroll.directive.js
- src/styles/input-controls.less
- Changed the select component to update the height of the dropdown when the items change
- Added a event to the infinite-scroll directive as the loading indicator is hidden using ng-show/ng-hide so watching for element changes doesn't detect this, so the event emits when the loading state changes and we can update the height of the dropdown.
https://portal.digitalsafe.net/browse/EL-3500
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3500-Select-Scrollbar
> EL-3500 - AngularJS select dynamic height

- docs/app/pages/charts/charts-sections/organization-chart/organization-chart.module.ts
- docs/app/pages/charts/charts-sections/organization-chart/organization-chart/organization-chart.component.html
- docs/app/pages/charts/charts-sections/organization-chart/organization-chart/snippets/app.html
- src/components/hierarchy-bar/hierarchy-bar-node/hierarchy-bar-node.component.html
Fixing the issues mentioned by Roland:
- Items with no children should not show the icon and child count or up arrow on hover
- Fixed issue in hierarchy bar where focus indicator doesnt show on first menu item when it is triggered by the keyboard
(note there was another issue mentioned in the ticket about showing the hover state when an item is focused, this was completed as part of the original PR so no changes are required for it)
https://portal.digitalsafe.net/browse/EL-3116
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3116-Organization-Chart-QA
> EL-3116 - Organization Chart Improvements

- docs/app/pages/components/components-sections/panels/item-display-panel/item-display-panel.component.html
- docs/app/pages/components/components-sections/panels/side-panel/side-panel.component.html
- e2e/pages/app/item-display-panel/item-display-panel.testpage.component.ts
- e2e/pages/app/side-panel/side-panel.testpage.component.html
- src/components/item-display-panel/item-display-panel.component.html
- src/components/item-display-panel/item-display-panel.component.ts
- src/components/side-panel/side-panel-animations.ts
- src/components/side-panel/side-panel.component.html
- src/components/side-panel/side-panel.component.less
- src/components/side-panel/side-panel.component.ts
* Using Angular animations in order to set `visibility` with the proper timing. `visibility: hidden` prevents focus landing on panel content when it is closed.
* Converted the duration and timing function to match quantum.
https://portal.digitalsafe.net/browse/EL-3468
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3468-side-panel
> EL-3468 - Side Panel focus

- src/ng1/directives/dynamicSelect/dynamicSelect.controller.js
Removing the use of `array.findIndex` as this is not available in IE without a polyfill. Replacing with ES5 equivalent code.
https://portal.digitalsafe.net/browse/EL-3500
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3500-Select-QA
> EL-3500 - Select IE issue

- docs/app/pages/charts/charts-sections/organization-chart/organization-chart/organization-chart.component.html
- src/components/organization-chart/organization-chart.component.ts
- Fixing selection using the input issue. Initial selection is now deferred until the initial render has started.
- Added a `verticalSpacing` option to allow the user to customize the amount of space between parent and child nodes.
https://portal.digitalsafe.net/browse/EL-3116
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3116-Organization-Chart-Fixes
> EL-3116 - Organization Chart Bug Fixes

- e2e/pages/app/app.module.ts
- e2e/pages/app/navigation/navigation.module.ts
- e2e/pages/app/navigation/navigation.testpage.component.html
- e2e/pages/app/navigation/navigation.testpage.component.ts
- e2e/pages/app/navigation/page.component.ts
- e2e/tests/components/navigation/navigation.e2e-spec.ts
- e2e/tests/components/navigation/navigation.po.spec.ts
- src/components/navigation/index.ts
- src/components/navigation/navigation-item.inferface.ts
- src/components/navigation/navigation-item/navigation-item.component.html
- src/components/navigation/navigation-item/navigation-item.component.ts
- src/components/navigation/navigation-link/navigation-link.directive.ts
- src/components/navigation/navigation-options.ts
- src/components/navigation/navigation.component.html
- src/components/navigation/navigation.component.ts
- src/components/navigation/navigation.module.ts
- src/components/navigation/navigation.service.ts
**NavigationItem Interface**
- Added new `routerOptions` property to the interface to contain all router related configuration as we may want to add more options over time. I did not want to use the existing `routerExtras` property as this maps directly to the Angular `routerExtras` properties used by `routerLink`. It also allows use to share the interface with the global config as mentioned below.
- Added option to specify the `exact` property (defaults to true to retain existing functionality)
- Added option to `ignoreQueryParams` (defaults to false to retain existing functionality)
**Navigation Module**
- Added a `forRoot` option to the module. This will allow the `exact` and `ignoreQueryParams` (and any others that we may add in future) to be specified on a global level rather than …
> EL-3269 - Side Menu Route Options

- src/directives/drag/drag.directive.ts
- src/directives/drag/drag.service.ts
- src/directives/drag/drop.directive.ts
- Updated the drag directives and service to use a generic rather than `any` to provide better type inference.
- Moved the `takeUntil` operators to the end of the `pipe` (after watching ng-conf yesterday it this was mentioned that this way of unsubscribing should come at the end to prevent certain edge cases where order is important)
- Updated the `dragEnd` `filter` operator to check if the model is the same instead of solely relying on `_isDragging`. This is because in the calendar when calendar items are rendered using an `ngFor` it can create a new instance of the directive so `isDragging` may be false simply because a new instance was created. The model is persisted across instances so we can alternatively compare against that.
- The `dragEnd` event is now a separate subscription. …
> EL-3513 - Calendar Drag Enhancement

- src/ng1/directives/marqueeWizard/marqueeWizard.controller.js
The `onChanging` function was always being passed the immediate next index or immediate previous index, eg, if we are on step 3 and I hit previous the `onChanging` function would receive the current index (3) and the target index (2) even if step two was hidden and we actually would have ended up on step 1.
I have now updated the function to pass the correct indexes to the `onChanging` function, so if we are on step 3 and hit previous, if step 2 is hidden it will pass `1` to the function as the target index.
This issue covers the two Marquee Wizard tickets in this sprint. One relates to the `onChanging` function receiving the wrong indexes, the other relates to the contents of step 2 being shown when I hit previous on step 3 if step 2 is hidden. Again, this is caused because we were …
> EL-3507 - Marquee Wizard Previous Issue

- docs/app/pages/components/components-sections/date-time-picker/date-range-picker/date-range-picker.component.html
- docs/app/pages/components/components-sections/date-time-picker/date-range-picker/date-range-picker.component.less
- docs/app/pages/components/components-sections/date-time-picker/date-range-picker/snippets/app.css
- docs/app/pages/components/components-sections/date-time-picker/date-range-picker/snippets/app.html
- e2e/pages/app/date-range-picker/date-range-picker.testpage.component.html
- e2e/pages/app/date-range-picker/date-range-picker.testpage.component.ts
- e2e/tests/components/date-range-picker/date-range-picker.e2e-spec.ts
- e2e/tests/components/date-range-picker/date-range-picker.po.spec.ts
- src/components/date-range-picker/date-range-picker.component.less
- src/components/date-time-picker/day-view/day-view.component.ts
- src/directives/accessibility/focus-indicator/default-focus-indicator.directive.ts
- src/directives/accessibility/focus-indicator/focus-indicator.directive.ts
**Date Range Picker**
- Added new selection behaviour where the the range end will only change the displayed month on selection if it is before the start date and vice versa.
- Fixing alignment of the duration arrow and label
- Removing popover bottom padding when show now button is visible to match Rolands updated designs
**Protractor Tests**
- Fixing tests, they were failing locally due to timezones not being accounted for. The tests have now all been updated to take into account the local timezone
- Added new tests to cover the new selection behaviour
**Focus Indicator**
- I also found our date picker component has gotten very slow, after some performance profiling it turns out it was due to the `FocusIndicator`. When instantiated the `FocusIndicator` initially emits its focused state. …
> EL-3454 - Date Range Picker Fixes

- src/directives/drag/drop.directive.ts
- Previously the stored `group` was set in the `onDragStart` function, however this function is only called if the `isDropAllowed` function returns true. So if an item is dragged (that drop is allowed) it will set the group, then the next time we drag an item (that is not allowed) the stored group still contains the previous group name.
- Changed to now always update the stored group as soon as dragging starts 
https://portal.digitalsafe.net/browse/EL-3513
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3513-Calendar-Drag-Fix
> EL-3413 - Calendar Drag Fix

- src/components/organization-chart/organization-chart.component.ts
- src/components/typeahead/typeahead-event.ts
- src/components/typeahead/typeahead.component.ts
Identified a few areas where performance can be improved:
**Organization Chart**
- Camera movement was running inside NgZone causing change detection when panning which was unnecessary
**Typeahead**
- Component was using `Default` Change Detection which is quite expensive especially when each item in the typeahead `key` and `display` properties are retrieved from function calls.
- Also added generic for typeahead events and replacing `any` with the correct type for template contexts for better type inference.
https://portal.digitalsafe.net/browse/EL-3503
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3503-Organization-Chart-Showcase
> EL-3503 - Organization Chart Showcase

- docs/app/pages/charts/charts-sections/partition-map/partition-map/partition-map.component.html
- docs/app/pages/charts/charts-sections/partition-map/partition-map/snippets/app.html
- src/components/partition-map/partition-map.component.html
- src/components/partition-map/partition-map.component.less
- src/components/partition-map/partition-map.component.ts
- Fixing a typo in a class name
- Added `expanded` option to the context to know the expanded state of a segment
- Added `children` option to the context so we can access the color and expanded state of child items
https://portal.digitalsafe.net/browse/EL-3482
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3482-Partition-Map-Showcase
> EL-3482 - Partition Map Showcase

- docs/app/pages/charts/charts-sections/partition-map/partition-map/partition-map.component.html
- src/components/partition-map/events/partition-map-segment-events.directive.ts
- src/components/partition-map/index.ts
- src/components/partition-map/partition-map.module.ts
https://portal.digitalsafe.net/browse/EL-3482
Added a directive that allows a custom partition map segment template to trigger events on `segmentFocus` and `segmentBlur`.
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3482-Partition-Map-Segment-Events
> EL-3482 - Partition Map Segment Events

- e2e/tests/components/select/standard/select.e2e-spec.ts
- src/components/select/select.component.ts
- src/components/typeahead/typeahead.component.html
- src/components/typeahead/typeahead.component.ts
https://portal.digitalsafe.net/browse/EL-3519
* `hasBeenOpened` added to the typeahead component to track when it has been opened for the first time. Infinite scroll is disabled until this becomes true. This resolves the reported issue as well as the current behavior in the documentation where all the pages start loading as soon as paging is enabled.
* Moved `takeUntil` to the end of the `pipe` functions.
* Removed some irrelevant tests (testing functionality of code that only exists on the test page).
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3519-select-load
> EL-3519 - Select - duplicate page load attempts

- src/components/sankey-chart/sankey-chart.component.ts
- Angular 5 build was failing due to use of `formatNumber` from `@angular/common` as this was only added in v6 or above. Changed to use the built in browser `Number.toLocaleString` which provides the same functionality
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_Sankey-Angular-5
> Sankey Chart - Angular 5 Support

- src/components/date-range-picker/date-range-picker.component.ts
- src/components/date-range-picker/date-range.service.ts
- src/components/date-time-picker/date-time-picker.utils.ts
- src/components/date-time-picker/time-view/time-view.component.ts
https://portal.digitalsafe.net/browse/EL-3540
- Previously that date range duration always calculate the range based on 00:00 on the start date and 23:59 on the end date. I have updated this to now take into account the time provided by the time picker, so if the time was set to 7pm on both start and end time pickers the duration would be 2 days rather than 3 days
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3540-Date-Range-Picker-Duration
> EL-3540 - Date Range Picker Time

- src/components/table/table-column-resize/resizable-table-cell.directive.ts
- src/components/table/table-column-resize/resizable-table-column.component.ts
- src/components/table/table-column-resize/resizable-table.directive.ts
- src/components/table/table-column-resize/resizable-table.service.ts
https://portal.digitalsafe.net/browse/EL-3528
- Updated the `width` input to only mark a column as fixed if a value was actually provided, previously if columns were added with an `ngFor` and only some had a width specified, the `width` setter was getting called with `undefined` and being marked as a fixed width column.
- Hiding horizontal overflow while dragging. To prevent jankiness when dragging we have to specify the column widths as pixels, however pixels are not as precise as percentages so when converting between the two there is a chance that overflow may occur based on the conversion, so hiding horizontal overflow while dragging.
- Also fixed a bug where when dragging ends the column widths were not getting set back to percentages as they should have. …
> EL-3528 - Column Resizing Fix

- docs/app/pages/css/css-sections/icons/basic-usage/basic-usage.component.html
- docs/app/pages/css/css-sections/icons/basic-usage/snippets/sample.html
- docs/app/pages/css/css-sections/icons/fixed-width/fixed-width.component.html
- docs/app/pages/css/css-sections/icons/icon-buttons/icon-buttons.component.html
- docs/app/pages/css/css-sections/icons/icon-buttons/snippets/sample.html
- docs/app/pages/css/css-sections/icons/icon-colors/icon-colors.component.html
- docs/app/pages/css/css-sections/icons/icon-colors/snippets/sample.html
- docs/app/pages/css/css-sections/icons/icon-size/icon-size.component.html
- docs/app/pages/css/css-sections/icons/icon-size/snippets/sample.html
- docs/app/pages/css/css-sections/icons/rotate-flip-icons/rotate-flip-icons.component.html
- docs/app/pages/css/css-sections/icons/rotate-flip-icons/snippets/sample.html
https://portal.digitalsafe.net/browse/EL-3512
- Updating icon sections to use `ux` icons and modifier classes instead of `hpe`. Note, the fixed width section I have kept using the `hpe` icons as this is not relevant to the new iconset due to them being a consistent size already.
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3512-Iconset-Fixes
> EL-3512 - Iconset Fixes

- .gitignore
- package.json
- pom.xml
Release candidate build failed, see: https://jenkins.swinfra.net/job/SEPG/job/UXAspects/view/Builds/job/UXAspects~UXAspects~master-2.0/15/console
RE_BUILD_TYPE env variable was not being passed through, so the RC package was not being created. Also, the package:release stage is no longer needed.
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_release-build-fix
> Fix the release candidate build

- src/ng1/directives/listHoverActions/listHoverAction/listHoverAction.controller.js
https://portal.digitalsafe.net/browse/EL-3581
The listHoverActions directive had `bindToController` set to `true`, so the click function was being added directly to the controller, however we were previously trying to call it on the `$scope` object. Updated the function to point to the controller instead.
Here is a plunker that should show the clicks in action:
https://plnkr.co/edit/fF6w0Kys58Z6cSH2Lb0l?p=preview
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3581-List-Hover-Action-Fix
> EL-3581 - List Hover Action Fix

- docs/app/pages/components/components-sections/tables/selection/selection.component.html
- e2e/pages/app/selection/selection.testpage.component.html
- e2e/pages/app/selection/selection.testpage.component.ts
- e2e/tests/components/selection/selection.e2e-spec.ts
- e2e/tests/components/selection/selection.po.spec.ts
- src/components/checkbox/checkbox.component.ts
- src/directives/selection/selection-item.directive.ts
- src/directives/selection/selection.service.ts
https://portal.digitalsafe.net/browse/EL-3557
- In the plunker that was provided in the ticket they were using the `selected` input to essentially disabled certain items (https://plnkr.co/edit/ylfe6rin0pngNDMEMZAA?p=preview), which was not really what it was designed for. The reason this method did not work, is because on a disabled item, they were setting the `[selected]` value to `false`. Then the user clicks on the item and the directive marks the item as selected, however they are still saying the value for the `[selected]` input is `false`, or in other words, the value has not changed, so Angular does not re-evaluated the input so the selected state does not change.
- I have introduced a new `[uxSelectionDisabled]` option which can be applied to each item in the list. Previously we …
> EL-3557 - Selection Item Disabled fix

- docs/app/pages/components/components-sections/input-controls/tags/snippets/app.css
- docs/app/pages/components/components-sections/input-controls/tags/snippets/app.html
- docs/app/pages/components/components-sections/input-controls/tags/snippets/app.ts
- docs/app/pages/components/components-sections/input-controls/tags/tags.component.html
- docs/app/pages/components/components-sections/input-controls/tags/tags.component.less
- docs/app/pages/components/components-sections/input-controls/tags/tags.component.ts
https://portal.digitalsafe.net/browse/EL-3575
- Adding in ability to add/remove tag icon in 'customize example' dropdown
- Changed icon types from hpe to ux 
- Added in styling so tag was 8px horizontally padded
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3575-tag-input
> Adding ability to add/remove tag icon in customize example section

- src/components/date-time-picker/date-time-picker.service.ts
https://portal.digitalsafe.net/browse/EL-3587
- Selecting the today button if a selection has already been made now updates the date picker to the current day/month.
- Ran the date picker tests and date picker is working as expected.
- <code>pipe(distinctUntilChanged(dateComparator)).</code> was removed from the <code>selected$</code> subscription as if the two date values where the same then true was being return and changing the viewports was never being hit.
- <code>dateComparator(date, this.date$.value))</code> now moved to inside the <code>selected$</code> subscription and the date is only being emitted if the dates are different.
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3587-date-range-picker
> EL-3587-date-range-picker

- docs/app/pages/components/components-sections/input-controls/tags/snippets/app.html
- docs/app/pages/components/components-sections/input-controls/tags/snippets/tag-template.html
- docs/app/pages/components/components-sections/input-controls/tags/tags.component.html
https://portal.digitalsafe.net/browse/EL-3575
* As discussed with Roland (see ticket), removed the custom template from the example and added an inline code snippet.
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3575-remove-custom-icons
> EL-3575 - Removed demoTagTemplate and added a code snippet to the docs

- src/ng1/directives/treegrid/treegrid.controller.js
https://portal.digitalsafe.net/browse/EL-3594
- Previously every time the tree grid was rendered the expanded state was based on it the item was expanded or the expand top level option was set. Now I have updated it to only check the expand top level option on initial render, then afterwards base it on the expanded state only
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3594-Tree-Grid-Expand-Top-Level
> EL_3594 - Tree Grid Expand Top Level

- src/components/tag-input/tag-input.component.less
- src/components/tag-input/tag-input.component.ts
https://portal.digitalsafe.net/browse/EL-3605
- Implemented `Validator` interface to ensure we remain compatible
- Added support for marking component as touched
- Added error styling based on the presence of the `ng-invalid` class which will get applied for both template and reactive form errors.
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3605-Tag-Reactive-Form
> EL-3605 - Tag Input Reactive Forms

- .gitignore
- docs/app/pages/components/components-sections/panels/side-panel/side-panel.component.html
- docs/app/pages/components/components-sections/panels/side-panel/snippets/app.html
- e2e/tests/components/side-panel/side-panel.e2e-spec.ts
- e2e/tests/components/side-panel/side-panel.po.spec.ts
- src/common/index.ts
- src/common/utilities/trigger-source.ts
- src/components/item-display-panel/item-display-panel.component.html
- src/components/item-display-panel/item-display-panel.component.ts
- src/components/item-display-panel/item-display-panel.module.ts
- src/components/menu/menu-item/menu-item.component.ts
- src/components/side-panel/side-panel-animations.ts
- src/components/side-panel/side-panel-close.directive.ts
- src/components/side-panel/side-panel.component.html
- src/components/side-panel/side-panel.component.ts
- src/components/side-panel/side-panel.module.ts
- src/components/side-panel/side-panel.service.ts
- src/directives/accessibility/focus-indicator/focus-indicator.directive.ts
https://portal.digitalsafe.net/browse/EL-3559
- Side Panel content is now not inserted into the DOM until it is opened
- Side panel now uses `OnPush` change detection for better performance
- Updated tests
- The `openChange` event was emitted initially even though it did not change. Now only emits once a change has occurred
- Pressing escape previously triggered the close event even if the side panel was not open
- Added utility functions to determine if a `click` event is triggered by the mouse or by the enter key
- Updated focus indicator directive to coerce boolean values, this way we can set the values using a string instead of a binding if the values never change, allowing Angular to skip checking these during change detection eg. `[programmaticFocusIndicator]="false"` could now just …
> EL-3559 - Side Panel Improvements

- docs/app/pages/css/css-sections/icons/ux-icons/icon-preview/icon-snippet/icon-snippet.component.less
https://portal.digitalsafe.net/browse/EL-3593
- Fixing copy icon button alignment in IE:
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3593-Icon-Alignment-Fix
> EL-3593 - IE Fixing Icon Alignment

- Gruntfile.js
- grunt/execute.js
- package-lock.json
- package.json
- scripts/typescript-compat.js
- scripts/typescript-transforms.js
N/A
1. TypeScript converted `ReadonlyArray<T>` to `readonly T[]` which breaks in versions lower than 3.4
2. Angular 8 renamed `defineInjectable` and `inject` (https://angular.io/api/core/defineInjectable) and instead the import should now be `ɵɵdefineInjectable` and `ɵɵinject`, there is no change in functionality, just a rename to indicate it is a private function. While the old imports are still available until Angular 11, as we are now using the Angular 8 compiler it has been updated to use the private imports.
Both of these can be solved with TypeScripts transform API, which I have added as as step after the library build.
After this is run the package now build successfully in Angular 6, 7 and 8 in production mode.
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_ …
> Fixing backwards compatibility

- docs/app/pages/css/css-sections/icons/icons.module.ts
- docs/app/pages/css/css-sections/icons/ux-icons/icon-preview/icon-preview.component.html
- docs/app/pages/css/css-sections/icons/ux-icons/icon-preview/icon-preview.component.less
- docs/app/pages/css/css-sections/icons/ux-icons/icon-preview/icon-preview.component.ts
- docs/app/pages/css/css-sections/icons/ux-icons/ux-icons.component.html
- docs/app/pages/css/css-sections/icons/ux-icons/ux-icons.component.less
- docs/app/pages/css/css-sections/icons/ux-icons/ux-icons.component.ts
- docs/styles.less
https://portal.digitalsafe.net/browse/EL-3552
- Added in size selector for ux-icon for 16px, 24px, 32px
- Default 24px
- Added in <code>size</code> to ux-icon clipboard copy
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3552-add-size-selector-icon-documentation
> EL-3552 - Add size selector to the Icons documentation

- docs/app/pages/components/components-sections/input-controls/typeahead/snippets/app.html
- docs/app/pages/components/components-sections/input-controls/typeahead/typeahead.component.html
https://portal.digitalsafe.net/browse/EL-3599
- Missing type of text in Input for typehead causing focus styles to be wrong in MF site
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_typeahead-input-type
> EL-3599 - Missing type text for input typeahead

- docs/app/pages/components/components-sections/input-controls/input-dropdown/input-dropdown.component.less
- docs/app/pages/components/components-sections/input-controls/input-dropdown/snippets/app.css
Updated styling so the focus outline appears inside the dropdown for both Keppel and MF sites.
Also removed `font-size` style rule as it does not appear to have any effect in either Keppel or MF sites.
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3621-Input-Dropdown-Focus-Styling
> EL-3621 - Input Dropdown Styling Fix

- src/styles/buttons.less
- src/styles/labels.less
https://portal.digitalsafe.net/browse/EL-3645
Hyperlinks and labels show up with the incorrect font in the Micro Focus theme. This was not noticed in the documentation since we were building the Less stylesheet with new variables. In this case, these components should be fine with the inherited font.
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3645-label-hyperlink-font
> EL-3645 - Removed some unnecessary font-family rules

- src/components/menu/menu.spec.ts
- src/components/menu/menu/menu.component.ts
https://portal.digitalsafe.net/browse/EL-3644
- When a submenu item was clicked (submenu hover set to `true`), which closed the menu, the internal hover and focus states were not reset, so when you opened the menu a second time and the mouse entered the submenu trigger it showed the submenu but the submenu did not get hidden because it thought the mouse was still over the submenu due to the state it was in when it was first closed.
- Simply resetting the state correctly when a menu is closed fixes the issue.
- Also added test to ensure the menu states get the correct value when they are closed.
- Updated existing tests to use `fixture.whenStable()` instead of `Promise.resolve()`
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3644-Menu-Bug
> EL-3644 - Menu Visibility Issue

- docs/app/pages/components/components-sections/input-controls/number-picker/number-picker.component.html
- src/components/number-picker/number-picker.component.less
- src/components/number-picker/number-picker.component.spec.ts
- src/components/number-picker/number-picker.component.ts
https://portal.digitalsafe.net/browse/EL-3636
- removed has-error styling when disabled
- Added styling for ng-invalid
- Added in tests for number picker
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3636-number-picker-validation
> EL-3636 - Number picker validation fix and tests

- src/ng1/directives/infiniteScroll/infiniteScroll.controller.js
https://portal.digitalsafe.net/browse/EL-3646
The issue is that the interval created within `ensureScrollable` triggers a reinitialize of the jScrollPane plugin, which triggers another call to `ensureScrollable` and so on.
One fix which seems to work is to remove the call to `scrollpane.reinitialise()`. However this was explicitly added to address an issue which cannot now be identified so for safety I have left it in place. This fix instead ensures that the cascade of multiple setIntervals does not occur. Since the interval is never cancelled, the first one created should be sufficient.
Updated plunker - reduce the preview panel to <600px to reproduce:
https://plnkr.co/edit/UNjWhAPQMoTmjOqhdhaj?p=preview
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3 …
> EL-3646 - Fix for performance issue

- docs/app/pages/components/components-sections/wizard/wizard/wizard.component.html
https://portal.digitalsafe.net/browse/EL-3638
* Removed `footerTemplate` input documentation.
* Moved the "Custom Templates" section towards the end of the section, matching the Marquee Wizard documentation layout.
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3638-wizard-documentation-corrections
> EL-3638 - Corrected mistakes in the Wizard documentation

- src/components/side-panel/side-panel.component.spec.ts
- src/components/side-panel/side-panel.component.ts
- src/components/side-panel/side-panel.service.ts
https://portal.digitalsafe.net/browse/EL-3639
- Side Panel opens if open initially set to true
- Karma tests added to test initially setting panel open and checking when the openChange event is emitted.
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3639-side-panel-initially-open
> EL-3639 - Side panel initially open

- e2e/protractor.config.js
- e2e/tests/components/tags/tags.e2e-spec.ts
- package-lock.json
- package.json
- src/components/tag-input/tag-input.component.ts
https://portal.digitalsafe.net/browse/EL-3662
Fixing error that occurs in console when clicking on input field when tag limit is reached
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3662-Tag-Input-Error
> EL-3662-Fixing tag input error

- src/components/time-picker/time-picker.component.ts
- src/components/time-picker/time-picker.spec.ts
https://portal.digitalsafe.net/browse/EL-3649
- Moved checking if the <code>hour</code> and <code>currentHour</code> are the same until after the hour entered is checked to be valid. This is because when entering '13' you first enter '1' which would set the <code>currentHour</code> to '13' as '1' is 13 in PM. Once the '3' is added to '13' the <code>currentHour</code> was '13' and the <code>hour</code> is now '13' which would have matched and exited. So I have changed this so that the hour entered is being checked first to see if it is valid so 13 would not be allowed.
- Added a karma test to cover this issue.
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3649-time-picker
> EL-3649 - Time Picker Invalid Time Entered

- .gitignore
- grunt/webfont.js
- src/styles/ux-icons.less
https://portal.digitalsafe.net/browse/EL-3653
Added ttf file type to grunt file for icon-set generation as requested
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3653-add-ttf-to-icon-set
> Added ttf generation to grunt file for icons

- .gitignore
- scripts/run-ci-local.js
Large amount of time spent running `npm ci` when switching between docker and the dev environment.
Updated the docker script to keep a copy of node_modules when switching between docker and the dev environment. This should hopefully save time spent on running `npm ci`.
N/A
> Attempt to preserve dependencies when using docker

- grunt/jasmine.js
- src/ng1/directives/fixedHeaderTable/fixed-header-table.controller.js
- src/ng1/directives/fixedHeaderTable/fixed-header-table.spec.js
https://portal.digitalsafe.net/browse/EL-3673
Table head was being rendered before table body, so was not accounting for the scrollbar. A watcher was added to rerender the layout if the table width is greater than 0.
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3673-Fixed-header-table-alignment
> Wait for table width before adding header padding

- src/components/table/table-column-resize/table-column-resize-expanding/resizable-expanding-table.directive.ts
https://portal.digitalsafe.net/browse/EL-3675
Issue occurs whenever we switch to expanded mode, then collapse the fixed header table accordion and then expand it again.
Essentially when the table is hidden (but not removed, eg: not using ngIf), it gets a width of 0. Whenever it no longer has a width of 0, e.g. when the accordion gets expanded again, we need to re-run some of the initial column size logic again to ensure columns get the right sizes.
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3675-Resizable-Column-Fix
> EL-3675 - Colum resizing fix

- guides/developer-standard.md
- scripts/run-ci-local.js
https://portal.digitalsafe.net/browse/EL-3727
User a dedicated directory on the docker host environment for Linux node modules.
> EL-3727: Change docker e2e test execution

- e2e/pages/app/toolbar-search/toolbar-search.testpage.component.html
https://portal.digitalsafe.net/browse/EL-3706
`background="white"` is needed to prevent the icon overlap seen in the Micro Focus theme.
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3706-Toolbar-Search
> EL-3706 - Added background="white" to Toolbar Search e2e testpage

- src/components/number-picker/number-picker.component.ts
https://portal.digitalsafe.net/browse/EL-3694
Added an if to the component to say if the component is not destroyed then run change detection
which works around for Angular bug
https://jenkins.swinfra.net/job/SEPG/job/UXAspects/view/Developer/job/UXAspects~UXAspects~EL-3694-Form-Control-destroy-issue-2~CI/
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3694-Form-Control-destroy-issue-2 
Microfocus build
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/caf_CI_ux-aspects-micro-focus_EL-3694-Form-Control-destroy-issue-2/#/landing
> EL-3694-Form-Control-destroy-issue

- docs/app/pages/components/components-sections/input-controls/tags/tags.component.html
- src/components/select/select.component.html
- src/components/select/select.component.spec.ts
- src/components/select/select.component.ts
- src/components/tag-input/tag-input.component.html
- src/components/tag-input/tag-input.component.ts
https://portal.digitalsafe.net/browse/EL-3715
Marking the component as touched when using ngModel when the user clicks on the component. Also added an event for the multiple option by emitting and event to the parent component. 
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3715-FormTouched
> EL-3715-FormTouched

- e2e/pages/styles.css
- e2e/tests/components/select/forms/select-forms.e2e-spec.ts
- e2e/tests/components/select/standard/select.e2e-spec.ts
https://portal.digitalsafe.net/browse/EL-3804
- Uncommented select screenshot tests
- Removed the transition on the form control which causes a delay for the focus state
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3804-screenshot-failure
https://jenkins.swinfra.net/job/SEPG/job/UXAspects/view/Developer/job/UXAspects~UXAspects~EL-3804-screenshot-failure~CI/
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/caf_CI_ux-aspects-micro-focus_EL-3804-screenshot-failure
https://jenkins.swinfra.net/job/SEPG/job/caf/view/Developer/job/caf~ux-aspects-micro-focus~EL-3804-screenshot-failure~CI/
> EL-3804 - screenshot failure

- src/components/date-range-picker/date-range-picker.spec.ts
- src/components/date-time-picker/date-time-picker.spec.ts
https://portal.digitalsafe.net/browse/EL-3871
Tests depend on being run on a system in the +0 timezone, which will not always be the case. Stub the `getTimezoneOffset` function to always return 0 when running these tests.
The explicit timezone in these tests causes the date to be adjusted to the local timezone when parsed, and therefore (depending on the system timezone) may no longer match the expected date when displayed in the date range picker.
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3871-timezone-tests
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-3871-timezone-tests~CI/)
> EL-3871 - Fix timezone related karma test failures

- src/components/table/column-picker/column-picker.component.html
- src/components/table/column-picker/column-picker.component.less
- src/components/table/table.module.ts
https://portal.digitalsafe.net/browse/EL-3902
This branch fixes two issues:
- When scrolling the deselected items in the column picker the scroll area comes into focus (outline now removed).
- Sometimes the list items within deselected also have a focus state that we do not want to see we have our own custom styling to show this (outline also removed).
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3902-column-picker-grouping-focus-fix
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/view/Developer/job/caf~ux-aspects-micro-focus~EL-3902-column-picker-grouping-focus-fix~CI/)
> EL-3902 - Column grouping fix focus issue

- configs/webpack.docs.dev.config.js
- docs/app/pages/components/components-sections/select/select-list/select-list.component.ts
- src/components/select/select.component.html
https://portal.digitalsafe.net/browse/EL-3950
* Fix ExpressionChanged error for aria-controls.
* There were some other errors in the console which were quite straightforward to fix so I have included those fixes here as well.
Since discussing these errors during storytime I have not been able to reproduce the second occurrence noted in the ticket.
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3950-select-expression-changed
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-3950-select-expression-changed~CI/)
> EL-3950 - Select: ExpressionChangedAfterItHasBeenCheckedError

- docs/app/pages/css/css-sections/icons/ux-icons/ux-icons.component.html
- scripts/inline-less.js
https://portal.digitalsafe.net/browse/EL-3940
* Update the less script to create a secondary stylesheet for the distribution named ux-aspects-no-legacy. This is identical to the ux-aspects stylesheet except for the removal of hpe-icons.less.
* Mark hpe-icon set as deprecated.
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3940-remove-hpe-icons
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-3940-remove-hpe-icons~CI/)
> EL-3940 - Provide a stylesheet without hpe-icons

- docs/app/data/components-page.json
- docs/app/pages/components/components-sections/buttons/dropdowns/dropdowns.component.html
- docs/app/pages/components/components-sections/buttons/split-button-dropdowns/snippets/app.microfocus.html
- docs/app/pages/components/components-sections/buttons/split-button-dropdowns/split-button-dropdowns.component.html
- docs/app/pages/components/components-sections/buttons/split-button-dropdowns/split-button-dropdowns.component.ts
https://portal.digitalsafe.net/browse/EL-3960
- Document `uxMenuParent` input
- Ensure the appropriate icon is displayed within the documentation
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3960-split-button-dropdown2
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-3960-split-button-dropdown2~CI/)
> EL-3960 - Split Button Dropdown: rework example to use ux-menu

- docs/app/pages/components/components-sections/wizard/marquee-wizard/marquee-wizard.component.html
- src/components/marquee-wizard/marquee-wizard.component.spec.ts
- src/components/marquee-wizard/marquee-wizard.component.ts
https://portal.digitalsafe.net/browse/EL-3956
* Add `resetVisitedOnValidationError` input, which can be used to prevent automatic setting of `visited`.
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3956-prevent-visited-change-on-validation
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-3956-prevent-visited-change-on-validation~CI/)
> EL-3956 - Marquee wizard resetVisitedOnValidationError setting

- docs/app/pages/components/components-sections/input-controls/number-picker/number-picker.component.html
- src/components/number-picker/number-picker.component.spec.ts
- src/components/number-picker/number-picker.component.ts
Scrolling though a page can cause accidental changes to the values of number pickers.
Number pickers now  only change values when scrolled if they have focus
Do not have access to Jenkins
Do not have access to Jenkins
> Prevent scrolling though page affecting number pickers

- src/components/marquee-wizard/marquee-wizard.component.spec.ts
- src/components/wizard/wizard.component.ts
https://portal.digitalsafe.net/browse/EL-4012
Move the subscription to `steps` back into the `ngAfterContentInit` handler. See Jira ticket for the repro plunker example.
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4012-marquee-wizard-fix
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-4012-marquee-wizard-fix~CI/)
> EL-4012 - Marquee Wizard: initial step not visible when loading steps after initialization

- e2e/tests/components/dashboard/dashboard.e2e-spec.ts
- src/components/dashboard/dashboard.component.ts
- src/components/dashboard/dashboard.service.ts
- src/components/dashboard/dashboard.spec.ts
https://portal.digitalsafe.net/browse/EL-4010
* Add initialized$ state to replace use of dimensions$ in the setLayoutData subscription.
* Add new e2e test including a second drag operation.
* Fixed some incorrect descriptions in a karma test.
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4010-dashboard-drag
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-4010-dashboard-drag~CI/)
> EL-4010 - Dashboard: cannot move additional widgets after initial move

- docs/app/pages/components/components-sections/tree-view/tree-grid/snippets/app.html
- docs/app/pages/components/components-sections/tree-view/tree-grid/tree-grid.component.html
- src/directives/tree-grid/tree-grid-row.directive.ts
- src/directives/tree-grid/tree-grid.directive.ts
- src/directives/tree-grid/tree-grid.service.ts
- src/directives/tree-grid/tree-grid.spec.ts
https://portal.digitalsafe.net/browse/EL-4023
This particular problem was caused by the `_expanded$` subscription being invoked for every row, even if the bound value was false. This also caused `rows$` to change as well. Since they both included tick operators, a lot of time was wasted on this.
* Replace `_expanded$` with equivalent code in the setter.
* Remove `tick` from the `rows$` subscription. This is a workaround for an ExpressionChanged error, which can be avoiding by not 2-way binding the `rows` input. (The `rows` input actually does nothing and was probably only implemented to enable the convenient template syntax.)
* Update documentation and example to use `rowsChange` instead of 2-way binding `rows`.
* Mark the `rows` input as deprecated. …
> EL-4023 - Fix another tree grid performance issue

- e2e/tests/components/date-time-picker/date-time-picker.e2e-spec.ts
- e2e/tests/components/date-time-picker/date-time-picker.po.spec.ts
- src/components/date-time-picker/date-time-picker.service.ts
https://portal.digitalsafe.net/browse/EL-3959
- `Date`'s set date, month and year methods accept invalid values and will automatically correct them. In this case, setting the month value before the day can cause a month to be incorrectly skipped. Using `setMonth` with both month and day values ensures that the date is correctly set.
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3959-datepicker-incorrectdate
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-3959-datepicker-incorrectdate~CI/)
> EL-3959 - Date & Time Picker: incorrect date selected

- docs/app/pages/components/components-sections/input-controls/typeahead/typeahead.component.html
- docs/app/pages/components/components-sections/select/select/select.component.html
- e2e/tests/components/custom-facet/custom-facet.e2e-spec.ts
- e2e/tests/components/marquee-wizard/marquee-wizard.e2e-spec.ts
- e2e/tests/components/tabbable-list/tabbable-list.po.spec.ts
- src/components/dashboard/dashboard.spec.ts
- src/components/facets/facet-check-list.component.spec.ts
- src/components/hierarchy-bar/hierarchy-bar.component.spec.ts
- src/components/marquee-wizard/marquee-wizard.component.spec.ts
- src/components/number-picker/number-picker.component.spec.ts
- src/components/select/select.component.spec.ts
- src/components/side-panel/side-panel.component.spec.ts
- src/components/table/column-picker/column-picker.component.spec.ts
- src/components/tabset/tabset.component.spec.ts
- src/components/tooltip/tooltip.directive.spec.ts
- src/components/typeahead/typeahead-option-api.ts
- src/components/typeahead/typeahead-options-list.component.html
- src/components/typeahead/typeahead-options-list.component.ts
- src/components/typeahead/typeahead-visible-option.ts
- src/components/typeahead/typeahead.component.ts
- src/components/typeahead/typeahead.spec.ts
- src/components/wizard/wizard.component.spec.ts
- src/directives/badge/badge.spec.ts
- src/directives/infinite-scroll/infinite-scroll.component.spec.ts
- tslint.json
https://portal.digitalsafe.net/browse/EL-3926
Previously the disabled property was added to the item objects in the typeahead themselves, this meant having to update them any time selection changed etc... This was hard when using paging as the infinite scroll directive keeps these items in memory too, so they could further get out of sync. It also meant there was a function on the class to check if it something was disabled and a property on the item to store the disabled state and they could return different results if they are out of sync.
The typeahead also accepted an input called `disabledOptions` which was documented but was never used by the typeahead so was technically broken. I have removed this internal isDisabled property on each item and instead updated to use the …
> EL-3926 - Select Disabled Options

- e2e/pages/app/typeahead/typeahead.testpage.component.ts
- e2e/tests/components/typeahead/typeahead.e2e-spec.ts
- e2e/tests/components/typeahead/typeahead.po.spec.ts
- src/components/select/select.component.ts
- src/components/tag-input/tag-input.component.ts
- src/components/typeahead/typeahead.component.ts
https://portal.digitalsafe.net/browse/EL-4061
After some investigation the issue was slightly different than I think we initially suspected. Neither stopping propagation or creating a new output was the solution to the issue. 
The issue is caused by a Chrome bug, that will blur an input when a scrollbar is used if a parent element has a tabindex set. So the side panel is one potential cause as it has a tabindex="0", but really it could be any parent element.
The solution is to `preventDefault` if a mousedown event occurs within the scrollbar region of the typeahead.
Due to this, I couldn't find a way to add a test for this, as it requires the scroll to be performed using the mouse, its not standard behaviour that occurs whenever general scrolling happens, but if you have any suggestions …
> EL-4061 - Tag Input Focus Out

- src/components/wizard/wizard.component.html
- src/components/wizard/wizard.component.spec.ts
https://portal.digitalsafe.net/browse/EL-4101
Added stp.visited to class.invalid which fixes the regression in the steps having an invalid appearance before being visited
Added a karma test  to verify that: invalid appearance is not shown when valid = false and visited = false &
Invalid appearance should be shown when valid = false and visited = true
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4101-Wizard-steps-invalid
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-4101-Wizard-steps-invalid~CI/)
> EL-4101 - Wizard-steps-invalid

- src/components/breadcrumbs/breadcrumbs.component.html
- src/components/page-header/page-header.component.spec.ts
https://portal.digitalsafe.net/browse/EL-4086
- Prevent duplicate breadcrumbs when using routerLink and onClick
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4086-duplicate-breadcrumbs
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-4086-duplicate-breadcrumbs~CI/)
> EL-4086 - Prevent duplicate breadcrumbs when using routerLink and onClick

- docs/app/pages/components/components-sections/dashboard/dashboard/dashboard.component.html
- e2e/pages/app/dashboard/dashboard.testpage.component.html
- e2e/tests/components/dashboard/dashboard.e2e-spec.ts
- src/components/dashboard/dashboard.service.ts
- src/components/dashboard/dashboard.spec.ts
- src/components/dashboard/widget/dashboard-widget.component.ts
https://portal.digitalsafe.net/browse/EL-4170
- Add new `autoPositioning` input which determines whether or not to move the widget into any free space above it when available
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4170-widget-repositioning
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-4170-widget-repositioning~CI/)
> EL-4170 - Dashboard - allow disabling of widget repositioning

- src/components/hierarchy-bar/hierarchy-bar-standard/hierarchy-bar-standard.component.less
- src/components/popover/popover.directive.ts
- src/components/tooltip/tooltip.directive.ts
- src/styles/tooltips.less
- src/styles/zindex.less
https://portal.digitalsafe.net/browse/EL-4178
- div with popover directive requires a higher z-index value than the z-index value of `.cdk-overlay-container` to prevent a mouseenter / mouseleave event loop when hovering the the edge that the div and popover share
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4178-popover-loop
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-4178-popover-loop~CI/)
> EL-4178 - Popover - hovering div edges create event loop

- e2e/tests/components/dashboard/dashboard.e2e-spec.ts
- src/components/dashboard/dashboard.service.ts
- src/components/dashboard/widget/dashboard-widget.component.ts
https://portal.digitalsafe.net/browse/EL-4224
1. Added call to sendToBack() in the onDragEnd function in the dashboard.service
2. Set initial values of z-index to null from 0
3. 2 protractor tests to check z-index initially and after moving a widget
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4224-dashboard-z-index
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/view/Developer/job/caf~ux-aspects-micro-focus~EL-4224-dashboard-z-index~CI/)
> EL-4224: Dashboard: z-index values on widgets cause overlap issues

- docs/app/pages/components/components-sections/tooltips/tooltips/tooltips.component.html
https://portal.digitalsafe.net/browse/EL-4079
Updated documentation to mention tooltips don't display on disabled elements
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4079-Tooltip-documentation-update
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-4079-Tooltip-documentation-update~CI/)
> EL-4079 -Updating tooltip documentation

- docs/app/services/playground/utilities/system-helper.ts
[Dashboard demo link to plunker](https://uxaspects.github.io/UXAspects/#/components/dashboard) doesn't work. It can't load `chart.js` because the path is not correct.
Correct `chart.js` path will make the demo work as expected.
> docs: correct chart.js path

- src/components/menu/menu-trigger/menu-trigger.directive.ts
- src/components/menu/menu.spec.ts
- src/components/menu/menu/menu.component.html
- src/components/menu/menu/menu.component.ts
https://portal.digitalsafe.net/browse/EL-4250
- added overlay element id as aria-controls 
- Added role menu to overlay container element
- Updated karma tests to cover this
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4250-menu-accessibility
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-4250-menu-accessibility~CI/)
> EL-4250 - Menu: trigger is not linked to menu container (accessibility)

- src/components/dashboard/widget/dashboard-widget.component.spec.ts
- src/components/dashboard/widget/dashboard-widget.component.ts
- src/components/marquee-wizard/marquee-wizard.component.spec.ts
…has been performed
https://portal.digitalsafe.net/browse/EL-4270
- Checking that the widget layout has occurred before attempting to resize widget
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_dashboard-fix
https://jenkins.swinfra.net/job/SEPG/job/Inner-Source-Incubating/view/Developer/job/Inner-Source-Incubating~ux-aspects-universal~ng-toggle-button~CI/
> Dashboard: Prevent trying to shift widgets before the initial layout has been performed

- e2e/tests/components/tags/tags.e2e-spec.ts
- e2e/tests/components/tags/tags.po.spec.ts
- src/components/tag-input/tag-input.component.ts
https://internal.almoctane.com/ui/entity-navigation?p=131002/7002&entityType=work_item&id=464101
1. ISSUE: There is a console error when tabbing through the component when there are max tags and enforce tag limits is true. The input is removed when this parameter is met and therefore this.tagInput is undefined in the keyHandler function.
2. FIX: Making problem parameters optional.
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_464101-tag-input-console-error
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~464101-tag-input-console-error~CI/)
> 464101 - Tag Input - Console error when enforceTagLimits is at maxTag limit when tabbing through tags

- src/components/breadcrumbs/breadcrumbs.component.html
- src/components/breadcrumbs/breadcrumbs.module.ts
- src/components/navigation/navigation-item/navigation-item.component.html
- src/components/navigation/navigation.module.ts
- src/components/page-header/navigation/navigation-item/navigation-item.component.html
- src/components/page-header/page-header.module.ts
- src/components/tabset/tabset.component.html
- src/components/tabset/tabset.module.ts
- src/directives/router-link/index.ts
- src/directives/router-link/router-link.directive.ts
- src/index.ts
N/A
Angular merged the `RouterLink` and `RouterLinkWithHref` directives in Angular 15. They haven't removed the `RouterLinkWithHref` directive, however the build tooling is detecting any `a[routerLink]` elements as `RouterLink` so in an Angular 14 environment the directive is never getting instantiated.
With this PR I have added a temporary directive `uxRouterLink` that is a modified version of the Angular 15 `RouterLink` directive. I have updated our components to use this directive instead of the Angular one, this way the compiler will not use the wrong one. This directive can be removed and we can revert the `routerLink` whenever we drop support for Angular 14.
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_angular-14-routerlink …
> fix: adding workaround for routerLink angular 14 issues

- src/components/facets/facet.service.ts
https://github.houston.softwaregrp.net/caf/ux-aspects-micro-focus/issues/959
Updated the facet service to use the facet id for comparisons rather than the object.
> Changed facet service to use facet ID for comparisons

- src/components/date-range-picker/date-range-picker.spec.ts
- src/components/date-time-picker/day-view/day-view.component.ts
https://github.houston.softwaregrp.net/caf/ux-aspects-micro-focus/issues/976
Remove problem code, update test coverage to cover fix
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_range-picker-emit
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~range-picker-emit~CI/)
> 976 - Fix date range picker from emitting both onStartChange and onEndChange simultaneously 
