docs/app/pages/components/sections/tables/custom-responsive-table-ng1/codepen/codepen.html, docs/app/pages/css/sections/page-header/page-header-example/snippets/sample.js
=> EL-2468 - Removing Elements

src/ng1/external/ui-bootstrap/ui-bootstrap-tpls.js, src/ng1/plugins/customscroll/jquery.jscrollpane.js, src/ng1/plugins/jquery-validation/jquery-validation.js
Removing some missed usages of old branding
=> EL-2468 - Removing old branding from code

docs/app/pages/changelog/logs/release-v1.0.0.md, guides/angular-upgrade-guide.md, src/ng1/external/ui-bootstrap/ui-bootstrap-tpls.js
Fixing a few minor issues that came back from QA
=> EL-2458, EL-2468, EL-2392 - Fixing QA issues

src/fonts/hpe-icons-license.txt
Added the creative commons license from grommet for the icons, it is build with the rest of our licenses.
=> EL-2399 - Added license for icons

docs/app/pages/charts/sections/bar-charts/bar-chart-ng1/bar-chart-ng1.component.html, docs/app/pages/charts/sections/bar-charts/bar-chart-ng1/bar-chart-ng1.component.ts, docs/app/pages/charts/sections/bar-charts/bar-chart-ng1/snippets/chart.js, docs/app/pages/charts/sections/bar-charts/horizontal-bar-chart-ng1/horizontal-bar-chart-ng1.component.ts, docs/app/pages/charts/sections/bar-charts/horizontal-bar-chart-ng1/snippets/chart.js, docs/app/pages/charts/sections/donut-charts/donut-chart-ng1/donut-chart-ng1.component.html, docs/app/pages/charts/sections/donut-charts/donut-chart-ng1/snippets/legend.css, docs/app/pages/charts/sections/line-charts/line-chart-ng1/line-chart-ng1.component.html, docs/app/pages/charts/sections/line-charts/multiple-axis-line-chart-ng1/multiple-axis-line-chart-ng1.component.html, docs/app/pages/charts/sections/line-charts/stacked-line-chart-ng1/stacked-line-chart-ng1.component.html, docs/app/pages/charts/sections/live-charts/live-chart-ng1/live-chart-ng1.component.html, docs/app/pages/charts/sections/organization-chart/organization-chart-ng1/organization-chart-ng1.component.html, docs/app/pages/charts/sections/organization-chart/organization-chart-ng1/snippets/chart.js, docs/app/pages/charts/sections/partition-map/partition-map-ng1/snippets/chart.js, docs/app/pages/charts/sections/scrollable-chart/scrollable-chart-ng1/scrollable-chart-ng1.component.html, docs/app/pages/charts/sections/social-chart/social-chart-ng1/snippets/codepen/chart.css, docs/app/pages/charts/sections/social-chart/social-chart-ng1/social-chart-ng1.component.html, docs/app/pages/charts/sections/spark-charts/spark-chart-ng1/spark-chart-ng1.component.html, docs/app/pages/charts/sections/timeline-chart/timeline-chart-ng1/timeline-chart-ng1.component.html, src/ng1/directives/partitionMap/partitionMap.service.js, src/ng1/wrappers/spark/spark.directive.js
Fixing QA issues on charts page
=> EL-2384 - Fixing issues on charts page

docs/app/pages/components/sections/wizard/wizard-validation-ng1/snippets/sample.js, docs/app/pages/components/sections/wizard/wizard-validation-ng1/wrapper/wizard-validation-wrapper.directive.ts, src/styles/wizard.less
=> S 55/el 2383 qa2

docs/app/pages/css/sections/labels/labels/codepen/codepen.html, docs/app/pages/css/sections/labels/labels/labels.component.html, docs/app/pages/css/sections/labels/labels/snippets/sample1.html, docs/app/pages/css/sections/page-header/page-header-example/snippets/sample.html
Fixing a couple of issues with the CSS page, there is an issue with the disabled inputs select style in IE however this is a pre existing issue with no simple fix, we should look into this after open sourcing when we have more time.
=> EL-2480 - Fixing QA issues with CSS section

.gitignore, docs/app/assets/licenses.txt
Adding gitignore back in and removing licence file from gitignore
=> S 55/el 2399 ghpages

docs/app/app.module.ts, docs/app/data/top-navigation.json, docs/app/services/services.ts
Removing the customize page for now as it is incomplete
=> Removing customize page

docs/app/data/config.json, docs/app/data/footer-navigation.json, docs/app/data/landing-page.json, docs/app/pages/getting-started/getting-started.component.html, docs/app/pages/getting-started/getting-started.component.ts, docs/app/pages/getting-started/snippets/angular1-downgrade.js, docs/app/pages/getting-started/snippets/angular4-upgrade.txt, docs/app/pages/getting-started/snippets/angular4.txt, docs/app/pages/getting-started/snippets/stylesheet.html, docs/app/pages/landing/landing.component.html
Added Getting Started details.
Update version and links on landing page/footer.
https://jira.autonomy.com/browse/EL-2459
=> S 55/el 2459

docs/app/pages/charts/sections/bar-charts/horizontal-bar-chart-ng1/horizontal-bar-chart-ng1.component.html, docs/app/pages/charts/sections/bar-charts/stacked-bar-chart-ng1/stacked-bar-chart-ng1.component.html, docs/app/pages/charts/sections/donut-charts/nested-donut-chart-ng1/nested-donut-chart-ng1.component.html
Fixing some incorrect links on charts page
=> EL-2384 - Fixing links on charts

docs/app/pages/components/sections/tables/detail-row-header-ng1/detail-row-header-ng1.component.ts, docs/app/pages/components/sections/tables/dynamic-filters-ng1/dynamic-filters-ng1.component.ts, docs/app/pages/components/sections/tables/filters-ng1/filters-ng1.component.ts, docs/app/pages/components/sections/tables/grouping-ng1/grouping-ng1.component.ts, docs/app/pages/components/sections/tables/indices-ng1/indices-ng1.component.ts, docs/app/pages/components/sections/tables/multiple-select-actions-ng1/multiple-select-actions-ng1.component.ts, docs/app/pages/components/sections/tables/multiple-selection-row-ng1/multiple-selection-row-ng1.component.ts, docs/app/pages/components/sections/tables/preview-pane-ng1/preview-pane-ng1.component.ts, docs/app/pages/components/sections/tables/sorting-ng1/sorting-ng1.component.ts, docs/app/pages/components/sections/tables/traditional-multiple-select-actions-ng1/traditional-multiple-select-actions-ng1.component.ts, docs/app/pages/getting-started/getting-started.component.ts
Found that on our getting started page code snippets were displaying incorrectly.
Also found many of the code snippets under tables were missing a context for the base section and failed to load many of the snippets
=> Fixing code snippet issues

docs/app/components/landing-page-header/landing-page-header.component.html, docs/styles.less
Attempting to fix minor issues on mobile displays
=> Fixing mobile issues

src/index.ts
Adding in missing component exports
=> Adding exports for components

docs/app/components/landing-page-feature/landing-page-feature.component.html, docs/app/data/landing-page.json, docs/app/interfaces/ILink.ts
Added router link, I think should work in pages but cant test it
=> EL-2356 - Fixing broken link to blogs on landing page

docs/app/showcase/charts/dist/app/views/common/app_navigation_popover.html, docs/app/showcase/charts/src/app/common/app_navigation_popover.html
=> EL-2390 - Fixing broken link in showcase

docs/app/pages/components/sections/flippable-cards/flippable-cards-ng1/wrapper/flippable-cards-wrapper.directive.ts, src/components/toggleswitch/toggleswitch.component.less, src/ng1/directives/socialChart/socialChart.directive.js, src/styles/controls.less, src/styles/input-controls.less
Updating some styles and adding the color service to the social chart
=> EL-2385 - Fixing some colors

docs/app/pages/components/sections/tables/reorderable-table-ng1/snippets/layout.html, docs/app/pages/components/sections/tables/reorderable-table-ng1/wrapper/reorderable-table-wrapper.directive.html
Changing to use text-success and text-error instead to try to ensure color remain correct despite any future rebranding
=> EL-2484 - Reorderable tables tick colour

src/ng1/directives/socialChart/socialChart.spec.js
Added color service to social chart unit tests
=> Fixing unit tests

docs/app/interfaces/IChangeLog.ts, docs/app/pages/components/sections/buttons/grouped-buttons-ng1/wrapper/grouped-buttons-wrapper.directive.ts, docs/app/pages/components/sections/date-time-picker/date-picker-ng1/wrapper/date-picker-wrapper.directive.ts, docs/app/pages/components/sections/date-time-picker/date-range-picker-ng1/wrapper/date-range-picker-wrapper.directive.ts, docs/app/pages/components/sections/tables/detail-row-header-ng1/wrapper/detail-row-header-wrapper.directive.ts, docs/app/pages/components/sections/tables/multiple-column-sorting-ng1/wrapper/multi-column-sorting-wrapper.directive.ts, docs/app/pages/components/sections/tables/preview-pane-window-ng1/wrapper/preview-pane-window-wrapper.directive.ts, docs/app/pages/components/sections/tables/reorderable-table-ng1/wrapper/reorderable-table-wrapper.directive.ts, docs/app/pages/components/sections/wizard/wizard-validation-ng1/wrapper/wizard-validation-wrapper.directive.ts, docs/app/pages/css/sections/buttons/button-dropdowns/button-dropdowns.component.ts, docs/app/pages/css/sections/buttons/split-button-dropdowns/split-button-dropdowns.component.ts, docs/app/pages/css/sections/icons/fixed-width/fixed-width.component.ts, docs/app/pages/css/sections/text-inputs/dropdown-addons/dropdown-addons.component.ts, docs/app/pages/css/sections/text-inputs/segmented-addons/segmented-addons.component.ts
Fixing ts lint errors that appeared after upgrading ts lint to 5.1.0
=> Fixing TS Lint errors

guides/developer-standard.md
Adding a guide for writing components outlining coding standards
=> EL-2402 - Adding developer standards guide

buildscripts/buildWebService.sh, buildscripts/executeSeleniumTests.sh, buildscripts/executeSeleniumTestsDocker.sh, buildscripts/executeUnitTests.sh, buildscripts/executeUnitTestsDocker.sh, src/test/java/WebDriverTests/WebDriverTests/CSS/Buttons.java, src/test/java/WebDriverTests/WebDriverTests/Charts/BarCharts.java, src/test/java/WebDriverTests/WebDriverTests/Charts/Spark.java, src/test/java/WebDriverTests/WebDriverTests/Components/Buttons.java, src/test/java/WebDriverTests/WebDriverTests/Components/InputControls.java, src/test/java/WebDriverTests/WebDriverTests/Components/ItemDisplayPanel.java, src/test/java/WebDriverTests/WebDriverTests/Components/Select.java, src/test/java/WebDriverTests/WebDriverTests/Components/SideInsetSplitters.java, src/test/java/WebDriverTests/WebDriverTests/Components/Tabs.java, src/test/java/WebDriverTests/WebDriverTests/Components/TreeViews.java, src/test/java/WebDriverTests/WebDriverTests/Components/Wizard.java, src/test/java/WebDriverTests/WebDriverTests/UXAspectsTesting/CloseDriver.java, src/test/java/WebDriverTests/WebDriverTests/UXAspectsTesting/OpenPage.java, src/test/java/WebDriverTests/WebDriverTests/UXAspectsTesting/TestNGBase.java, src/test/java/WebDriverTests/WebDriverTests/UXAspectsTesting/Utilities.java, src/test/java/WebDriverTests/WebDriverTests/UXAspectsTesting/WebDriverStore.java, testng.xml
Updated CSS locators.
Changed test user to UXAspectsTestUser.
Commented out Firefox tests which will not work until a new version of Zone.js is released.
Commented out most IE 11 tests.
Updated build scripts to execute unit tests and Selenium tests.
=> EL-2469 Reworked Selenium tests for new repository.

docs/app/pages/charts/sections/line-charts/multiple-axis-line-chart/multiple-axis-line-chart.component.ts, docs/app/pages/charts/sections/line-charts/multiple-axis-line-chart/snippets/line-chart.ts
Wrapping expression change in a timeout as it occurs in afterViewInit hook
=> EL-2428 - Moving expression to timeout

guides/developer-standard.md, src/components/checkbox/checkbox.component.less, src/components/checkbox/checkbox.component.ts, src/components/ebox/ebox.component.less, src/components/ebox/ebox.component.ts, src/components/flippable-card/flippable-card.component.less, src/components/flippable-card/flippable-card.component.ts, src/components/progressbar/progressbar.component.less, src/components/progressbar/progressbar.component.ts, src/components/radiobutton/radiobutton.component.less, src/components/radiobutton/radiobutton.component.ts, src/components/spark/spark.component.less, src/components/spark/spark.component.ts, src/components/toggleswitch/toggleswitch.component.less, src/components/toggleswitch/toggleswitch.component.ts, src/styles/ux-aspects.less
Removing Angular component style encapsulation and moving to a tag selector based approach for style encapsulation.
=> EL-2499 Component Theming

src/ng1/directives/draggableCards/cards/draggableCard.directive.js, src/ng1/directives/draggableCards/draggableCards.directive.js
allowEditing & allowRemoving can now be dynamically updated
=> EL-2512 - Draggable cards dynamically changing edit and remove

buildscripts/buildRelease.sh, buildscripts/executeSeleniumTests.sh, buildscripts/executeSeleniumTestsDocker.sh, buildscripts/executeSeleniumTestsReleaseBuild.sh, buildscripts/executeSeleniumTestsReleaseBuildDocker.sh, buildscripts/executeUnitTests.sh, grunt/connect.js, grunt/jasmine.js
Script will execute unit and Selenium tests.
Tidied output of unit tests.
=> EL-2529 Complete migration of release build script.

docs/app/components/usage-link/usage-link.component.ts
=> EL-2507 - Fixing ts lint failures

src/styles/theme.less
Fixing issue which caused white text on a white background in IE
=> EL-2467 - Fixing ie issue

src/ng1/external/ui-bootstrap/ui-bootstrap-tpls.js
Fixing issues in codepen in IE
=> EL-2482 - Fixing IE codepen issue

docs/app/pages/charts/sections/bar-charts/bar-chart-ng1/bar-chart-ng1.component.html, docs/app/pages/charts/sections/bar-charts/horizontal-bar-chart-ng1/horizontal-bar-chart-ng1.component.html, docs/app/pages/charts/sections/bar-charts/stacked-bar-chart-ng1/stacked-bar-chart-ng1.component.html, docs/app/pages/charts/sections/donut-charts/donut-chart-ng1/donut-chart-ng1.component.html, docs/app/pages/charts/sections/donut-charts/nested-donut-chart-ng1/nested-donut-chart-ng1.component.html, docs/app/pages/charts/sections/line-charts/line-chart-ng1/line-chart-ng1.component.html, docs/app/pages/charts/sections/line-charts/multiple-axis-line-chart-ng1/multiple-axis-line-chart-ng1.component.html, docs/app/pages/charts/sections/line-charts/stacked-line-chart-ng1/stacked-line-chart-ng1.component.html, docs/app/pages/charts/sections/live-charts/live-chart-ng1/live-chart-ng1.component.html, docs/app/pages/charts/sections/organization-chart/organization-chart-ng1/organization-chart-ng1.component.html, docs/app/pages/charts/sections/partition-map/partition-map-ng1/partition-map-ng1.component.html, docs/app/pages/charts/sections/peity-charts/peity-charts-ng1/peity-charts-ng1.component.html, docs/app/pages/charts/sections/sankey-chart/sankey-chart-ng1/sankey-chart-ng1.component.html, docs/app/pages/charts/sections/scrollable-chart/scrollable-chart-ng1/scrollable-chart-ng1.component.html, docs/app/pages/charts/sections/social-chart/social-chart-ng1/social-chart-ng1.component.html, docs/app/pages/charts/sections/spark-charts/spark-chart-ng1/spark-chart-ng1.component.html, docs/app/pages/charts/sections/timeline-chart/timeline-chart-ng1/timeline-chart-ng1.component.html, docs/app/pages/components/sections/contacts/contacts-ng1/contacts-ng1.component.html
=> S 57/el 2500

docs/app/components/component-section/component-section.component.html, docs/app/components/component-section/component-section.component.less, docs/app/components/edit-example-link/edit-example-link.component.html, docs/app/components/edit-example-link/edit-example-link.component.less, docs/app/components/edit-example-link/edit-example-link.component.ts, docs/app/components/usage-link/usage-link.component.html, docs/app/components/usage-link/usage-link.component.less, docs/app/components/usage-link/usage-link.component.ts
Some changes requested by Roland: https://jira.autonomy.com/browse/EL-2507
=> EL-2507 - Making some styling changes for usage popover

docs/app/pages/charts/sections/donut-charts/nested-donut-chart-ng1/nested-donut-chart-ng1.component.html
Fixing error when copying the selector over
=> EL-2500 - Typo

docs/app/components/component-section/component-section.component.html, docs/app/components/usage-link/usage-link.component.html
Small padding and margin changes
=> EL-2507 - Fixing padding

src/ng1/directives/displayPanels/displayPanel/displayPanel.directive.js
This reverts console error fix in item display panel
=> Revert "EL-2348 - Fixing errors (#145)"

bower.json, docs/app/pages/getting-started/getting-started.component.html, docs/app/pages/getting-started/getting-started.component.ts, docs/app/pages/getting-started/snippets/tsconfig.txt
Tidying up bower.json file. Added instructions on how to configure TypeScript to find the `ux-aspects` module as typescript currently only searches the node_modules folder by default.
=> EL-2547 - Bower Module Fix

docs/app/pages/components/sections/tables/column-sorting/column-sorting.component.html, docs/app/pages/components/sections/tables/column-sorting/snippets/app.html, src/components/column-sorting/column-sorting.component.less
Making QA changes for https://jira.autonomy.com/browse/EL-2440
=> EL-2440 - Styling changes from QA

docs/app/pages/components/sections/input-controls/sliders/sliders.component.html, docs/app/pages/components/sections/input-controls/sliders/sliders.component.ts, docs/app/pages/components/sections/input-controls/sliders/snippets/app.html, docs/app/pages/components/sections/input-controls/sliders/snippets/app.ts, docs/app/pages/components/sections/input-controls/sliders/snippets/sample4.html, docs/app/pages/components/sections/input-controls/sliders/snippets/sample4.ts, docs/styles.less, src/components/slider/slider.component.ts
Fixing Typos, increasing debounce to 500ms, remove disabling of text selection as this was causing a full page reflow causing quite a large performance hit. Also delaying the initial tooltip positioning.
=> EL-2436 - Slider fixes

docs/app/pages/components/sections/input-controls/sliders/sliders.component.ts, docs/app/pages/components/sections/input-controls/sliders/snippets/app.ts
Making callout the same colour as slider colour
=> EL-2436 - Fixing slider callout colour

docs/app/pages/components/sections/tables/column-sorting/column-sorting.component.html, docs/app/pages/components/sections/tables/column-sorting/snippets/app.html
=> S 58/el 2440   roland

buildscripts/buildRelease.sh
Also changed variable latestCommitID to latestDevelopCommitID to make clearer what it is for.
=> EL-2491 Wrong branch name inserted into branch commit message.

docs/app/pages/blog/posts/2017-05-25-Angular-Productivity.md, docs/app/pages/blog/posts/2017-05-25-Bundle-Optimization.md
=> EL-2504 - Blog Typos

configs/webpack.docs.dev.config.js, docs/app/data/components-page.json, docs/app/pages/components/sections/panels/item-display-panel/item-display-panel.component.html, docs/app/pages/components/sections/panels/item-display-panel/item-display-panel.component.ts, docs/app/pages/components/sections/panels/item-display-panel/modalDOC.html, docs/app/pages/components/sections/panels/item-display-panel/modalPDF.html, docs/app/pages/components/sections/panels/item-display-panel/modalPPT.html, docs/app/pages/components/sections/panels/item-display-panel/snippets/app.html, docs/app/pages/components/sections/panels/item-display-panel/snippets/app.ts, docs/app/pages/components/sections/panels/panels.module.ts, src/components/item-display-panel/index.ts, src/components/item-display-panel/item-display-panel.component.html, src/components/item-display-panel/item-display-panel.component.less, src/components/item-display-panel/item-display-panel.component.ts, src/components/item-display-panel/item-display-panel.module.ts, src/index.ts, src/styles/ux-aspects.less, src/styles/variables.less
Migrating Item display panel to angular 4, added documentation and plunker example.
A new variable was added therefore a pull request has been added to the other repo for that
=> S 59/el 2438

docs/app/pages/components/sections/panels/item-display-panel/item-display-panel.component.html, docs/app/pages/components/sections/panels/item-display-panel/item-display-panel.component.ts, docs/app/pages/components/sections/panels/item-display-panel/snippets/app.html, docs/app/pages/components/sections/panels/item-display-panel/snippets/app.ts, src/components/item-display-panel/item-display-panel.component.less
Fixing issues with animate and shadow and fixing less formatting
=> EL-2438 - QA fixes

docs/app/pages/components/sections/keyboard/hotkeys/hotkeys.component.html
=> EL-2437 - Improving documentation

docs/app/pages/components/sections/input-controls/expanding-text-area-ng1/wrapper/expanding-text-area-wrapper.directive.html, docs/app/pages/components/sections/input-controls/expanding-text-area-ng1/wrapper/expanding-text-area-wrapper.directive.ts
Fixed the placeholder issue in IE, this has just been added in our documentation, not the sample code or codepen as it works as expected there.
=> EL-2511 - Fixing IE bug in Expanding Text Area

docs/app/pages/components/sections/panels/item-display-panel/item-display-panel.component.html, docs/app/pages/components/sections/panels/item-display-panel/item-display-panel.component.ts, docs/app/pages/components/sections/panels/item-display-panel/snippets/app.html, docs/app/pages/components/sections/panels/item-display-panel/snippets/app.ts, src/components/item-display-panel/item-display-panel.component.html, src/components/item-display-panel/item-display-panel.component.ts
=> EL-2438 - Requested changes

src/ng1/directives/componentList/component/component.html, src/styles/component-list.less
Requested by Roland: https://jira.autonomy.com/browse/EL-2417
=> EL-2417 - Remove hover effect has been removed when removing is disabled

docs/app/pages/components/sections/panels/item-display-panel/snippets/app.html, docs/app/pages/components/sections/panels/item-display-panel/snippets/app.ts
Horizontal scrollbars were visible in firefox
=> EL-2438 - Fixing sample code width in firefox

docs/app/pages/components/sections/panels/item-display-panel/item-display-panel.component.html, docs/app/pages/components/sections/panels/item-display-panel/snippets/app.html, src/styles/tables.less
Checkmark was not vertically centered
=> EL-2438 - Fixing checkmark alignment

docs/app/pages/components/sections/tables/custom-filters-component/custom-filters.component.html, docs/app/pages/components/sections/tables/custom-filters-component/custom-filters.component.ts, docs/app/pages/components/sections/tables/filters/filters.component.html, docs/app/pages/components/sections/tables/filters/filters.component.ts, docs/app/pages/components/sections/tables/filters/snippets/app.html
=> EL-2439 - QA Issues

docs/app/pages/components/sections/tables/custom-filters-component/sample/sample-filter.component.html, docs/app/pages/components/sections/tables/custom-filters-component/sample/sample-filter.component.less, docs/app/pages/components/sections/tables/custom-filters-component/snippets/sample.html, docs/app/pages/components/sections/tables/custom-filters-component/snippets/sample.less, docs/app/pages/components/sections/tables/filters/filters.component.ts, docs/app/pages/components/sections/tables/filters/snippets/app.ts, src/components/filters/filter-dropdown/filter-dropdown.component.html, src/components/filters/filter-dropdown/filter-dropdown.component.less, src/components/filters/filter-dynamic/filter-dynamic.component.html, src/components/filters/filter-dynamic/filter-dynamic.component.less
Also set typeahead mincharacters to 1 so we can see it working more clearly
=> EL-2439 - Fixing some UI issues

docs/app/pages/components/sections/wizard/marquee-wizard-ng1/marquee-wizard-ng1.component.html, docs/app/pages/components/sections/wizard/marquee-wizard-ng1/marquee-wizard-ng1.component.ts, docs/app/pages/components/sections/wizard/marquee-wizard-ng1/snippets/fifth.html, docs/app/pages/components/sections/wizard/marquee-wizard-ng1/snippets/fourth.html, docs/app/pages/components/sections/wizard/marquee-wizard-ng1/snippets/sample.js, docs/app/pages/components/sections/wizard/marquee-wizard-ng1/snippets/second.html, docs/app/pages/components/sections/wizard/marquee-wizard-ng1/snippets/sixth.html, docs/app/pages/components/sections/wizard/marquee-wizard-ng1/snippets/third.html, docs/app/pages/components/sections/wizard/marquee-wizard-ng1/wrapper/marquee-wizard-wrapper.directive.ts, src/ng1/directives/marqueeWizard/marqueeWizard.controller.js, src/ng1/directives/marqueeWizard/marqueeWizard.html
Added ability to hide steps in the marquee wizard and updated the documentation.
=> S 60/el 2579

src/components/filters/filter-dynamic/filter-dynamic.component.html, src/components/filters/filter-dynamic/filter-dynamic.component.less, src/components/filters/filter-dynamic/filter-dynamic.component.ts
UI change and the input box now clears between uses
=> EL-2439 - UI Changes

src/components/filters/filter-dynamic/filter-dynamic.component.less
=> EL-2439 - Fixing issues with drop shadow

docs/app/pages/components/sections/wizard/marquee-wizard-ng1/marquee-wizard-ng1.component.html, docs/app/pages/components/sections/wizard/marquee-wizard-ng1/snippets/sample.js, docs/app/pages/components/sections/wizard/marquee-wizard-ng1/wrapper/marquee-wizard-wrapper.directive.ts
going back to change the error state on step 2 will now remove the completed/visited steps on other steps.
Haven't done anything about QA point 5 as its not relevant to the ticket.
https://jira.autonomy.com/browse/EL-2579
=> EL-2579 - QA Changes

LICENSE.md, README.md, docs/app/pages/licenses/licenses.component.html, package.json, src/package.json
Updating license to use Apache 2.0
=> Updating licenses

docs/app/components/documentation-category/documentation-category.component.html, docs/app/components/documentation-category/documentation-category.component.ts, docs/app/components/navigation-bar-search/navigation-bar-search.component.ts, docs/app/components/side-navigation/side-navigation.component.html, docs/app/components/side-navigation/side-navigation.component.ts, docs/app/data/charts-page.json, docs/app/data/components-page.json, docs/app/pages/charts/charts.component.html, docs/app/pages/charts/charts.component.ts, docs/app/pages/charts/charts.module.ts, docs/app/pages/components/components.component.html, docs/app/pages/components/components.component.ts, docs/app/pages/components/components.module.ts, docs/app/services/services.module.ts, docs/app/services/version/version.service.ts, docs/styles.less
Added the version switcher component to the components and charts pages, it has been left out of the CSS page as there is nothing to be filtered on that page.
=> S 60/el 2588

docs/app/components/components.module.ts, docs/app/components/side-navigation/side-navigation.component.html, docs/app/components/side-navigation/side-navigation.component.ts, docs/app/pages/charts/charts.component.html, docs/app/pages/charts/charts.component.ts, docs/app/pages/charts/charts.module.ts, docs/app/pages/components/components.component.html, docs/app/pages/components/components.component.ts, docs/app/pages/components/components.module.ts, docs/app/pages/css/css.component.html, docs/app/pages/css/css.component.ts, docs/app/pages/css/css.module.ts
Buttons no longer scroll off the screen
=> EL-2588 - QA Fix

README.md, bower.json, docs/app/data/config.dev.json, docs/app/data/config.json, docs/app/data/footer-navigation.json, docs/app/data/landing-page.json, docs/app/pages/changelog/changelog.component.ts, docs/app/pages/changelog/logs/release-v1.2.1.md, docs/app/pages/getting-started/getting-started.component.html, package.json, src/package.json
https://jira.autonomy.com/browse/EL-2601
=> S 60/el 2601

src/components/filters/filter-container.component.html, src/components/filters/filter-container.component.less
Replaced clear all button with the same one as is used on the facets, made some styling changes to make it work on the filters.
=> EL-2620 - Replace clear all button

docs/app/components/side-navigation/side-navigation.component.ts, docs/app/data/components-page.json, docs/app/pages/components/sections/input-controls/input-controls.module.ts, docs/app/pages/components/sections/input-controls/number-picker/number-picker.component.html, docs/app/pages/components/sections/input-controls/number-picker/number-picker.component.ts, docs/app/pages/components/sections/input-controls/number-picker/snippets/app.css, docs/app/pages/components/sections/input-controls/number-picker/snippets/app.example.ts, docs/app/pages/components/sections/input-controls/number-picker/snippets/app.html, docs/app/pages/components/sections/input-controls/tags/snippets/app.html, docs/app/pages/components/sections/input-controls/tags/tags.component.html, docs/app/pages/components/sections/input-controls/tags/tags.component.ts, docs/app/pages/components/sections/scrollbar/infinite-scroll/infinite-scroll.component.html, docs/app/pages/components/sections/scrollbar/infinite-scroll/infinite-scroll.component.ts, docs/app/pages/components/sections/scrollbar/infinite-scroll/snippets/app.html, docs/app/pages/components/sections/scrollbar/scrollbar.module.ts, docs/app/pages/components/sections/select/select.module.ts, docs/app/pages/components/sections/select/select/select.component.html, docs/app/pages/components/sections/select/select/select.component.ts, docs/app/pages/components/sections/select/select/snippets/app.html, docs/styles.less, src/components/number-picker/index.ts, src/components/number-picker/number-picker.component.html, src/components/number-picker/number-picker.component.less, src/components/number-picker/number-picker.component.ts, src/components/number-picker/number-picker.module.ts, src/index.ts, src/styles/ux-aspects.less, src/styles/variables.less
- Added Number Picker Angular4 component
- Updated uses in other examples (select, infinite scroll and tags) to use new control
- Fixed timing issue in side navigation
- Changed variables.less & styles.less to follow our style guidelines
=> EL-2614 - Number Picker Migration

docs/app/data/components-page.json, docs/app/pages/components/sections/facets/facet-check-list/facet-check-list.component.html, docs/app/pages/components/sections/facets/facet-check-list/facet-check-list.component.ts, docs/app/pages/components/sections/facets/facet-typeahead-list/facet-typeahead-list.component.html, docs/app/pages/components/sections/facets/facet-typeahead-list/facet-typeahead-list.component.ts, docs/app/pages/components/sections/facets/facet-typeahead-list/snippets/app.html, docs/app/pages/components/sections/facets/facet-typeahead-list/snippets/app.ts, src/components/facets/facet-container.component.html, src/components/facets/facet-container.component.less, src/components/facets/facet-typeahead-list/facet-typeahead-list.component.html, src/components/facets/facet-typeahead-list/facet-typeahead-list.component.less, src/components/facets/facet-typeahead-list/facet-typeahead-list.component.ts, src/components/facets/facets.module.ts
Making some refinements to Facet examples. Also chagin typeahead list facet to allow a "suggestions" list above the typeahead for quick selection
=> EL-2560 - Facet Refinements

docs/app/pages/blog/blog.component.html, docs/app/pages/components/sections/input-controls/custom-dropdown-ng1/snippets/sample.html, docs/app/pages/components/sections/input-controls/custom-dropdown-ng1/wrapper/custom-dropdown-wrapper.directive.html, docs/app/pages/components/sections/modals/side-modal-ng1/snippets/controller.js, docs/app/pages/components/sections/modals/side-modal-ng1/wrapper/side-modal-wrapper.directive.js, docs/app/pages/components/sections/search/search-builder-ng1/snippets/dateRangeComponent.html, docs/app/pages/components/sections/search/search-builder-ng1/snippets/dateRangeComponent.js, docs/app/pages/components/sections/search/search-builder-ng1/wrapper/search-builder-wrapper.directive.js, docs/app/pages/components/sections/utilities/expanding-content-ng1/snippets/sample.snippet.html, docs/app/pages/components/sections/utilities/expanding-content-ng1/wrapper/expanding-content-wrapper.directive.html, docs/styles.less, package-lock.json, package.json, src/styles/buttons.less
Custom dropdown - closes on click outside
Side modal now animates
Search build uses new date picker
Expanding content link behavior:
=> EL-2562 - Example Refinements

docs/app/pages/charts/sections/spark-charts/spark-charts/snippets/app.html, docs/app/pages/charts/sections/spark-charts/spark-charts/snippets/app.ts, docs/app/pages/charts/sections/spark-charts/spark-charts/spark-charts.component.html, docs/app/pages/charts/sections/spark-charts/spark-charts/spark-charts.component.ts, src/components/spark/spark.component.ts
Updated to allow users to specify themes to set both barColor and trackColor.  Documentation updated to include a definition of the theme property, updated definitions of the barColor and trackColor properties, a table of available theme colors, and updated snippets.
=> EL-2606-SparkChartThemeColors

docs/app/pages/charts/sections/spark-charts/spark-charts/snippets/app.html, docs/app/pages/charts/sections/spark-charts/spark-charts/snippets/app.ts, docs/app/pages/charts/sections/spark-charts/spark-charts/spark-charts.component.html, docs/app/pages/charts/sections/spark-charts/spark-charts/spark-charts.component.ts, src/components/spark/spark.component.less, src/components/spark/spark.component.ts
Added default behavior to account for user mistakes when specifying barColor and trackColor
=> S 61/el 2606 spark chart theme colors

docs/app/pages/components/sections/facets/facet-check-list/facet-check-list.component.ts, docs/app/pages/components/sections/facets/facet-check-list/snippets/app.ts, docs/app/pages/components/sections/facets/facet-typeahead-list/facet-typeahead-list.component.html, docs/app/pages/components/sections/facets/facet-typeahead-list/facet-typeahead-list.component.ts, docs/app/pages/components/sections/facets/facet-typeahead-list/snippets/app.ts, src/components/facets/base/facet-base/facet-base.component.ts, src/components/facets/facet-typeahead-list/facet-typeahead-list.component.html, src/components/facets/facet-typeahead-list/facet-typeahead-list.component.less, src/components/facets/facet-typeahead-list/facet-typeahead-list.component.ts
1) Facet typeahead list and facet checklist examples are now sorted alphabetically
2) Typeahead now shows shows more items
3) Typeahead is not aligned with the checkboxes
=> EL-2614 - Adding new facet features

docs/app/data/components-page.json, docs/app/pages/components/sections/help-center/help-center.module.ts, docs/app/pages/components/sections/help-center/help-center/help-center.component.html, docs/app/pages/components/sections/help-center/help-center/help-center.component.less, docs/app/pages/components/sections/help-center/help-center/help-center.component.ts, docs/app/pages/components/sections/help-center/help-center/snippets/app.css, docs/app/pages/components/sections/help-center/help-center/snippets/app.html, docs/app/pages/components/sections/help-center/help-center/snippets/app.ts, docs/app/pages/components/sections/help-center/help-center/snippets/interface.snippet.ts, src/directives/help-center/help-center-item.directive.ts, src/directives/help-center/help-center.module.ts, src/directives/help-center/help-center.service.ts, src/directives/help-center/index.ts, src/index.ts
Adding help center service an directive. Add example using page header component
=> EL-2644 - Help Center

guides/angular-upgrade-guide.md
Updating migration guide to include information on HTML webpack plugin. Also updated references of Angular 1 to AngularJS and Angular 4+ to Angular to follow the official Angular naming recommendation
=> Updating the Angular upgrade guide

docs/app/pages/components/sections/tables/hover-actions/hover-actions.component.html, docs/app/pages/components/sections/tables/hover-actions/hover-actions.component.ts, docs/app/pages/components/sections/tables/hover-actions/snippets/app.html, docs/app/pages/components/sections/tables/tables.module.ts, src/directives/hover-action/hover-action-container.directive.ts, src/directives/hover-action/hover-action.directive.ts
Adding tooltips to hover actions, taking new line in sample code and fixing issue where IE would not show outline on focus
=> Adding tooltips, fixing IE issue, taking new line in sample code

src/styles/breadcrumbs.less, src/styles/main.less, src/styles/ux-aspects.less
- Moving breadcrumbs to it's own stylesheet - making it easier to find as it was buried in main.less
- Refining styles in preparation for Quantum styles
+ Using color instead of opacity
+ Before it was using the up arrow and rotating it, now just uses the arrow initially pointing the correct way
=> EL-2634 - Improving breadcrumb styling

docs/app/pages/components/sections/panels/item-display-panel-inline/snippets/app.html, docs/app/pages/components/sections/panels/item-display-panel/item-display-panel.component.html
=> EL-2639 - QA

docs/app/pages/components/sections/panels/item-display-panel/item-display-panel.component.html
Fixing mistake in documentation
=> EL-2639 - Documentation fix

docs/app/assets/styles/variables.less, docs/app/components/navigation-bar-search/navigation-bar-search.component.less
Hover is now the primary color and active is the darkest grey possible that is comfortable to use.
=> EL-2661 - Accessability changes to search component

docs/app/pages/components/sections/wizard/marquee-wizard-ng1/marquee-wizard-ng1.component.html, src/ng1/directives/marqueeWizard/marqueeWizard.controller.js
Adding support to change step on-finishing event
=> EL-2658 - Marquee wizard, enable changing step on finishing event

docs/app/pages/components/sections/scrollbar/virtual-scroll/virtual-scroll.component.html
=> EL-2694 - Fixing typo

docs/app/pages/charts/sections/bar-charts/stacked-bar-chart/snippets/app.ts, docs/app/pages/charts/sections/bar-charts/stacked-bar-chart/stacked-bar-chart.component.ts, package-lock.json, package.json
Chart.js has been updated to version 2.6, was 2.5. Stacked property has to be set to true on both the x and y axis, previously we had it on only the y axis. Also set @types/angular to version 1.6.6 as the new version causes errors when building aspects.
=> EL-2699 - Fixing stacked bar chart

docs/app/pages/components/sections/date-time-picker/integrated-date-picker-ng1/integrated-date-picker-ng1.component.html, src/ng1/directives/dateTimePicker/dateTimePickerPopup.directive.js, src/styles/controls.less
Allowing placement of 'top' and 'bottom' on popover.
Adjusted styling to remove most of the `!important`.
=> EL-2703 - Enabling placement of the popover

docs/app/pages/components/sections/page-header/page-header/page-header.component.html, src/components/page-header/custom-menu/custom-menu.directive.ts, src/components/page-header/index.ts, src/components/page-header/navigation/navigation-item/navigation-item.component.less, src/components/page-header/navigation/navigation-item/navigation-item.component.ts, src/components/page-header/navigation/navigation.component.html, src/components/page-header/navigation/navigation.component.less, src/components/page-header/navigation/navigation.component.ts, src/components/page-header/page-header.component.html, src/components/page-header/page-header.component.ts, src/components/page-header/page-header.module.ts
Making some changes to the page header component to support some MF branding changes
=> EL-2706 - Support for custom menus and selected indicator animations

docs/app/app.component.ts, docs/app/components/component-section/component-section.component.html, docs/app/components/side-navigation/side-navigation.component.html, docs/app/components/side-navigation/side-navigation.component.ts, docs/app/pages/getting-started/getting-started.component.html, docs/app/services/navigation/navigation.service.ts, docs/app/services/version/version.service.ts
Added a new function which switches the current version if the route changes to a section with a different version specified.
Fixed the version toggles to update correctly with external changes to the version.
Changed several occurrences of "Angular 1" to "AngularJS".
https://jira.autonomy.com/browse/EL-2650
=> EL-2650 - hyperlinks

src/components/slider/slider.component.html, src/components/slider/slider.component.ts
Firefox is not working with the :active pseudo class
=> Making changes to fix Quantum issue with Firefox

src/ng1/directives/dateTimePicker/dateTimePicker.controller.js, src/ng1/directives/dateTimePicker/dateTimePicker.directive.js, src/ng1/directives/dateTimePicker/dateTimePicker.html, src/ng1/directives/dateTimePicker/dateTimePickerPopup.directive.js, src/ng1/templates/ui-bootstrap/datepicker/day.html
I have not added any examples to this to UX Aspects
=> Changes for custom class in integrated date picker

src/ng1/directives/dateTimePicker/dateTimePicker.controller.js, src/ng1/directives/dateTimePicker/dateTimePicker.directive.js, src/ng1/directives/dateTimePicker/dateTimePicker.html, src/ng1/directives/dateTimePicker/dateTimePickerPopup.directive.js, src/ng1/templates/ui-bootstrap/datepicker/day.html
This reverts commit 21c3bab57090dbd68b1c244f2f13d16846879c1d.
=> Revert "Changes for custom class in integrated date picker (#331)"

docs/app/pages/blog/blog.component.ts, docs/app/pages/blog/posts/2017-08-24-Protractor-Testing.md, e2e/tests/components/select/select.e2e-spec.ts, e2e/tests/components/select/select.po.spec.ts
Fixed clash between names of namespace and class.
=> S 65/el 2750

src/ng1/external/ui-bootstrap/ui-bootstrap-tpls.js, src/ng1/templates/ui-bootstrap/datepicker/day.html
Adding today class to date picker
=> EL-2722 - Change for Today in date picker

package.json
Modified package.json file for docs package. 
Ideally this would probably have its own package.json file in the docs folder, however our docs are currently referencing our component scripts in the root/src folder so if i did this the src folder wouldn't be included and cause errors. Likely something we could implement later.
Also included the config/loaders folder to package to include our custom snippet loader. I know there was some discussion about making this a separate package but I don't think this is done yet.
=> Making changes to package.json for docs package

docs/app/components/navigation-bar-search/navigation-bar-search.component.ts, docs/app/components/navigation-bar/navigation-bar.component.ts, docs/app/components/page-footer/page-footer.component.ts, docs/app/pages/customize/customize.component.ts, docs/app/pages/landing/landing.component.ts, docs/app/pages/team/team.component.ts, docs/app/services/app-configuration/app-configuration.service.ts
Added methods to AppConfiguration to return the contents of the data/*.json files, and update them. This is used in the new documentation site to inject custom site layout.
https://jira.autonomy.com/browse/EL-2759
=> Service for data JSON files

src/components/slider/slider.component.html
Added `.active` class when slider is dragged
=> Slider Fix for Firefox

bower.json, docs/app/data/config.dev.json, docs/app/data/config.json, docs/app/data/footer-navigation.json, docs/app/data/landing-page.json, package.json, src/package.json
Since this is a maintenance release I will omit the changelog entry.
=> Update for 1.3.4

docs/app/services/codepen/codepen.service.ts, docs/app/services/plunker/plunker.service.ts
Update to plunker and codepen services
=> EL-2772-PlunkerCodePenExamples

src/components/dashboard/dashboard.component.ts, src/directives/resize/resize.service.ts
=> EL-2725-DashboardResizeError

src/ng1/directives/treegrid/treegrid.controller.js, src/ng1/directives/treegrid/treegrid.html, src/styles/tree-views.less
Added new classes to tree grid
=> el 2771 tree grid

buildscripts/buildRelease.sh
https://jira.autonomy.com/browse/EL-2755
=> Added README.md to the npm workspace

docs/app/pages/getting-started/getting-started.component.html
https://jira.autonomy.com/browse/EL-2788
=> Corrected a typo

docs/app/pages/components/sections/date-time-picker/integrated-date-picker-ng1/integrated-date-picker-ng1.component.html, src/ng1/directives/dateTimePicker/dateTimePickerPopup.controller.js, src/ng1/directives/dateTimePicker/dateTimePickerPopup.directive.js
Could whoever has time please review this. I have added 2 new attributes to the integrated date picker, one for 12hr and 1 for 24hr. These will allow teams to edit the display format and documented the changes.
=> EL-2709 - Added ability to format the integrated datepicker display

docs/app/pages/components/sections/utilities/color-service/color-service.component.html
Small typo in the documentation
=> EL-2777 - Fixing typo

configs/webpack.docs.dev.config.js, configs/webpack.docs.prod.config.js, src/ng1/directives/dateTimePicker/dateTimePickerPopup.controller.js
Fixing bug where the formatting would not accept variables
=> EL-2709 - QA changes

bower.json, docs/app/data/config.dev.json, docs/app/data/config.json, docs/app/data/footer-navigation.json, docs/app/data/landing-page.json, docs/app/pages/changelog/changelog.component.ts, docs/app/pages/changelog/logs/release-v1.3.6.md, package-lock.json, package.json, src/package.json
https://jira.autonomy.com/browse/EL-2795
=> Update for 1.3.6

src/styles/tree-views.less
Removing import and just bringing the base styles into the stylesheet as import from node modules broke the production build
=> EL-2796 - Tree View

docs/app/components/side-navigation/side-navigation.component.ts
Making change to fix issues with side navigation after doctype is added, these changes work as expected both with and without the doctype
=> EL-2308 - Making fix for side navigation after adding doctype

docs/app/pages/components/sections/select/select/select.component.ts, docs/app/pages/css/sections/buttons/size-variations/snippets/code.example.html, package-lock.json, src/components/typeahead/typeahead.component.ts
- Fixed the spacing between the icons and text on the size variation buttons in codepen.
- Fixed the select component example bugs.
=> S 68/el 2798 code pen plunker bugs

src/components/page-header/page-header.component.less, src/styles/breadcrumbs.less, src/styles/controls.less, src/styles/tables.less, src/styles/variables.less, src/styles/wizard.less
Added new variables for:
* Page header
* Breadcrumb
* Select table
* Marquee wizard
=> EL-2794 darwin variables

docs/app/components/side-navigation/side-navigation.component.ts
Recent change broke the side menu in IE, works as expected now both with and without doctype
=> S 68/el 2803 qa

docs/app/pages/components/sections/tree-view/tree-view-custom-node/snippets/app.snippet.css, docs/app/pages/components/sections/tree-view/tree-view-custom-node/snippets/app.snippet.html, docs/app/pages/components/sections/tree-view/tree-view-custom-node/tree-view-custom-node.component.html, docs/app/pages/components/sections/tree-view/tree-view-custom-node/tree-view-custom-node.component.less, docs/app/pages/components/sections/tree-view/tree-view/snippets/app.snippet.css, docs/app/pages/components/sections/tree-view/tree-view/snippets/app.snippet.html, docs/app/pages/components/sections/tree-view/tree-view/tree-view.component.html, docs/app/pages/components/sections/tree-view/tree-view/tree-view.component.less, src/styles/tree-views.less
Making tree-view styling consistent across all browsers
=> EL-2796 - Fixing some styling in IE and Firefox - Tree View

docs/app/pages/components/sections/tree-view/tree-grid-ng1/wrapper/tree-grid-wrapper.directive.ts
Tree Grid section throws an error in the MF docs site
The file loader was returning a path under node modules which didn't exist when ux-aspects-docs package was being used. Instead using raw loader and inserting directly into angularjs templatecache.
=> Fixing Error - Using raw loader instead of file loader

bower.json, docs/app/data/config.dev.json, docs/app/data/config.json, docs/app/data/footer-navigation.json, docs/app/data/landing-page.json, docs/app/pages/changelog/changelog.component.ts, docs/app/pages/changelog/logs/release-v1.4.0.md, package-lock.json, package.json, src/package.json
https://jira.autonomy.com/browse/EL-2811
=> Update for 1.4.0

docs/app/data/components-page.json, docs/app/pages/components/sections/wizard/wizard.module.ts, docs/app/pages/components/sections/wizard/wizard/snippets/app.html, docs/app/pages/components/sections/wizard/wizard/snippets/app.ts, docs/app/pages/components/sections/wizard/wizard/wizard.component.html, docs/app/pages/components/sections/wizard/wizard/wizard.component.ts, src/components/wizard/index.ts, src/components/wizard/wizard-step.component.html, src/components/wizard/wizard-step.component.ts, src/components/wizard/wizard.component.html, src/components/wizard/wizard.component.less, src/components/wizard/wizard.component.ts, src/components/wizard/wizard.module.ts, src/index.ts, src/styles/ux-aspects.less
Jira: https://jira.autonomy.com/browse/EL-2827
Created Angular 4 wizard control
=> EL-2827 - Wizard component

e2e/pages/app/app.module.ts, e2e/pages/app/virtual-scroll/virtual-scroll.testpage.component.ts, e2e/pages/app/wizard/wizard.testpage.component.html, e2e/pages/app/wizard/wizard.testpage.component.ts, e2e/tests/components/wizard/wizard.e2e-spec.ts, e2e/tests/components/wizard/wizard.po.spec.ts
https://jira.autonomy.com/browse/EL-2827
Adding unit tests for wizard component
=> Adding protractor tests for Wizard Component

.gitignore, Gruntfile.js, grunt/clean.js, grunt/compress.js, package-lock.json, package.json
This produces a tgz file at `target/bower/ux-aspects-VERSION.tgz`, for eventual use with SEPG as discussed.
https://jira.autonomy.com/browse/EL-2820
=> Added `compress:bower` and `releasebuild` grunt tasks

docs/app/app.module.ts, docs/app/components/components.module.ts, docs/app/components/navigation-bar-search/navigation-bar-search.component.ts, docs/app/data/components-page.json, docs/app/pages/components/sections/search/search-history-ng1/search-history-ng1.component.html, docs/app/pages/components/sections/search/search-history-ng1/snippets/controller.js, docs/app/pages/components/sections/search/search-history-ng1/wrapper/search-history-wrapper.directive.js, docs/app/pages/components/sections/utilities/persistent-data-service/persistent-data-service.component.html, docs/app/pages/components/sections/utilities/persistent-data-service/persistent-data-service.component.ts, docs/app/pages/components/sections/utilities/persistent-data-service/snippets/app.ts, docs/app/pages/components/sections/utilities/utilities.module.ts, docs/app/services/version/version.service.ts, src/index.ts, src/ng1/directives/applicationSwitcher/applicationSwitcherItem/applicationSwitcherItem.controller.js, src/services/persistent-data/adapters/cookie-adapter.ts, src/services/persistent-data/adapters/local-storage-adapter.ts, src/services/persistent-data/adapters/session-storage-adapter.ts, src/services/persistent-data/adapters/storage-adapter.ts, src/services/persistent-data/index.ts, src/services/persistent-data/persistent-data.module.ts, src/services/persistent-data/persistent-data.service.ts
https://jira.autonomy.com/browse/EL-2818
I have added a service which will attempt to use localStorage before falling back to cookies, you can also choose to save between localStorage, cookies and sessionStorage (this will still fallback to cookies if localStorage fails). 
I have also updated our site to use this where localStorage was being used previously and have added documentation for this service and a note to search builder explaining localStorage issues.
=> EL-2818 - Adding persistent data service and documentation

buildscripts/buildRelease.sh
Modified Git command which commits changes to stage deleted files.
=> EL-2847 Bower 1.4.0 package contains excess files

src/components/typeahead/typeahead.component.less, src/styles/variables.less
Added @dropdown-highlight-bg since by default the dropdown hover color is gray.
https://jira.autonomy.com/browse/EL-2794
=> Added a new variable for Darwin theme

bower.json, docs/app/data/config.dev.json, docs/app/data/config.json, docs/app/data/footer-navigation.json, docs/app/data/landing-page.json, docs/app/pages/changelog/changelog.component.ts, docs/app/pages/changelog/logs/release-v1.4.1.md, docs/app/showcase/charts/package.json, docs/app/showcase/list_view/package.json, package.json, src/package.json
Updating version numbers and adding changelog
=> Release preparation

docs/app/pages/components/sections/dashboard/dashboard/dashboard.component.html, docs/app/pages/components/sections/dashboard/dashboard/snippets/app.html, src/components/dashboard/dashboard.component.ts, src/components/dashboard/dashboard.service.ts, src/components/dashboard/drag-handle/drag-handle.directive.ts, src/components/dashboard/widget/dashboard-widget.component.ts, src/directives/resize/resize.directive.ts, src/directives/resize/resize.service.ts
https://jira.autonomy.com/browse/EL-2839 & https://jira.autonomy.com/browse/EL-2830
Fixing several issues:
- When widgets are dynamically added eg. using ngFor the height of the dashboard isnt recalculated
- When using ngFor to add widgets, they did not get their padding set
- Adding types to resize service subject
- Changing directive selector to follow naming conventions (kept old selector as well to prevent any breaking changes)
=> EL-2830 - Dashboard Fixes

docs/app/pages/components/sections/tables/custom-filters-component/snippets/app.ts
Fixing import statement in sample code
=> Fixing linting error in sample code

src/ng1/directives/splitter/splitter.directive.js
Jira: https://jira.autonomy.com/browse/EL-2828
Find testing instructions here: https://github.com/UXAspects/UXAspects/pull/414
Didnt work in IE previously. Was using .find on a node list which isn't supported in IE. Using forEach instead to find the desired panel
=> EL-2828 - Splitter Fix

docs/app/pages/components/sections/tree-view/tree-view-ng1/tree-view-ng1.component.html, src/ng1/directives/treeView/treeView.controller.js, src/ng1/directives/treeView/treeView.partial.html
Adding support to have tooltips on tree view node labels
=> EL-2835 - Adding support for tooltips on treeview node labels

docs/app/services/plunker/templates/config_js.txt
- Fix new errors found in plunker for the dropdown/select components
=> Fix for new errors in plunker

docs/app/pages/components/sections/notifications/notifications-ng1/notifications-ng1.component.html, docs/app/pages/components/sections/notifications/notifications-ng1/wrapper/notifications-wrapper.directive.html, src/ng1/services/notificationService/notification.service.js
JIRA: https://jira.autonomy.com/browse/EL-2851
Making modifications to allow us to rebrand the notifications
=> Notifications

docs/app/pages/charts/sections/bar-charts/bar-chart/bar-chart.component.html, docs/app/pages/charts/sections/bar-charts/horizontal-bar-chart/horizontal-bar-chart.component.html, docs/app/pages/charts/sections/bar-charts/stacked-bar-chart/stacked-bar-chart.component.html, docs/app/pages/charts/sections/donut-charts/donut-chart/donut-chart.component.html, docs/app/pages/charts/sections/flot-options/flot-options-ng1/flot-options-ng1.component.html, docs/app/pages/charts/sections/line-charts/line-chart/line-chart.component.html, docs/app/pages/charts/sections/line-charts/multiple-axis-line-chart/multiple-axis-line-chart.component.html, docs/app/pages/charts/sections/line-charts/stacked-line-chart/stacked-line-chart.component.html, docs/app/pages/charts/sections/live-charts/live-chart/live-chart.component.html, docs/app/pages/charts/sections/scrollable-chart/scrollable-chart/scrollable-chart.component.html, docs/app/pages/components/sections/input-controls/tags/tags.component.html, docs/app/pages/components/sections/keyboard/keyboard-service-ng1/keyboard-service-ng1.component.html, docs/app/pages/components/sections/panels/item-display-panel-service-ng1/item-display-panel-service-ng1.component.html, docs/app/pages/components/sections/scrollbar/infinite-scroll/infinite-scroll.component.html, docs/app/pages/components/sections/scrollbar/virtual-scroll/virtual-scroll.component.html, docs/app/pages/components/sections/select/multiple-select-table-ng1/multiple-select-table-ng1.component.html, docs/app/pages/components/sections/select/select-ng1/select-ng1.component.html, docs/app/pages/components/sections/select/select/select.component.html, docs/app/pages/components/sections/tables/column-sorting/column-sorting.component.html, docs/app/pages/components/sections/tables/filters/filters.component.html, docs/app/pages/components/sections/tables/multiple-column-sorting-ng1/multiple-column-sorting-ng1.component.html, docs/app/pages/components/sections/tables/single-column-sorting-ng1/single-column-sorting-ng1.component.html, docs/app/pages/components/sections/tooltips/static-tooltip-ng1/static-tooltip-ng1.component.html, docs/app/pages/components/sections/tree-view/tree-grid-ng1/tree-grid-ng1.component.html, docs/app/pages/components/sections/wizard/wizard/wizard.component.html, docs/styles.less
- Jira: https://jira.autonomy.com/browse/EL-2812
- This change updates the line spacing in the documentation so that it is consistent within tables
=> S 70/el 2812 tree grid

docs/app/pages/css/sections/color-palette/color-palette/color-palette.component.html
https://jira.autonomy.com/browse/EL-2832
=> Updated hex and rgb values for "OK" status color

LICENSE.md, docs/app/components/page-footer/page-footer.component.html, docs/app/components/page-footer/page-footer.component.less, docs/app/data/footer-navigation.json, docs/app/pages/licenses/licenses.component.html, docs/app/showcase/list_view/dist/documents/PreviewPDF.html, docs/app/showcase/list_view/src/assets/documents/PreviewPDF.html, grunt/usebanner.js
https://jira.autonomy.com/browse/EL-2837
=> EL-2837 - Updating copyright

src/components/date-time-picker/date-time-picker.component.ts, src/components/date-time-picker/date-time-picker.config.ts, src/components/date-time-picker/date-time-picker.module.ts, src/components/date-time-picker/index.ts
Using a service to store default values - this will allow a team to set their own default values once and it be applied to ever date picker in the whole application by default
=> EL-2805 - Date Picker Enhancement

docs/app/data/iconset.json, src/icons/chevron-down.svg, src/icons/chevron-left.svg, src/icons/chevron-right.svg, src/icons/chevron-up.svg, src/ng1/directives/treeView/treeView.partial.html, src/ng1/directives/treegrid/treegrid.controller.js, src/styles/tree-views.less
Added new icons and used new icons on tree view and tree grid
=> EL-2805 - Updating Icons on tree grid and tree view

src/components/tag-input/tag-input.component.html, src/components/tag-input/tag-input.component.ts
https://jira.autonomy.com/browse/EL-2838
=> Removed getTagClass wrapper function

docs/app/pages/components/sections/buttons/dropdown-ng1/snippets/dropdown.html, docs/app/pages/components/sections/buttons/dropdown-ng1/wrapper/dropdown-wrapper.directive.html, docs/app/pages/css/sections/buttons/button-dropdowns/button-dropdowns.component.html, docs/app/pages/css/sections/buttons/circular-icon-buttons/circular-icon-buttons.component.html, docs/app/pages/css/sections/buttons/circular-icon-buttons/snippets/sample.html, docs/app/pages/css/sections/buttons/colored-buttons/colored-buttons.component.html, docs/app/pages/css/sections/buttons/colored-buttons/snippets/sample.html, docs/app/pages/css/sections/buttons/link-buttons/link-buttons.component.html, docs/app/pages/css/sections/buttons/link-buttons/snippets/sample.html, docs/app/pages/css/sections/buttons/size-variations/size-variations.component.html, docs/app/pages/css/sections/buttons/size-variations/snippets/code.example.html, docs/app/pages/css/sections/buttons/size-variations/snippets/iconOnly.html, docs/app/pages/css/sections/buttons/size-variations/snippets/textIconSample.html, docs/app/pages/css/sections/buttons/size-variations/snippets/textSample.html, docs/app/pages/css/sections/buttons/split-button-dropdowns/split-button-dropdowns.component.html, docs/styles.less, src/styles/buttons.less
- Jira: https://jira.autonomy.com/browse/EL-2821
- Updated buttons to use the same spacing as on EverythingUX, and to use a flex layout to address the additional white space between inline elements.
=> MF-Theme-Feedback-09-10 - Updated spacing between buttons

docs/app/services/codepen/codepen.service.ts, src/ng1/external/ng-tags-input/ng-tags-input.js
https://jira.autonomy.com/browse/EL-2838
=> Added polyfill library to codepen references

src/ng1/external/ng-tags-input/ng-tags-input.js
Apologies for this omission and delaying the release.
https://jira.autonomy.com/browse/EL-2838?focusedCommentId=1997982&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1997982
=> Fixed an error where tagClass was not specified

src/ng1/directives/dynamicSelect/dynamicSelect.controller.js
Added an explicit dirty status for programmatic population of single select text field.
I hope I understand the request correctly in that it was the input field that needed the status.
https://jira.autonomy.com/browse/EL-2834
=> Dirty status for single select

docs/app/components/api-properties/api-properties.component.html, docs/app/components/api-properties/api-properties.component.less, docs/app/components/api-properties/api-properties.component.ts, docs/app/components/api-property/api-property.component.html, docs/app/components/api-property/api-property.component.less, docs/app/components/api-property/api-property.component.ts, docs/app/components/components.module.ts, docs/app/pages/components/sections/dashboard/dashboard/dashboard.component.html
Added components for api properties, have used this on the dashboards page for now, the rest will be added when this has been approved so I wont have to redo everything if something needs changed.
https://jira.autonomy.com/browse/EL-2813
=> EL-2813 - Api Properties

configs/webpack.docs.dev.config.js, configs/webpack.docs.prod.config.js, package.json
=> Including img and fonts in build

docs/app/services/app-configuration/app-configuration.service.ts, docs/polyfills.ts, package.json
These changes should fix the issues you were having Chris
=> Fixing issues with plunker

src/ng1/services/notificationService/notification.service.js, src/styles/notifications.less
JIRA: https://jira.autonomy.com/browse/EL-2873
Making the entry and exit of notifications animated - now much less jumpy
=> Making notification movement animated

buildscripts/buildRelease.sh
Versions containing "rc" will be tagged "next".
https://jira.autonomy.com/browse/EL-2862
=> Set npm tag as "latest" or "next"

docs/app/pages/components/components-sections/buttons/radio-buttons/radio-buttons.component.html, docs/app/pages/components/components-sections/buttons/toggle-buttons/toggle-buttons.component.html
Add classes to a couple of components to allow targeting of the components by CSS in ux-aspects-micro-focus.
=> EL-2867 Micro Focus Style guide updates 01/11

docs/app/pages/components/components-sections/search/search-builder/snippets/search-component-config.ts, docs/app/pages/components/components-sections/search/search-builder/snippets/search-component.ts, docs/app/pages/css/css-sections/progress/mini-activity-indicator/mini-activity-indicator.component.less, docs/app/pages/css/css-sections/progress/mini-activity-indicator/mini-activity-indicator.component.ts, src/components/checkbox/checkbox.component.less, src/components/date-time-picker/time-view/time-view.component.less, src/components/search-builder/search-builder.module.ts, src/components/search-builder/search-components/base-search.component.ts
Fixing linting issues, a few minor styling issues and making search builder basesearchcomponent AOT compatible
=> EL-2863 - Fixing Build

docs/app/pages/components/components-sections/search/search-builder/search-builder.component.html, docs/app/pages/components/components-sections/search/search-builder/search-builder.component.ts, docs/app/pages/components/components-sections/search/search-builder/snippets/app.ts
Jira: https://jira.autonomy.com/browse/EL-2861
Fixing typos and preventing save when clicking on modal backdrop
=> Search Builder - Fixing QA feedback

tsconfig.json
Removing preserveWhitespaces option as this removed some white space that is wanted, eg, tree view custom nodes
=> Removing preserveWhitespaces

docs/app/services/app-configuration/app-configuration.service.ts, docs/environments/environment.ts
Also moved version into the environment object.
https://jira.autonomy.com/browse/EL-2840
=> Added setConfigurationTemplateData for use in MF docs

docs/app/pages/getting-started/getting-started.component.html
- Jira: https://jira.autonomy.com/browse/EL-2856.
- Made QA change to update wording in a sentence.
=> EL-2856 - Getting Started Reorgaization - change after QA feedback

docs/app/services/plunker/plunker.service.ts
Jira: https://jira.autonomy.com/browse/EL-2824
- Fixes the Plunker issue caused by EL-2824-Rebrand-Components-P1
=> Plunker Fix

configs/webpack.e2e.config.js, e2e/pages/app/app.module.ts, e2e/pages/polyfills.ts, e2e/pages/vendor.ts, e2e/tests/components/tree-grid/tree-grid.e2e-spec.ts, e2e/tsconfig-app.json
Made some performance optimizations and fixed the tree grid tests
=> EL-2891 - Tree grid test fixes

docs/app/pages/components/components-sections/splitter/side-inset-panel-splitter-ng1/side-inset-panel-splitter-ng1.component.html, src/ng1/directives/splitter/splitter.directive.js, src/styles/buttons.less
https://jira.autonomy.com/browse/EL-2886
Quantum styles to follow.
=> EL-2886 - Adding ability to disable the toggle button on the side inset splitter

docs/app/pages/charts/charts-sections/spark-charts/spark-chart-ng1/snippets/chart.html, docs/app/pages/charts/charts-sections/spark-charts/spark-chart-ng1/snippets/chart.js, docs/app/pages/charts/charts-sections/spark-charts/spark-chart-ng1/snippets/tooltips.html, docs/app/pages/charts/charts-sections/spark-charts/spark-chart-ng1/spark-chart-ng1.component.html, docs/app/pages/charts/charts-sections/spark-charts/spark-charts/snippets/app.ts, docs/app/services/codepen/codepen.service.ts, docs/app/wrappers/components/spark-chart.component.ts, src/components/spark/spark.component.html, src/components/spark/spark.component.less, src/components/spark/spark.component.ts, src/ng1/directives/spark/spark.controller.js, src/ng1/directives/spark/spark.directive.js, src/ng1/directives/spark/spark.html, src/ng1/services/colorService/colorService.service.js, src/ng1/wrappers/spark/spark.directive.js, src/services/color/color.service.ts, src/styles/charts.less
- Jira: https://jira.autonomy.com/browse/EL-2824
- Added support to allow bar, track and theme to be set by specifying colors from the color palette.
- Tidied up some of the spark chart documentation
=> S 72/el 2824 spark charts

docs/app/pages/charts/charts-sections/spark-charts/spark-chart-ng1/spark-chart-ng1.component.html, docs/app/pages/charts/charts-sections/spark-charts/spark-charts/spark-charts.component.html
Jira: https://jira.autonomy.com/browse/EL-2824
- Fixing typos.
=> Spark chart typos

package.json
Include docs/app/wrappers in @ux-aspects/ux-aspects-docs package.
=> EL-2885 Make the login components available and add documentation

docs/app/pages/components/components-sections/search/search-builder/search-builder.component.html
Fixing some typos spotted in QA
=> Search builder - Fixing typos

e2e/pages/app/app.module.ts, e2e/pages/app/search-builder/search-builder.testpage.component.html, e2e/pages/app/search-builder/search-builder.testpage.component.ts, e2e/tests/components/search-builder/search-builder.e2e-spec.ts, e2e/tests/components/search-builder/search-builder.po.spec.ts
Adding some tests for the search builder
=> EL-2887 - Adding tests for search builder

src/styles/buttons.less
https://jira.autonomy.com/browse/EL-2880
Updated btn-container to use margin left
=> Making changes to btn-container

src/ng1/services/colorService/colorService.service.js, src/services/color/color.service.ts, src/styles/breadcrumbs.less, src/styles/timeline.less, src/styles/tree-views.less
Jira: https://jira.autonomy.com/browse/EL-2899
Updating icons to use mixins as they kept becoming wrong any time our icon set changed.
Also fixed a bug in our colour services that was causing spark charts to appear the wrong colour.
=> EL-2899 - UX Feedback for S-73

docs/app/pages/components/components-sections/tables/fixed-header-table-ng1/snippets/app.js, docs/app/services/navigation/navigation.service.ts
Fixing issue with fixed header table example - snippet was using arrow function when this doesn't work in CodePen - now using regular function.
Also fixing issue where page was not always scrolled to top when changing sections. Now adding use of documentElement to ensure the page is scrolled to top.
=> EL-2895 - Fixing QA issues

bower.json, docs/app/pages/changelog/changelog.component.ts, docs/app/pages/changelog/logs/release-v1.5.2.md, package.json, src/package.json
https://jira.autonomy.com/browse/EL-2901
=> Update for 1.5.2

CONTRIBUTING.md, guides/angular-optimization-guide.md, guides/developer-standard.md
Adding contributing guide, updating some of our other guides to make sure they are up to date,
Let me know if you have any suggestions about the content of the guide.
=> EL-2900 - Contributing Guide

src/ng1/directives/draggableCards/draggableCards.directive.js
Draggable card scroll pane would not get updated when additional cards were added. Now reinitialising the scroll pane when cards have changed
=> EL-2910 - Fixing draggable cards issue

docs/app/components/landing-page-feature/landing-page-feature.component.less, docs/app/data/landing-page.json
Related MF PR: https://github.houston.softwaregrp.net/caf/ux-aspects-micro-focus/pull/114
=> EL-2647 - Fixing landing page icon sizes and removing mention of bower

src/ng1/directives/dateTimePicker/dateTimePickerPopup.directive.js
https://jira.autonomy.com/browse/EL-2908
=> Fixed ng1 date/time picker to allow dynamic update of placement

src/ng1/directives/infiniteScroll/infiniteScroll.controller.js
When reloading multiple pages of data, the directive was setting the loading state to false after a single request had completed, even if there were multiple requests outstanding.
Now the loading state is determined on whether or not all requests have completed
=> EL-2904 - Infinite scroll fix

src/ng1/directives/infiniteScroll/adapters/scroll-pane.adapter.js
If you pull down this branch, run npm start and go to the codepen and make those changes to add the reset button. Hopefully now it will only load the one page.
=> Fixing infinite scroll issue

src/ng1/services/colorService/colorService.service.js
Fixing themeColor related protractor test issues
=> Adding missing functions to color service

docs/app/pages/components/components-sections/buttons/floating-action-button-ng1/snippets/floating-action-button.html, docs/app/pages/components/components-sections/buttons/floating-action-button-ng1/wrapper/floating-action-button-wrapper.directive.html
This accounts for the removal of default button margins in the MF theme.
https://jira.autonomy.com/browse/EL-2918
=> Added margin to the floating action button examples

src/ng1/directives/fixedHeaderTable/fixed-header-table.controller.js, src/ng1/directives/fixedHeaderTable/fixed-header-table.module.js
This should now prevent the Angular loaded twice error
=> EL-2938 - Removing unneeded angular imports

ng-package.json, src/hybrid/components/organization-chart/organization-chart.component.ts, src/hybrid/components/partition-map/partition-map.component.ts, src/hybrid/components/peity-chart/peity-bar-chart.component.ts, src/hybrid/components/peity-chart/peity-line-chart.component.ts, src/hybrid/components/peity-chart/peity-pie-chart.component.ts, src/hybrid/components/peity-chart/peity-updating-line-chart.component.ts, src/hybrid/components/sankey-chart/sankey.component.ts, src/hybrid/components/search-toolbar/search-toolbar.component.ts, src/hybrid/components/select-table/select-table.component.ts, src/hybrid/components/social-chart/social-chart.component.ts, src/hybrid/components/tree-grid/tree-grid.component.ts, src/hybrid/index.ts, src/package.json
Adding external to ng-packagr config
=> Wrappers - Fixing build issue

src/components/slider/slider.component.less, src/styles/slider.less
Fixing that slider bug that Roland mentioned
=> EL-2937 - Improving slider tick alignment

guides/angular-upgrade-guide.md
Updating the Upgrade guide to use the latest Upgrade Module and simplifying the guide and the upgrade process.
=> EL-2894 - Angular Upgrade Guide

docs/app/pages/components/components-sections/flippable-cards/flippable-cards/flippable-cards.component.html, docs/app/pages/components/components-sections/flippable-cards/flippable-cards/flippable-cards.component.ts, src/components/select/select.component.ts, src/directives/resize/resize.service.ts, src/ng1/directives/infiniteScroll/infiniteScroll.controller.js
- Fixing IE10 select error
- Fixing flippable card images
- Adding safety checks to infinite scrollbar
=> EL-2983, EL-2982 & EL-2953

docs/app/pages/components/components-sections/flippable-cards/flippable-cards-ng1/snippets/app.css, docs/app/pages/components/components-sections/flippable-cards/flippable-cards-ng1/snippets/app.html, docs/app/pages/components/components-sections/flippable-cards/flippable-cards-ng1/wrapper/flippable-cards-wrapper.directive.html, docs/app/pages/components/components-sections/flippable-cards/flippable-cards/flippable-cards.component.html, docs/app/pages/components/components-sections/flippable-cards/flippable-cards/snippets/app.css, docs/app/pages/components/components-sections/flippable-cards/flippable-cards/snippets/app.html, docs/styles.less, src/styles/cards.less
JIRA: https://jira.autonomy.com/browse/EL-2953
Updating flippable cards to more closely resembled Rolands new mockup (attached in jira).
Fixed up several styling and documentation issues
=> EL-2953 - Flippable Cards

docs/app/data/components-page.json, docs/app/pages/components/components-sections/wizard/marquee-wizard/marquee-wizard.component.html, docs/app/pages/components/components-sections/wizard/marquee-wizard/marquee-wizard.component.ts, docs/app/pages/components/components-sections/wizard/wizard.module.ts
Added documentation proposal for the marquee wizard migration.
We can simply extend the WizardComponent and WizardStepComponent classes and add any additional functionality required avoiding a lot of code duplication. Because of this the inputs and outputs are largely identical.
=> EL-2557 - Marquee Wizard Proposal

src/ng1/directives/marqueeWizard/marqueeWizard.controller.js, src/ng1/directives/marqueeWizard/marqueeWizard.directive.js, src/ng1/directives/marqueeWizard/marqueeWizard.html, src/ng1/directives/marqueeWizard/marqueeWizardStep.directive.js
Restructured the AngularJS marquee wizard to work with Upgrade Tool
=> EL-2961 - Reworking AngularJS Marquee wizard to support hybrid module wrapper

docs/app/pages/components/components-sections/wizard/marquee-wizard/marquee-wizard.component.html
Adding in Roland's new description
=> EL-2557 - Marquee Wizard Documentation

src/hybrid/index.ts
Exporting interfaces for AngularJS upgraded services
=> EL-2959 - AngularJS Upgraded Services Interfaces

bower.json, docs/app/pages/changelog/changelog.component.ts, docs/app/pages/changelog/logs/release-v1.5.5.md, package.json, src/package.json
Preparing for release.
https://jira.autonomy.com/browse/EL-3019
=> Release 1.5.5

src/components/dashboard/dashboard.component.less, src/components/dashboard/dashboard.service.ts, src/components/dashboard/drag-handle/drag-handle.directive.ts, src/components/dashboard/widget/dashboard-widget.component.ts, src/directives/drag/drag.directive.ts
My lint plugins for vs code crashed so some minor linting issues crept in without me noticing. Here are the fixes for them
=> Fixing some linting errors

docs/app/pages/components/components-sections/timeline/timeline/snippets/app.ts, docs/app/pages/components/components-sections/timeline/timeline/timeline.component.html, e2e/pages/app/app.module.ts, e2e/pages/app/timeline/timeline.module.ts, e2e/pages/app/timeline/timeline.testpage.component.html, e2e/pages/app/timeline/timeline.testpage.component.ts, e2e/tests/components/common/common.spec.ts, e2e/tests/components/timeline/timeline.e2e-spec.ts, e2e/tests/components/timeline/timeline.po.spec.ts
=> EL-2941 Added code snippets and Plunker link.

buildscripts/buildRelease.sh, buildscripts/buildTheme.sh, buildscripts/executeContinuousIntegrationTasks.sh, buildscripts/executeUnitTests.sh, buildscripts/executeUnitTestsDocker.sh, buildscripts/functions.sh, buildscripts/updateConfigJSON.sh, buildscripts/updateSEPGRepository.sh
Removed --force switch from grunt commands.
Deleted remnants of themed builds once they are no longer needed.
Creating @ux-aspects/ux-aspects and @ux-aspects/ux-aspects-docs NPM packages as tarballs and uploading the tarballs to repository branches for testing. No longer attempting to publish the @ux-aspects/ux-aspects package.
Recording exit code after important operations. If failure detected, the exit code is displayed and the process is stopped.
Prepending comments with '===' string to aid following commands in a large console file.
https://jira.autonomy.com/browse/EL-2992
=> EL-2992 Removed --force switch from grunt commands.

docs/app/pages/components/components-sections/timeline/timeline/snippets/app.ts
Updating path in timeline plunker
=> Fixing timeline plunker

buildscripts/buildRelease.sh, buildscripts/buildTheme.sh, buildscripts/updateConfigJSON.sh, buildscripts/updateSEPGRepository.sh, buildscripts/updateVersionNumbers.sh
Don't exit script immediately upon an error. Allow error code to be recorded and displayed.
https://jira.autonomy.com/browse/EL-2992
=> EL-2992 Correct errors in UXAspects release build

docs/app/pages/components/components-sections/scrollbar/infinite-scroll/infinite-scroll.component.html, src/directives/infinite-scroll/infinite-scroll.directive.ts
Added similar implementation from the AngularJS enhancement.
Updated documentation.
Protractor tests to follow (probably next sprint).
https://jira.autonomy.com/browse/EL-2924
=> EL-2924 - Infinite Scroll (Angular) page reload functionality

src/components/navigation/navigation-item/navigation-item.component.ts
https://jira.autonomy.com/browse/EL-2897
=> Creating UrlTree to determine if link is active.

docs/polyfills.ts, package.json
Add import of package to polyfills.ts.
=> Install web-animations-js package.

grunt/stylelint.js
=> Ignoring fonts and variables

docs/app/components/api-properties/api-properties.component.ts, docs/app/components/api-property/api-property.component.ts, docs/app/pages/components/components-sections/buttons/floating-action-button-ng1/floating-action-button-ng1.component.html, docs/app/pages/components/components-sections/buttons/floating-action-button-ng1/floating-action-button-ng1.component.ts, src/hybrid/components/floating-action-button/floating-action-button.component.ts, src/ng1/directives/floatingActionButton/floatingActionButton.directive.js, src/ng1/directives/floatingActionButton/floatingActionButton.html
- Allow adding tooltips to floating action buttons
- Change our API tables to use OnPush change detection for performance improvements
=> EL-3028 - Adding tooltip to floating action buttons

docs/app/pages/components/components-sections/notifications/notifications-ng1/wrapper/notifications-wrapper.directive.html, docs/app/pages/components/components-sections/notifications/notifications-ng1/wrapper/notifications-wrapper.directive.ts, docs/app/pages/components/components-sections/notifications/notifications/notifications.component.html, docs/app/pages/components/components-sections/notifications/notifications/snippets/app.html, docs/app/wrappers/examples/notifications/notifications.component.ts, src/ng1/services/notificationService/notification.service.js
Remove unused 'band' element.
Allow title of 'Background Color' field to be changed.
https://jira.autonomy.com/browse/EL-3000
=> EL-3000 Change colour of icon if 'iconColor' value is defined.

src/components/floating-action-buttons/floating-action-button.component.less
Removing empty line that caused linting to fail
=> Fixing linting issue

docs/app/pages/components/components-sections/buttons/floating-action-button/floating-action-button.component.html, docs/app/pages/components/components-sections/buttons/floating-action-button/snippets/app.html, package-lock.json, package.json
* Fixed a documentation typo.
* Updated ngx-bootstrap to release version, which corrects the tooltip issue.
* Updated code snippet.
=> Floating Action Button QA feedback

src/components/floating-action-buttons/floating-action-buttons.component.ts, src/components/floating-action-buttons/floating-action-buttons.module.ts
Jira: https://jira.autonomy.com/browse/EL-3034
Add a check to ensure that any tooltips will get closed whenever the floating action button closes.
=> El 3034 fab tooltip fixes

bower.json, docs/app/pages/changelog/changelog.component.ts, docs/app/pages/changelog/logs/release-v1.5.7.md, package-lock.json, package.json, src/package.json
https://jira.autonomy.com/browse/EL-3030
=> Release 1.5.7

docs/app/pages/changelog/changelog.component.ts, docs/app/pages/changelog/logs/release-v1.5.8.md, package-lock.json, package.json, src/package.json
Links to be added as part of the relevant tickets.
=> Release notes for 1.5.8

docs/app/components/component-section/component-section.component.html, docs/app/components/component-section/component-section.component.ts, docs/app/components/documentation-category/documentation-category.component.html, docs/app/data/components-page.json, docs/app/interfaces/ISection.ts, docs/app/pages/components/components-sections/search/search.module.ts, docs/app/pages/components/components-sections/search/toolbar-search/snippets/app.html, docs/app/pages/components/components-sections/search/toolbar-search/toolbar-search.component.html, docs/app/pages/components/components-sections/search/toolbar-search/toolbar-search.component.ts, docs/app/services/navigation/navigation.service.ts
Also added a link from the ng1 Search Toolbar section, to avoid confusion due to the name change.
=> Initial documentation for Toolbar Search

e2e/pages/app/app.module.ts, e2e/pages/app/reorderable-table/reorderable-table.module.ts, e2e/pages/app/reorderable-table/reorderable-table.testpage.component.html, e2e/pages/app/reorderable-table/reorderable-table.testpage.component.ts, e2e/tests/components/reorderable-table/reorderable-table.e2e-spec.ts, e2e/tests/components/reorderable-table/reorderable-table.po.spec.ts, src/directives/reorderable/reorderable.directive.ts
- Adding protractor tests for reorderable table
- Fixing issue with ng-packagr when importing the dragula library
=> EL-2974 - Reorderable Table Tests

docs/app/pages/components/components-sections/search/toolbar-search/snippets/app.html, docs/app/pages/components/components-sections/search/toolbar-search/snippets/app.ts, docs/app/pages/components/components-sections/search/toolbar-search/toolbar-search.component.html, docs/app/pages/components/components-sections/search/toolbar-search/toolbar-search.component.ts, src/components/toolbar-search/toolbar-search.component.less
Adjusted animation for right-aligned button.
Changed search behavior for right-aligned component.
Changed tooltip for right-aligned button.
=> Toolbar Search feedback

docs/app/pages/components/components-sections/search/toolbar-search/snippets/app.html, docs/app/pages/components/components-sections/search/toolbar-search/toolbar-search.component.html, src/components/toolbar-search/toolbar-search-button.directive.ts, src/components/toolbar-search/toolbar-search-field.directive.ts, src/components/toolbar-search/toolbar-search.component.less, src/components/toolbar-search/toolbar-search.component.ts
https://jira.autonomy.com/browse/EL-3026
=> EL-3026 - Toolbar Search MF brand updates

configs/webpack.e2e.config.js, e2e/pages/app/app.module.ts, e2e/pages/app/floating-action-buttons/floating-action-buttons.module.ts, e2e/pages/app/toolbar-search/toolbar-search.module.ts, e2e/pages/app/toolbar-search/toolbar-search.testpage.component.html, e2e/pages/app/toolbar-search/toolbar-search.testpage.component.less, e2e/pages/app/toolbar-search/toolbar-search.testpage.component.ts, e2e/protractor.config.js, e2e/tests/components/toolbar-search/toolbar-search.e2e-spec.ts, e2e/tests/components/toolbar-search/toolbar-search.po.spec.ts
Also removed optimization steps from the e2e site for a faster build.
Removed a rogue debugger statement.
Fixed the chromedriver path.
https://jira.autonomy.com/browse/EL-3025
=> Added toolbar search e2e tests

docs/app/pages/components/components-sections/search/toolbar-search/toolbar-search.component.ts
https://jira.autonomy.com/browse/EL-3025
=> Added ColorServiceModule to toolbar search plunker

docs/app/pages/changelog/logs/release-v1.5.8.md
Added links to the changelog.
https://jira.autonomy.com/browse/EL-3031
=> Release 1.5.8

src/components/checkbox/checkbox.component.ts, src/components/radiobutton/radiobutton.component.ts, src/components/tag-input/tag-input.component.ts, src/components/toggleswitch/toggleswitch.component.ts
JIRA: https://jira.autonomy.com/browse/EL-3089
Adding missing disabled state code.
The following plunker can be used to test that this functionality is working
https://plnkr.co/edit/t7tEyQtNakslPrGzehbl?p=preview
=> EL-3089 - Adding the missing setDisabledState functions

src/data/micro-focus-colors.json, src/ng1/services/colorService/colorService.service.js, src/services/color/color.service.ts
Also added "forest green" to the ng1 color service, as it had previously been omitted.
https://jira.autonomy.com/browse/EL-2748
=> Fixed an issue with getColor and multi-word color names

src/directives/selection/selection-item.directive.ts
Added in missing getter which prevented the selected class from being added
=> EL-2967 - Selection fix

docs/app/data/components-page.json, docs/app/pages/components/components-sections/component-list/component-list.module.ts, docs/app/pages/components/components-sections/component-list/component-list/component-list.component.html, docs/app/pages/components/components-sections/component-list/component-list/component-list.component.ts, docs/app/pages/components/components-sections/component-list/component-list/snippets/app.html, docs/app/pages/components/components-sections/component-list/component-list/snippets/app.ts, src/ng1/directives/componentList/componentList.html, src/styles/component-list.less
JIRA: https://jira.autonomy.com/browse/EL-2963
- Added component list documentation example using Reactive forms.
- Deprecated old component list section
- Tidied up AngularJS Component List styles so we could reuse them in the Angular example
=> Adding component list example

docs/app/data/components-page.json, docs/app/pages/components/components-sections/input-controls/input-controls.module.ts, docs/app/pages/components/components-sections/input-controls/input-mask/input-mask.component.html, docs/app/pages/components/components-sections/input-controls/input-mask/input-mask.component.ts, docs/app/pages/components/components-sections/input-controls/input-mask/snippets/app.html, docs/app/pages/components/components-sections/input-controls/input-mask/snippets/app.ts, docs/app/services/plunker/templates/config_js.txt, package-lock.json, package.json, src/package.json
JIRA: https://jira.autonomy.com/browse/EL-2971
Adding example of input mask that uses ngx-mask external directive. Added plunker example.
No e2e tests required as this is an external component.
=> EL-2971 - Adding input mask documentation section

src/components/side-panel/side-panel.component.ts
https://jira.autonomy.com/browse/EL-2972
=> Added missing event argument in ux-side-panel

docs/app/data/components-page.json, docs/app/pages/components/components-sections/draggable-cards/draggable-cards.module.ts, docs/app/pages/components/components-sections/draggable-cards/draggable-cards/draggable-cards.component.html, docs/app/pages/components/components-sections/draggable-cards/draggable-cards/draggable-cards.component.less, docs/app/pages/components/components-sections/draggable-cards/draggable-cards/draggable-cards.component.ts, docs/app/pages/components/components-sections/draggable-cards/draggable-cards/snippets/app.css, docs/app/pages/components/components-sections/draggable-cards/draggable-cards/snippets/app.html, docs/app/pages/components/components-sections/draggable-cards/draggable-cards/snippets/app.ts, package-lock.json, package.json, src/directives/reorderable/reorderable.directive.ts, src/package.json, src/styles/cards.less
https://jira.autonomy.com/browse/EL-2964
=> EL-2964 - Draggable Cards

bower.json, docs/app/pages/changelog/changelog.component.ts, docs/app/pages/changelog/logs/release-v1.5.10.md, docs/app/pages/changelog/logs/release-v1.5.11.md, package.json, src/package.json
- Adding changelog entry for v1.5.11
- Updating package.json
- Updating bower.json
- Removing notice about Angular 6 upgrade (due to Angular 6 release being delayed wasn't able to bring this ticket into S-82)
=> EL-3121 - Release Preparations

docs/app/pages/components/components-sections/hierarchy-bar/hierarchy-bar.module.ts, docs/app/pages/components/components-sections/hierarchy-bar/hierarchy-bar/hierarchy-bar.component.html, docs/app/pages/components/components-sections/hierarchy-bar/hierarchy-bar/hierarchy-bar.component.less, docs/app/pages/components/components-sections/hierarchy-bar/hierarchy-bar/hierarchy-bar.component.ts, docs/app/pages/components/components-sections/hierarchy-bar/hierarchy-bar/snippets/app.css, docs/app/pages/components/components-sections/hierarchy-bar/hierarchy-bar/snippets/app.html, docs/app/pages/components/components-sections/hierarchy-bar/hierarchy-bar/snippets/app.ts, src/components/hierarchy-bar/hierarchy-bar.component.html, src/components/hierarchy-bar/hierarchy-bar.component.less, src/components/hierarchy-bar/hierarchy-bar.component.ts, src/components/hierarchy-bar/hierarchy-bar.module.ts, src/components/hierarchy-bar/hierarchy-bar.service.ts, src/components/hierarchy-bar/index.ts, src/directives/focus-if/focus-if.directive.ts, src/index.ts, src/styles/ux-aspects.less
JIRA: https://jira.autonomy.com/browse/EL-2942
Adding hierarchy bar implementation. Tests will be added in a separate PR
=> EL-2942 - Hierarchy Bar Implementation

docs/app/pages/components/components-sections/notifications/notifications/notifications.component.html, docs/app/pages/components/components-sections/notifications/notifications/notifications.component.ts, docs/app/pages/components/components-sections/notifications/notifications/snippets/app.html, docs/app/pages/components/components-sections/notifications/notifications/snippets/app.ts, src/components/notification/notification-list.component.html, src/components/notification/notification.service.ts
- Added option to supply notification with data
- Updated documentation
- Updated example to have the description provided in the custom data
- Updated sample code and plunker
- Was going to add a test to cover this but it appears there are not yet any tests for notifications
=> EL-3095 - Notification Improvements

docs/app/pages/changelog/logs/release-v1.5.12.md
https://jira.autonomy.com/browse/EL-3127
=> Updated changelog for 1.5.12 release

docs/app/data/components-page.json, docs/app/data/css-page.json, docs/app/pages/components/components-sections/input-controls/float-label/float-label.component.html, docs/app/pages/components/components-sections/input-controls/float-label/float-label.component.ts, docs/app/pages/components/components-sections/input-controls/float-label/snippets/app.html, docs/app/pages/components/components-sections/input-controls/float-label/snippets/app.ts, docs/app/pages/components/components-sections/input-controls/input-controls.module.ts, src/directives/float-label/float-label.directive.ts, src/directives/float-label/float-label.module.ts, src/directives/float-label/index.ts, src/index.ts, src/styles/controls.less
All new styles were added for this directive in order to avoid the extra structural parent element.
Protractor tests to be added following code review.
https://jira.autonomy.com/browse/EL-3113
=> EL-3113 - float label

docs/app/pages/components/components-sections/input-controls/float-label/float-label.component.ts, e2e/pages/app/app.module.ts, e2e/pages/app/float-label/float-label.module.ts, e2e/pages/app/float-label/float-label.testpage.component.html, e2e/pages/app/float-label/float-label.testpage.component.ts, e2e/tests/components/float-label/float-label.e2e-spec.ts, e2e/tests/components/float-label/float-label.po.spec.ts, src/directives/float-label/float-label.directive.ts
https://jira.autonomy.com/browse/EL-3113
=> Float label tests

docs/app/pages/components/components-sections/input-controls/float-label/float-label.component.html, docs/app/pages/components/components-sections/input-controls/float-label/snippets/app.html, e2e/pages/app/float-label/float-label.testpage.component.html, e2e/pages/app/float-label/float-label.testpage.component.ts, e2e/tests/components/float-label/float-label.e2e-spec.ts, e2e/tests/components/float-label/float-label.po.spec.ts, src/directives/float-label/float-label.directive.ts
Fixed the following issues:
* Not raised when initial value set via FormBuilder.
* Not raised when value is bound and mode = focus and input cleared via keyboard.
https://jira.autonomy.com/browse/EL-3113
=> EL-3147 - float label value binding

src/components/page-header/icon-menu/icon-menu.component.ts, src/components/page-header/page-header.component.html
* Added tabindex and keydown support to secondary tabs.
* Fixed an issue with icon menu not opening on first click.
https://jira.autonomy.com/browse/EL-3060
=> EL-3060 - Fixed issues found in MF masthead

docs/app/pages/components/components-sections/tree-view/tree-view-custom-node/snippets/app.snippet.html, docs/app/pages/components/components-sections/tree-view/tree-view-custom-node/tree-view-custom-node.component.html
=> Tree View - Fixing build issue

docs/app/pages/components/components-sections/tabs/tabs/tabs.component.ts
=> EL-3150 - Tabset - Adding missing dependency to plunker

docs/styles.less, src/components/popover/popover.directive.ts, src/components/tooltip/index.ts, src/components/tooltip/tooltip.directive.ts, src/components/tooltip/tooltip.module.ts, src/components/tooltip/tooltip.service.ts
Fixing QA Issues.
Related PRs: https://github.houston.softwaregrp.net/caf/quantum/pull/479 & https://github.houston.softwaregrp.net/caf/ux-aspects-micro-focus/pull/210
=> EL-3126-Bootstrap-QA-Fixes

bower.json, docs/app/pages/changelog/changelog.component.ts, docs/app/pages/changelog/logs/release-v1.5.14.md, package-lock.json, package.json, src/package.json
https://jira.autonomy.com/browse/EL-3169
=> Release 1.5.14

docs/app/pages/changelog/logs/release-v1.5.15.md
https://jira.autonomy.com/browse/EL-3173
=> Added dynamic facet change to the release notes

src/ng1/directives/socialChart/socialChart.controller.js
With 2 nodes it is possible to end up with a call to animate with no nodes. This can cause the chart to lose visible content. To avoid this situation I have added code for this edge case to ensure that at least one node is animated.
The original repro codepen (modified to use localhost):
https://codepen.io/donnamarijne/pen/OEZGoJ
https://jira.autonomy.com/browse/EL-3151
=> Fix for rendering issue with a 2-node chart

e2e/tests/components/page-header/page-header.e2e-spec.ts, src/components/page-header/navigation/navigation-item/navigation-item.component.ts, src/components/page-header/navigation/navigation-secondary-item/navigation-secondary-item.directive.ts, src/components/page-header/page-header.component.html, src/components/page-header/page-header.component.ts, src/components/page-header/page-header.module.ts, src/components/page-header/page-header.service.ts
Changed the behavior of the select$ observable so that it does not trigger itself via selectedRoot$. This caused issues with this request because the final value of selected$ was the parent rather than the child.
Also updated a test which was invalidated by this request.
https://jira.autonomy.com/browse/EL-3168
=> Masthead selection improvements

bower.json, docs/app/pages/changelog/changelog.component.ts, docs/app/pages/changelog/logs/release-v1.5.16.md, docs/app/services/plunker/templates/config_js.txt, package-lock.json, package.json, src/package.json
Also changed the rxjs entry point for plunker.
https://jira.autonomy.com/browse/EL-3182
=> EL-3182 - release 1.5.16

src/components/date-time-picker/date-time-picker.component.less
The date picker classes were not scoped correctly causing class conflicts with the calendar
=> EL-3142 - Fixing Date Picker style scoping

docs/app/pages/components/components-sections/dashboard/dashboard/dashboard.component.html, src/components/dashboard/drag-handle/drag-handle.directive.ts, src/directives/drag/drag.directive.ts
Adding disabled property to dashboard drag handle
=> EL-3123 - Dashboard Drag Handle

src/ng1/directives/multipleSelect/multipleSelect.provider.js, src/ng1/directives/treegrid/treegrid.controller.js
https://jira.autonomy.com/browse/EL-3181
=> Fixed jshint errors

docs/app/pages/components/components-sections/tables/column-sorting/column-sorting.component.html, docs/app/pages/components/components-sections/tables/column-sorting/column-sorting.component.ts, docs/app/pages/components/components-sections/tables/column-sorting/snippets/app.html, docs/app/pages/components/components-sections/tables/column-sorting/snippets/app.ts, docs/app/pages/components/components-sections/tables/tables.module.ts, src/components/column-sorting/column-sorting.component.html, src/components/column-sorting/column-sorting.component.less, src/components/column-sorting/column-sorting.component.ts, src/components/column-sorting/column-sorting.directive.ts, src/directives/observers/overflow/overflow-observer.directive.ts, src/styles/utilities.less
JIRA: https://jira.autonomy.com/browse/EL-3175
Updated the Column Sorting component and example to have keyboard accessibility and screen reader support.
=> EL-3175 - Column Sorting

src/components/column-sorting/column-sorting.component.html
=> Fixing build

docs/app/pages/components/components-sections/tables/column-sorting/column-sorting.component.html, docs/app/pages/components/components-sections/tables/column-sorting/column-sorting.component.ts, docs/app/pages/components/components-sections/tables/column-sorting/snippets/app.html, docs/app/pages/components/components-sections/tables/column-sorting/snippets/app.ts
Fixing sorting issue where sorting did not work on second column
=> EL-3175 - Column Sorting Fix

docs/app/pages/components/components-sections/flippable-cards/flippable-cards/flippable-cards.component.html, docs/app/pages/components/components-sections/flippable-cards/flippable-cards/flippable-cards.component.ts
Fixing missing icon on flippable cards
=> EL-3051 - Flippable Card Icon Fix

docs/app/pages/components/components-sections/facets/facet-typeahead-list/facet-typeahead-list.component.html, docs/app/pages/components/components-sections/facets/facet-typeahead-list/facet-typeahead-list.component.ts, docs/app/pages/components/components-sections/facets/facet-typeahead-list/snippets/app.html, docs/app/pages/components/components-sections/facets/facet-typeahead-list/snippets/app.ts, docs/app/pages/components/components-sections/tables/column-sorting/column-sorting.component.ts, docs/app/pages/components/components-sections/tables/column-sorting/snippets/app.ts, src/components/facets/base/facet-base/facet-base.component.ts, src/components/facets/base/facet-header/facet-header.component.ts, src/components/facets/facet-check-list/check-list-item/facet-check-list-item.component.html, src/components/facets/facet-check-list/check-list-item/facet-check-list-item.component.ts, src/components/facets/facet-check-list/facet-check-list.component.html, src/components/facets/facet-check-list/facet-check-list.component.less, src/components/facets/facet-check-list/facet-check-list.component.ts, src/components/facets/facet-container.component.html, src/components/facets/facet-container.component.less, src/components/facets/facet-container.component.ts, src/components/facets/facet-typeahead-list/facet-typeahead-list.component.html, src/components/facets/facet-typeahead-list/facet-typeahead-list.component.less, src/components/facets/facet-typeahead-list/facet-typeahead-list.component.ts, src/components/facets/facet-typeahead-list/typeahead-list-item/facet-typeahead-list-item.component.html, src/components/facets/facet-typeahead-list/typeahead-list-item/facet-typeahead-list-item.component.ts, src/components/facets/facets.module.ts, src/components/tabset/tabset.module.ts, src/components/typeahead/typeahead-key.service.ts, src/components/typeahead/typeahead.component.html, src/components/typeahead/typeahead.component.ts
JIRA: https://jira.autonomy.com/browse/EL-3049
Adding accessibility to facets
=> EL-3049 - WCAG Facets

docs/app/pages/components/components-sections/help-center/help-center/help-center.component.ts
Adding aria label to help center menu item
=> EL-3053 - Help Center Aria Label

src/ng1/directives/treegrid/treegrid.controller.js
=> Fixing JSHint error

src/components/facets/facet-check-list/facet-check-list.component.html, src/components/facets/facet-check-list/facet-check-list.component.ts, src/components/facets/facet-container.component.less, src/components/facets/facet-typeahead-list/facet-typeahead-list.component.html, src/components/facets/facet-typeahead-list/facet-typeahead-list.component.ts, src/components/facets/facet-typeahead-list/typeahead-list-item/facet-typeahead-list-item.component.html, src/components/facets/facet-typeahead-list/typeahead-list-item/facet-typeahead-list-item.component.ts
=> EL-3049 - Fixing WCAG Facet Issues

src/components/filters/filter-container.component.less, src/components/filters/filter.module.ts
=> EL-3176 - Filter QA Fixes

package-lock.json, package.json, src/directives/resize/resize.directive.ts, src/directives/resize/resize.service.ts, src/ng-package.json, src/package.json
JIRA: https://jira.autonomy.com/browse/EL-3191
Updated the resize service to use the build in browser ResizeObserver. Also added polyfill for when the ResizeObserver is not supported (it no longer polls to check for size changes).
=> EL-3191 - Resize Service

guides/angular-update-guide.md
Adding steps to update guide to provide a fix for the module not found error
=> EL-3102 - Updating Update Guide

guides/angular-upgrade-guide.md
- Making a few minor changes to account for Webpack 4
- Changing selectors to use the recommended `app` prefix
- Fixing some indentation errors
=> EL-3102 - Updating Angular Upgrade Guide

docs/app/services/plunker/plunker.service.ts, docs/app/services/plunker/templates/config_js.txt
Related PR: https://github.houston.softwaregrp.net/caf/ux-aspects-micro-focus/pull/243
Making the plunker config programmatically extensible by the MF docs site
=> EL-3178 - MF Docs Plunker Support

docs/app/pages/components/components-sections/keyboard/hotkeys/hotkeys.component.html, docs/app/pages/components/components-sections/keyboard/hotkeys/hotkeys.component.ts, docs/app/pages/components/components-sections/keyboard/hotkeys/snippets/app.html, docs/app/pages/components/components-sections/keyboard/hotkeys/snippets/app.ts, docs/app/pages/components/components-sections/keyboard/keyboard.module.ts
- Added role="group" to the button groups
- Aria Labels on the hotkey regions and buttons
- Removed redundant 'btn' classes
- Removed redundant keydown events as click fires these anyway
- Added LiveAnnouncer when item is selected
- Updated sample code/plunker
=> EL-3056 - WCAG Keyboard Selection

src/components/media-player/extensions/controls/controls.component.html, src/directives/accessibility/tabbable-list/tabbable-list.directive.ts
Subtitle button should now receive focus again when using keyboard
=> EL-3057 - Media Player QA fix

src/ng1/directives/marqueeWizard/marqueeWizard.controller.js
- Update the buttons any time the steps change
- Added some teardown logic that was missing
=> EL-3210 - Marquee Wizard Fix

docs/app/pages/components/components-sections/tables/selection/selection.component.html, docs/app/pages/components/components-sections/tree-view/tree-grid-ng1/tree-grid-ng1.component.html
- Adding missing classes to accordion panels
=> EL-3194 - Fix Accordion Styles

docs/app/pages/components/components-sections/notifications/notifications.module.ts, docs/app/pages/components/components-sections/notifications/notifications/notifications.component.html, docs/app/pages/components/components-sections/notifications/notifications/notifications.component.ts, docs/app/pages/components/components-sections/notifications/notifications/snippets/app.html, docs/app/pages/components/components-sections/notifications/notifications/snippets/app.ts, src/components/notification/notification-list.component.less
Improving the notifications example to be more accessible
=> EL-3059 - WCAG Notifications

docs/app/pages/components/components-sections/drag-and-drop/drag-and-drop-cards/drag-and-drop-cards.component.html, docs/app/pages/components/components-sections/drag-and-drop/drag-and-drop-cards/drag-and-drop-cards.component.ts, docs/app/pages/components/components-sections/drag-and-drop/drag-and-drop-cards/snippets/app.html, docs/app/pages/components/components-sections/drag-and-drop/drag-and-drop-cards/snippets/app.ts, docs/app/pages/components/components-sections/drag-and-drop/drag-and-drop.module.ts, docs/app/pages/components/components-sections/drag-and-drop/draggable-cards/draggable-cards.component.html, docs/app/pages/components/components-sections/drag-and-drop/draggable-cards/draggable-cards.component.less, docs/app/pages/components/components-sections/drag-and-drop/draggable-cards/draggable-cards.component.ts, docs/app/pages/components/components-sections/drag-and-drop/draggable-cards/snippets/app.css, docs/app/pages/components/components-sections/drag-and-drop/draggable-cards/snippets/app.html, docs/app/pages/components/components-sections/drag-and-drop/draggable-cards/snippets/app.ts, src/components/media-player/extensions/controls/controls.component.html, src/components/media-player/media-player.component.html, src/directives/accessibility/focus-within/focus-within.directive.ts, src/directives/accessibility/tabbable-list/tabbable-list-item.directive.ts, src/directives/accessibility/tabbable-list/tabbable-list.directive.ts, src/directives/accessibility/tabbable-list/tabbable-list.service.ts, src/styles/cards.less
Making draggable cards and drag and drop card sections more accessible.
=> EL-3047 - WCAG Drag and Drop

docs/app/pages/components/components-sections/progress/progress-bar/progress-bar.component.html, src/components/progress-bar/progress-bar.component.html, src/components/progress-bar/progress-bar.component.ts
WCAG Progress Bar improvements: https://jira.autonomy.com/browse/EL-3063
=> EL-3063 - WCAG Progress Bar

docs/app/pages/components/components-sections/drag-and-drop/drag-and-drop-cards/drag-and-drop-cards.component.less, docs/app/pages/components/components-sections/drag-and-drop/drag-and-drop-cards/snippets/app.css
=> EL-3047 -Drag and Drop Card Outline

bower.json, docs/app/pages/changelog/changelog.component.ts, docs/app/pages/changelog/logs/release-v1.6.1.md, package-lock.json, package.json, src/package.json
https://jira.autonomy.com/browse/EL-3185
=> Release 1.6.1

docs/app/pages/components/components-sections/scrollbar/infinite-scroll/infinite-scroll.component.html, docs/app/pages/components/components-sections/scrollbar/infinite-scroll/infinite-scroll.component.ts, docs/app/pages/components/components-sections/scrollbar/infinite-scroll/snippets/app.html, docs/app/pages/components/components-sections/scrollbar/infinite-scroll/snippets/app.ts, docs/app/pages/components/components-sections/scrollbar/infinite-scroll/snippets/loadMore.snippet.html, docs/app/pages/components/components-sections/scrollbar/scrollbar.module.ts, docs/app/pages/components/components-sections/scrollbar/virtual-scroll/snippets/app.html, docs/app/pages/components/components-sections/scrollbar/virtual-scroll/snippets/app.ts, docs/app/pages/components/components-sections/scrollbar/virtual-scroll/virtual-scroll.component.html, docs/app/pages/components/components-sections/scrollbar/virtual-scroll/virtual-scroll.component.ts, docs/styles.less
https://jira.autonomy.com/browse/EL-3064
=> EL-3064 - WCAG scrollbar

docs/app/pages/components/components-sections/progress/progress-bar-ng1/progress-bar-ng1.component.html, docs/app/pages/components/components-sections/progress/progress-bar/progress-bar.component.html, docs/app/pages/components/components-sections/progress/progress.module.ts, src/styles/navigation.less
* Corrected the text slightly.
* Switched example code tabset to accessible version.
https://jira.autonomy.com/browse/EL-3063
=> WCAG Progress

docs/app/pages/components/components-sections/search/search-builder/search-builder.component.ts, docs/app/pages/components/components-sections/search/search-builder/snippets/app.ts, src/components/color-picker/color-picker.module.ts, src/components/page-header/navigation/navigation-item/navigation-item.component.ts, src/components/page-header/navigation/navigation.component.ts, src/components/page-header/page-header.component.html, src/components/page-header/page-header.module.ts, src/components/page-header/page-header.service.ts
* Added `routerLink` and `routerExtras` to PageHeaderNavigationItem.
* Fixed some production build warnings/errors.
https://jira.autonomy.com/browse/EL-3215
=> EL-3215 - Masthead routerLinks

docs/app/pages/components/components-sections/color/color-picker/color-picker.component.html, docs/app/pages/components/components-sections/color/color-picker/color-picker.component.ts, docs/app/pages/components/components-sections/color/color-picker/snippets/app.html, docs/app/pages/components/components-sections/color/color-picker/snippets/app.ts
https://jira.autonomy.com/browse/EL-3207
=> EL-3207 - Added click-off behavior to the color picker demo

bower.json, docs/app/pages/changelog/changelog.component.ts, docs/app/pages/changelog/logs/release-v1.6.2.md, package-lock.json, package.json, src/package.json
https://jira.autonomy.com/browse/EL-3186
=> Release 1.6.2

src/components/page-header/page-header.service.ts
If there is further navigation beneath the masthead then this fix will be required to do an inexact route match on the masthead items if no exact match is found.
=> Enabled inexact matching for masthead items

docs/app/pages/components/components-sections/search/search-builder/search-builder.component.ts
https://jira.autonomy.com/browse/EL-3065
=> WCAG search - added missing modules to the plunker

src/components/search-builder/search-builder-group/search-builder-group.component.less
* Added focus outline to the add field and remove field buttons.
https://jira.autonomy.com/browse/EL-3065
=> EL-3065 - WCAG search corrections

docs/app/data/components-page.json, docs/app/pages/components/components-sections/tables/column-resizing/column-resizing.component.html, docs/app/pages/components/components-sections/tables/column-resizing/column-resizing.component.less, docs/app/pages/components/components-sections/tables/column-resizing/column-resizing.component.ts, docs/app/pages/components/components-sections/tables/column-resizing/snippets/app.css, docs/app/pages/components/components-sections/tables/column-resizing/snippets/app.html, docs/app/pages/components/components-sections/tables/column-resizing/snippets/app.ts, docs/app/pages/components/components-sections/tables/tables.module.ts, src/components/table/index.ts, src/components/table/table-column-resize/resizable-table-column.component.html, src/components/table/table-column-resize/resizable-table-column.component.less, src/components/table/table-column-resize/resizable-table-column.component.ts, src/components/table/table-column-resize/resizable-table.directive.ts, src/components/table/table-column-resize/resizable-table.service.ts, src/components/table/table.module.ts, src/index.ts, src/styles/ux-aspects.less
- Adding directive to allow table columns to be resized
=> EL-3217 - Table Column Resize

src/common/index.ts, src/common/operators/index.ts, src/common/operators/tick.operator.ts, src/components/navigation/navigation-link/navigation-link.directive.ts, src/components/table/table-column-resize/resizable-table-column.component.ts, src/index.ts
Fixing the expression changed after check issue. I have made an RxJS operator to allow us to use request animation frame in a pipeable way as this seems to be something we are having to do on a frequent basis.
=> EL-3217 - Table Resize Expression Fix

docs/app/pages/components/components-sections/wizard/marquee-wizard-ng1/marquee-wizard-ng1.component.html, src/ng1/directives/marqueeWizard/marqueeWizard.controller.js
JIRA: https://jira.autonomy.com/browse/EL-3230
All the marquee wizard on-finishing function to return a promise.
=> EL-3230 - Marquee Wizard Promise

docs/app/pages/components/components-sections/wizard/marquee-wizard-ng1/marquee-wizard-ng1.component.html, docs/app/pages/components/components-sections/wizard/wizard.module.ts, src/ng1/directives/marqueeWizard/marqueeWizard.controller.js, src/ng1/directives/marqueeWizard/marqueeWizard.html
Added a function which is called on each step change, this can override the default visibility of each of the three buttons.
https://jira.autonomy.com/browse/EL-3216
=> EL-3216 - allow finish button to appear on any step

src/components/navigation/navigation.component.html, src/directives/accessibility/tabbable-list/tabbable-list-item.directive.ts, src/directives/accessibility/tabbable-list/tabbable-list.service.ts
Made the current expanded state available to the service; this should resolve the issue.
https://jira.autonomy.com/browse/EL-3067
=> Fixing QA issue

bower.json, docs/app/pages/changelog/changelog.component.ts, docs/app/pages/changelog/logs/release-v1.6.3.md, package-lock.json, package.json, src/package.json
https://jira.autonomy.com/browse/EL-3187
=> Release 1.6.3

src/ng1/directives/dynamicSelect/dynamicSelect.controller.js, src/ng1/directives/dynamicSelect/dynamicSelect.html, src/ng1/directives/infiniteScroll/infiniteScroll.controller.js
Previously, when the select component loaded it was constantly checking if the infinite scroll needed to load another page, even when the dropdown was not visible causing the function to be called over and over again.
Reworked component to be simpler, more performant and added some additional cleanup logic to correctly destroy watchers
=> EL-3220 - Make dynamic select component much more performant

src/components/tag-input/tag-input.component.ts
Using the new tick() rxjs operator to prevent any expression has changed errors
=> EL-3299 - Tag Input Expression Error

docs/app/pages/components/components-sections/timeline/timeline/snippets/app.html, docs/app/pages/components/components-sections/timeline/timeline/timeline.component.html, src/components/timeline/timeline-event/timeline-event.component.html, src/components/timeline/timeline-event/timeline-event.component.ts
Added aria-described by attribute to allow the badge to be associated with the panel
=> EL-3071 - WCAG-Timeline

src/ng1/directives/marqueeWizard/marqueeWizard.controller.js
Adding check to find the first visible step rather than always showing step 0
=> EL-3240 - Marquee Wizard Hidden Steps

docs/app/pages/components/components-sections/splitter/side-inset-panel-splitter/side-inset-panel-splitter.component.ts, docs/app/pages/components/components-sections/splitter/splitter.module.ts, docs/app/pages/components/components-sections/splitter/splitter/splitter.component.html, docs/app/pages/components/components-sections/splitter/splitter/splitter.component.ts, e2e/pages/app/app.module.ts, e2e/pages/app/splitter/splitter.module.ts, e2e/pages/app/splitter/splitter.testpage.component.html, e2e/pages/app/splitter/splitter.testpage.component.less, e2e/pages/app/splitter/splitter.testpage.component.ts, e2e/tests/components/splitter/splitter.e2e-spec.ts, e2e/tests/components/splitter/splitter.po.spec.ts, src/directives/accessibility/accessibility.module.ts, src/directives/accessibility/index.ts, src/directives/accessibility/splitter/splitter-accessibility.directive.ts, src/styles/splitter.less
Adding splitter accessibility.
- Implements Splitter Accessibility directive
- Updated documentation
- Added tests to cover accessibility functionality
=> EL-3238 - Splitter Accessibility

src/ng1/directives/marqueeWizard/marqueeWizard.controller.js
Making the previous button visibility take into account hidden steps
=> EL-3240 - Marquee Wizard QA Fix

docs/app/data/components-page.json, docs/app/pages/components/components-sections/tree-view/tree-grid/snippets/app.html, docs/app/pages/components/components-sections/tree-view/tree-grid/snippets/app.ts, docs/app/pages/components/components-sections/tree-view/tree-grid/tree-grid.component.html, docs/app/pages/components/components-sections/tree-view/tree-grid/tree-grid.component.less, docs/app/pages/components/components-sections/tree-view/tree-grid/tree-grid.component.ts, docs/app/pages/components/components-sections/tree-view/tree-view.module.ts, src/directives/selection/selection-item.directive.ts, src/directives/selection/selection.directive.ts, src/directives/selection/selection.service.ts, src/directives/selection/strategies/selection.strategy.ts, src/directives/tree-grid/index.ts, src/directives/tree-grid/tree-grid-indent.directive.ts, src/directives/tree-grid/tree-grid-item.interface.ts, src/directives/tree-grid/tree-grid-load-function.type.ts, src/directives/tree-grid/tree-grid-row.directive.ts, src/directives/tree-grid/tree-grid-state.class.ts, src/directives/tree-grid/tree-grid.directive.ts, src/directives/tree-grid/tree-grid.module.ts, src/directives/tree-grid/tree-grid.service.ts, src/index.ts, src/styles/tables.less, src/styles/tree-views.less
https://autjira.microfocus.com/browse/EL-3231
=> EL-3231 - Tree grid

docs/app/pages/components/components-sections/tree-view/tree-grid/tree-grid.component.html, src/styles/tree-views.less
https://autjira.microfocus.com/browse/EL-3231
=> Additional styling changes to align header and rows in all browsers

bower.json, docs/app/pages/changelog/changelog.component.ts, docs/app/pages/changelog/logs/release-v1.6.3.md, docs/app/pages/changelog/logs/release-v1.6.4.md, package-lock.json, package.json, src/package.json
https://autjira.microfocus.com/browse/EL-3188
=> Release 1.6.4

docs/app/pages/components/components-sections/tree-view/tree-view-ng1/tree-view-ng1.component.html, docs/app/pages/components/components-sections/tree-view/tree-view-ng1/wrapper/tree-view-wrapper.directive.ts, src/ng1/directives/treeView/treeView.module.js, src/ng1/directives/treeView/treeView.partial.html, src/styles/controls.less
Added option to disable a node. Note the description mentioned about having a tooltip when disabled. There is currently an option to add a tooltip so nothing was required for this.
=> EL-3234 - Tree View Disabled Nodes

docs/app/components/component-section/component-section.component.html, docs/app/data/components-page.json, docs/app/pages/components/components-sections/utilities/focus/focus.component.html, docs/app/pages/components/components-sections/utilities/focus/focus.component.less, docs/app/pages/components/components-sections/utilities/focus/focus.component.ts, docs/app/pages/components/components-sections/utilities/focus/snippets/app.css, docs/app/pages/components/components-sections/utilities/focus/snippets/app.html, docs/app/pages/components/components-sections/utilities/focus/snippets/app.ts, docs/app/pages/components/components-sections/utilities/tabbable-list/snippets/app.css, docs/app/pages/components/components-sections/utilities/tabbable-list/snippets/app.html, docs/app/pages/components/components-sections/utilities/tabbable-list/snippets/app.ts, docs/app/pages/components/components-sections/utilities/tabbable-list/tabbable-list.component.html, docs/app/pages/components/components-sections/utilities/tabbable-list/tabbable-list.component.less, docs/app/pages/components/components-sections/utilities/tabbable-list/tabbable-list.component.ts, docs/app/pages/components/components-sections/utilities/utilities.module.ts, src/directives/accessibility/splitter/splitter-accessibility.directive.ts
Documenting the focuswithin directives and tabbable list directives
=> EL-3075 - Utilities Documentation

docs/app/pages/components/components-sections/tables/column-resizing/column-resizing.component.html, docs/app/pages/components/components-sections/tables/column-resizing/column-resizing.component.less, docs/app/pages/components/components-sections/tables/column-resizing/column-resizing.component.ts, docs/app/pages/components/components-sections/tables/column-resizing/snippets/app.css, docs/app/pages/components/components-sections/tables/column-resizing/snippets/app.html, docs/app/pages/components/components-sections/tables/column-resizing/snippets/app.ts, docs/app/pages/components/components-sections/tables/custom-responsive-table-ng1/snippets/sample.html, docs/app/pages/components/components-sections/tables/custom-responsive-table-ng1/snippets/sample.js, docs/app/pages/components/components-sections/tables/custom-responsive-table-ng1/wrapper/custom-responsive-wrapper.directive.html, docs/app/pages/components/components-sections/tables/custom-responsive-table-ng1/wrapper/custom-responsive-wrapper.directive.ts, src/components/table/index.ts, src/components/table/table-column-resize/resizable-table-cell.directive.ts, src/components/table/table-column-resize/resizable-table-column.component.html, src/components/table/table-column-resize/resizable-table-column.component.ts, src/components/table/table-column-resize/resizable-table.directive.ts, src/components/table/table-column-resize/resizable-table.service.ts, src/components/table/table.module.ts
- Making the column resizing work with uxFixedHeaderTable.
- Refactored existing code to make it simpler
- An additional directive is required when using is with a fixed header table - added documentation to include this.
- Fixed an issue with the custom responsive table example which produced an error in the console.
=> EL-3242 - Table Column Resize

src/components/checkbox/checkbox.component.less
Fixing the IE styling issue. I tried to use the tree grid styles, however there is some flex styling on the table cells which don't work when used with the fixed header table as it also uses flex
=> EL-3242 - Column Resizing IE Fix

src/components/wizard/wizard.component.html
=> Fixing wizard typo causing build issue

docs/app/data/iconset.json, src/icons/zoom-out.svg
=> EL-3256 - Zoom Out Icon

src/components/hierarchy-bar/hierarchy-bar.component.html, src/components/hierarchy-bar/hierarchy-bar.module.ts
Making hierarchy bar dropdown navigation work with arrow keys
=> EL-3054 - Hierarchy Bar WCAG

docs/app/pages/components/components-sections/wizard/marquee-wizard/marquee-wizard.component.html, docs/app/pages/components/components-sections/wizard/marquee-wizard/snippets/app.html, src/components/marquee-wizard/marquee-wizard.component.html
Related PRs: https://github.houston.softwaregrp.net/caf/ux-aspects-micro-focus/pull/286 & https://github.houston.softwaregrp.net/caf/quantum/pull/567
Fixing issues found during QA
=> EL-3076 - Marquee Wizard QA Fixes

docs/app/pages/components/components-sections/tables/hover-actions-ng1/hover-actions-ng1.component.html, src/ng1/directives/hoverActions/hoverAction.directive.js, src/styles/controls.less
Adding option to disabled hover actions
=> EL-3255 - Hover action disabled

docs/app/pages/components/components-sections/input-controls/tags/tags.component.html, docs/app/pages/components/components-sections/select/select/select.component.html, src/components/select/select.component.html, src/components/select/select.component.ts, src/components/tag-input/tag-input.component.html, src/components/tag-input/tag-input.component.ts
Adding option to override autocomplete property on select and tag input components.
=> EL-3241 - Select autocomplete

src/components/page-header/page-header.component.html, src/components/page-header/page-header.module.ts
Using tabset for secondary navigation
=> EL-3180-Masthead-Tabset

docs/app/pages/components/components-sections/buttons/floating-action-button/floating-action-button.component.html
Adding chevron to FAB customise panel
=> EL-3257 - Adding chevron to FAB panel

docs/app/pages/components/components-sections/component-list/component-list/component-list.component.html, docs/app/pages/components/components-sections/component-list/component-list/snippets/app.html, src/styles/component-list.less
Improving WCAG support for component list
=> EL-3043 - Component List WCAG

docs/app/pages/components/components-sections/tables/column-resizing/column-resizing.component.html, docs/app/pages/components/components-sections/tables/column-resizing/column-resizing.component.ts, docs/app/pages/components/components-sections/tables/column-resizing/snippets/app.html, docs/app/pages/components/components-sections/tables/column-resizing/snippets/app.ts, src/styles/tables.less
Fixing checkboxes in column resize example
=> EL-3069 - WCAG Tables Fix

docs/app/app.module.ts, docs/app/data/components-page.json, docs/app/pages/components/components-sections/buttons/buttons.module.ts, docs/app/pages/components/components-sections/buttons/floating-action-button/floating-action-button.component.html, docs/app/pages/components/components-sections/buttons/floating-action-button/snippets/app.html, docs/app/pages/components/components-sections/buttons/pagination/pagination.component.html, docs/app/pages/components/components-sections/buttons/pagination/pagination.component.ts, docs/app/pages/components/components-sections/buttons/pagination/snippets/app.html, docs/app/pages/components/components-sections/buttons/pagination/snippets/app.ts, docs/app/pages/components/components-sections/utilities/tabbable-list/tabbable-list.component.html, src/components/floating-action-buttons/floating-action-button.component.html, src/components/floating-action-buttons/floating-action-button.component.ts, src/components/floating-action-buttons/floating-action-buttons.component.html, src/components/floating-action-buttons/floating-action-buttons.component.ts, src/components/floating-action-buttons/floating-action-buttons.service.ts, src/components/pagination/index.ts, src/components/pagination/pagination.component.html, src/components/pagination/pagination.component.less, src/components/pagination/pagination.component.ts, src/components/pagination/pagination.module.ts, src/directives/accessibility/tabbable-list/tabbable-list.directive.ts, src/directives/accessibility/tabbable-list/tabbable-list.service.ts, src/index.ts, src/styles/utilities.less, src/styles/ux-aspects.less
- New Pagination Control that is now accessible
- Update FAB component to be keyboard accessible
=> EL-3042 - Buttons WCAG

src/components/floating-action-buttons/floating-action-button.component.ts
=> Fixing Import

bower.json, docs/app/pages/changelog/changelog.component.ts, docs/app/pages/changelog/logs/release-v1.6.7.md, package-lock.json, package.json, src/package.json
https://autjira.microfocus.com/browse/EL-3276
=> Updated to 1.6.7

docs/app/pages/components/components-sections/buttons/split-button-dropdowns/split-button-dropdowns.component.html
Fixing link. Related PR: https://github.houston.softwaregrp.net/caf/ux-aspects-micro-focus/pull/293
=> EL-3286 - Fixing Broken Link

docs/app/pages/components/components-sections/dashboard/dashboard/dashboard.component.less, docs/app/pages/components/components-sections/dashboard/dashboard/snippets/app.css, src/components/dashboard/widget/dashboard-widget.component.less
Moving offset code to the documentation styles and making grab movement and resizing animated
=> EL-3232 - Dashboard Improvements

src/components/dashboard/grab-handle/grab-handle.directive.ts
Fixing error announcement issue
=> EL-3232 - Fixing dashboard announcements

bower.json, docs/app/pages/changelog/changelog.component.ts, docs/app/pages/changelog/logs/release-v1.6.8.md, package-lock.json, package.json, pom.xml, src/package.json
https://autjira.microfocus.com/browse/EL-3292
=> Release 1.6.8

src/icons/gallery-filled.svg, src/icons/image-filled.svg, src/icons/pin-filled.svg, src/icons/trash-filled.svg, src/icons/trophy-filled.svg
Updating the filled icons with Rolands latest revision
=> EL-3284 - Updating broken icons

docs/app/data/components-page.json, docs/app/pages/components/components-sections/color/color-picker/color-picker.component.ts, docs/app/pages/components/components-sections/tables/fixed-header-table/fixed-header-table.component.html, docs/app/pages/components/components-sections/tables/fixed-header-table/fixed-header-table.component.ts, docs/app/pages/components/components-sections/tables/fixed-header-table/snippets/app.html, docs/app/pages/components/components-sections/tables/fixed-header-table/snippets/app.ts, src/components/color-picker/color-picker-color.ts, src/components/color-picker/color-picker.component.ts, src/components/color-picker/index.ts, src/directives/fixed-header-table/fixed-header-table.directive.ts
- Exposing the setLayout function
- Making the directive accessible via exportAs
- Adding dataset input that can be used to trigger this setLayout automatically when the dataset changes
- Updating documentation
- Updated example code
=> EL-3288 - Fixed Header Table Layout Update

docs/app/pages/components/components-sections/facets/custom-facet-component/custom-facet-component.component.html, docs/app/pages/components/components-sections/facets/custom-facet-component/custom-facet-component.component.ts
Documenting the `FacetService` observables and `FacetEvent`s.
=> EL-3294 - Custom Facet Documentation

docs/app/pages/components/components-sections/facets/facet-container/facet-container.component.html, docs/app/pages/components/components-sections/facets/facet-container/snippets/custom-button.snippet.html, src/components/facets/facet-clear-button/facet-clear-button.directive.ts, src/components/facets/facet-container.component.html, src/components/facets/facet-container.component.ts, src/components/facets/facets.module.ts, src/components/facets/index.ts
Related: https://github.houston.softwaregrp.net/caf/ux-aspects-micro-focus/pull/304 & https://github.houston.softwaregrp.net/caf/quantum/pull/588
Adding option to customise the clear all button
=> EL-3287 - Facet Improvements

docs/styles.less
https://autjira.microfocus.com/browse/EL-3265
=> Fixed abbr element style

configs/webpack.docs.prod.config.js, docs/app/pages/components/components-sections/tables/column-resizing/column-resizing.component.ts, docs/app/pages/components/components-sections/tables/column-resizing/snippets/app.ts, src/components/table/table-column-resize/resizable-table-cell.directive.ts, src/components/table/table-column-resize/resizable-table-column.component.ts, src/components/table/table-column-resize/resizable-table.directive.ts, src/components/table/table-column-resize/resizable-table.service.ts
Columns that are dynamically added or removed did not correctly update the layout. Should now work as expected.
Note, I also made a change to the docs production webpack config after noticing some messages being logged in the Jenkins console output. It appears that Babel is processing the `.ngfactory.js` files produced by the Angular AOT build and also the compiled Angular library in dist folder. I have excluded these files to ensure it they don't get processed (speeds up the build by ~16s).
https://autjira.microfocus.com/browse/EL-3313
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3313-Column-Resizing
https://plnkr.co/edit/pXcDc2gI1JvvAmkdGgOP?p=preview
=> EL-3313 - Column Resizing Improvements

src/components/select/select.component.ts
Related PR: https://github.houston.softwaregrp.net/caf/quantum/pull/597 & https://github.houston.softwaregrp.net/caf/ux-aspects-micro-focus/pull/313
Adding new selectors to the select component
https://autjira.microfocus.com/browse/EL-2997
Not Applicable
=> EL-2997 - Select Updates

.github/PULL_REQUEST_TEMPLATE.md, docs/app/pages/changelog/changelog.component.ts, docs/app/pages/changelog/logs/release-v1.7.1.md, docs/app/pages/getting-started/getting-started.component.html
* Removed bower section from Getting Started.
* Added install step for CDK.
* Removed top header from the PR template.
https://autjira.microfocus.com/browse/EL-3332
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3332-release-1.7.1 (not sure if Jenkins is working properly atm)
=> Release 1.7.1

release-notes-1.7.1.md
Making release ready.
https://autjira.microfocus.com/browse/EL-3332
n/a
=> Release 1.7.1 part 2

docs/app/pages/components/components-sections/tree-view/tree-grid-ng1/tree-grid-ng1.component.html, src/ng1/directives/infiniteScroll/infiniteScroll.controller.js, src/ng1/directives/treegrid/selection/multiple-select-bridge.js, src/ng1/directives/treegrid/selection/tree-grid-selection-model.js, src/ng1/directives/treegrid/treegrid.controller.js, src/ng1/directives/treegrid/treegrid.html, src/ng1/directives/treegrid/treegridMultipleSelectItem.directive.js
- Fixing Tree Grid programmatic selection issue
- Fixing Tree Grid losing state on expand/collapse
- Fixing Tree Grid indeterminate state not set on disabled row
- Fixing infinite scroll reset
- https://autjira.microfocus.com/browse/EL-3340
- https://autjira.microfocus.com/browse/EL-3359
- https://autjira.microfocus.com/browse/EL-3360
- https://autjira.microfocus.com/browse/EL-3362
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3340-Tree-Grid-Selection-2
=> El 3340 tree grid selection 2

docs/app/pages/changelog/changelog.component.ts, docs/app/pages/changelog/logs/release-v1.7.2.md, release-notes-1.7.2.md, src/directives/fixed-header-table/fixed-header-table.directive.ts
https://autjira.microfocus.com/browse/EL-3363
=> EL-3363 - Fixed Header Table Fix

src/components/card-tabs/card-tabset/card-tabset.component.html, src/components/date-time-picker/date-time-picker.component.html, src/components/date-time-picker/day-view/day-view.component.html, src/components/date-time-picker/header/header.component.html, src/components/date-time-picker/month-view/month-view.component.html, src/components/date-time-picker/year-view/year-view.component.html, src/components/facets/facet-container.component.html, src/components/filters/filter-container.component.html, src/components/floating-action-buttons/floating-action-button.component.html, src/components/hierarchy-bar/hierarchy-bar.component.html, src/components/marquee-wizard/marquee-wizard.component.html, src/components/media-player/extensions/controls/controls.component.html, src/components/page-header/navigation/navigation-item/navigation-item.component.html, src/components/page-header/page-header.component.html, src/components/spin-button/spin-button.component.html, src/components/time-picker/time-picker.component.html, src/components/wizard/wizard.component.html
Adding `type="button"` to all buttons in our components
https://autjira.microfocus.com/browse/EL-3328
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3328-Button-Types
=> EL-3328 - Button Types

docs/app/components/navigation-bar/navigation-bar.component.html, docs/app/components/navigation-bar/navigation-bar.component.less, docs/app/data/top-navigation.json, docs/app/interfaces/ILink.ts, docs/app/pages/team/team.component.html, docs/app/pages/team/team.component.less
Discussed with Roland how this should appear. He suggested adding a star icon beside the team menu item and adding a "card" to the team page with a link to the job listing.
https://autjira.microfocus.com/browse/EL-3338
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3338-Job-Link
=> EL-3338 - Job Link

package-lock.json, package.json, src/package.json
Keeping version in-sync with pom.xml.
n/a
=> Rolling version over to 1.7.4

src/components/floating-action-buttons/floating-action-buttons.service.ts
Fixing Expression Changed Error
Ticket
https://autjira.microfocus.com/browse/EL-3339
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3339-FAB-Expression-Changed
=> EL-3339-FAB-Expression-Changed-Error

docs/app/data/iconset.json, src/icons/status-information-filled.svg
Adding new icon to iconset
https://autjira.microfocus.com/browse/EL-3002
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3002-Alerts
=> El-3002 - Alerts

e2e/tests/components/select/standard/select.e2e-spec.ts, src/components/select/select.component.html, src/components/select/select.component.less, src/components/select/select.component.ts, src/components/tag-input/tag-input.component.html, src/components/tag-input/tag-input.component.ts
Related PR: https://github.houston.softwaregrp.net/caf/quantum/pull/611
Updating select component to:
- Show pointer cursor when hovering on arrow button
- Toggle dropdown open state when clicked
- Prevent select items from wrapping. Instead showing ellipsis
https://autjira.microfocus.com/browse/EL-3364
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3364-Select-Improvements
=> EL-3364 - Select Improvements

docs/app/data/components-page.json, docs/app/pages/components/components-sections/notifications/alert/alert.component.html, docs/app/pages/components/components-sections/notifications/alert/alert.component.less, docs/app/pages/components/components-sections/notifications/alert/alert.component.ts, docs/app/pages/components/components-sections/notifications/alert/snippets/app.css, docs/app/pages/components/components-sections/notifications/alert/snippets/app.html, docs/app/pages/components/components-sections/notifications/alert/snippets/app.ts, docs/app/pages/components/components-sections/notifications/notifications.module.ts, src/components/alert/alert-icon.directive.ts, src/components/alert/alert.component.html, src/components/alert/alert.component.ts, src/components/alert/alert.module.ts, src/components/alert/index.ts, src/index.ts, src/styles/notifications.less, src/styles/variables.less
Moving Alerts to open source library
https://autjira.microfocus.com/browse/EL-3002
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3002-Alerts-2
=> EL-3002 - Alerts Component

docs/app/pages/components/components-sections/wizard/marquee-wizard-ng1/marquee-wizard-ng1.component.html, docs/app/pages/components/components-sections/wizard/marquee-wizard/marquee-wizard.component.html, src/components/marquee-wizard/marquee-wizard.component.html, src/components/marquee-wizard/marquee-wizard.component.ts, src/ng1/directives/marqueeWizard/marqueeWizard.controller.js, src/ng1/directives/marqueeWizard/marqueeWizard.directive.js, src/ng1/directives/marqueeWizard/marqueeWizard.html, src/ng1/directives/marqueeWizard/marqueeWizard.module.js, src/ng1/directives/marqueeWizard/marqueeWizardSideStep.directive.js, src/ng1/directives/marqueeWizard/marqueeWizardStep.directive.js
Allow a custom template for each marquee wizard step in the side panel.
Ticket
https://autjira.microfocus.com/browse/EL-3356
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3356-Marquee-wizard-templates-2
=> EL-3356 - Marquee wizard templates

e2e/pages/app/reorderable-table/reorderable-table.testpage.component.html, e2e/tests/components/dashboard/dashboard.e2e-spec.ts, e2e/tests/components/filters/filters.e2e-spec.ts, e2e/tests/components/filters/filters.po.spec.ts, e2e/tests/components/page-header/page-header.e2e-spec.ts, e2e/tests/components/page-header/page-header.po.spec.ts, e2e/tests/components/reorderable-table/reorderable-table.e2e-spec.ts, e2e/tests/components/reorderable-table/reorderable-table.po.spec.ts, pom.xml
Fixing protractor tests. Note I have commented out one dashboard test as this appears to be a bug in the component (however I cannot reproduce it in our docs, showcase page or plunker, only in this test page). I have raised a ticket to correct this: https://autjira.microfocus.com/browse/EL-3381 after which that test can be included again.
https://autjira.microfocus.com/browse/EL-3372
N/A
=> EL-3372 - Fixing Protractor Tests

docs/app/pages/css/css-sections/buttons/link-buttons/link-buttons.component.html, docs/app/pages/css/css-sections/buttons/link-buttons/snippets/sample.html
Adding primary button to the link buttons section
https://autjira.microfocus.com/browse/EL-3283
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3283-Button-Documentation/#/landing
=> EL-3283 - Link Button Documentation Update

e2e/pages/app/focus-indicator/focus-indicator.testpage.component.ts, e2e/tests/components/hierarchy-bar/hierarchy-bar.po.spec.ts, e2e/tests/components/select/forms/select-forms.e2e-spec.ts, e2e/tests/components/select/standard/select.e2e-spec.ts, e2e/tests/components/tabs/tabs.e2e-spec.ts, e2e/tests/components/virtual-scroll/virtual-scroll.e2e-spec.ts
Fixing Protractor Issues:
- Added missing hasIndicator property
- Fixing hierarchy bar selector
- Fixing select tests as multiple selects no longer close the dropdown on selection
- Fixing tab test which was just wrong
https://autjira.microfocus.com/browse/EL-3372
N/A
=> El 3372 fixing protractor tests

docs/app/pages/changelog/changelog.component.ts, docs/app/pages/changelog/logs/release-v1.7.4.md, official-build.props
* Added release notes.
* Updated SEPG props per Tony's advice.
https://autjira.microfocus.com/browse/EL-3390
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3390-release-1.7.4
=> Release 1.7.4

package-lock.json, package.json
https://autjira.microfocus.com/browse/EL-3391
=> EL-3391 Webpack Security Fix

docs/app/pages/changelog/logs/release-v1.7.4.md, package-lock.json, package.json, src/package.json
Also fixed some missing links in the release notes. (pom.xml will be updated when Tony fixes the autorelease error.)
https://autjira.microfocus.com/browse/EL-3390
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3390-version-rollover
=> Version rollover to 1.7.5

docs/app/pages/components/components-sections/search/search-builder-ng1/search-builder-ng1.component.html, src/ng1/directives/searchBuilder/searchGroup.controller.js, src/ng1/directives/searchBuilder/searchGroup.html, src/styles/controls.less
Allowing an array of `buttonText` and `addField` to show multiple buttons in the search builder
https://autjira.microfocus.com/browse/EL-3383
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3383-Search-Builder-Buttons
=> EL-3383 - Search Builder Multiple Buttons

docs/app/pages/components/components-sections/notifications/notifications/notifications.component.html, docs/app/pages/components/components-sections/notifications/notifications/notifications.component.less, docs/app/pages/components/components-sections/notifications/notifications/snippets/app.css, docs/app/pages/components/components-sections/notifications/notifications/snippets/app.html
- Removing CSS that prevent height from growing
- Color picker close on selection
https://autjira.microfocus.com/browse/EL-3376
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3376-Dynamic-Notification-Height-QA
=> EL-3376 - Dynamic Notification Height Fixes

Gruntfile.js, e2e/protractor.config.js, e2e/tests/components/column-resizing/column-resizing.e2e-spec.ts, e2e/tests/components/hierarchy-bar/hierarchy-bar.e2e-spec.ts, official-build.props, pom.xml, src/directives/selection/selection.directive.ts
- Our selection tests were failing - turns out the event was being emitted repeatedly, so I have now added a check to only emit when it has actually changed
- Hierarchy bar had recently changed, so I have now updated the tests to reflect the new changes.
https://autjira.microfocus.com/browse/EL-3392
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3382-SEPG-Automated-Tests
=> EL-3382 - Fixing Protractor Tests

docs/app/data/components-page.json, docs/app/pages/components/components-sections/tables/column-resizing/column-resizing.component.html
Updated the usage dropdown and making documentation more concise
https://autjira.microfocus.com/browse/EL-3377
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3377-Column-Resizing-Documentation
=> EL-3377 - Column Resizing Documentation

docs/app/pages/changelog/changelog.component.ts, docs/app/pages/changelog/logs/release-v1.7.5.md
* Release notes
https://autjira.microfocus.com/browse/EL-3408
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3408-release-1.7.5
=> Release 1.7.5

package-lock.json, package.json, src/package.json
N/A
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_version-rollover-1.7.6
=> Rollover version to 1.7.6

docs/app/pages/components/components-sections/select/select-list/select-list.component.html, docs/app/pages/components/components-sections/select/select-list/select-list.component.ts, docs/app/pages/components/components-sections/select/select-list/snippets/app.ts, src/components/select-list/select-list.component.ts
Also updated documentation and examples.
https://autjira.microfocus.com/browse/EL-3400
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3400-select-list-docs
=> Changed selected property of select list to be ReadonlyArray

src/ng1/directives/overflowTooltip/singleLineOverflowTooltip.controller.js
When the text changes we now destroy any previous tooltip and create a new one.
https://autjira.microfocus.com/browse/EL-3399
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3399-Single-Line-Overflow-Tooltip
=> EL-3399 - Single Line Overflow Tooltip

docs/app/pages/components/components-sections/input-controls/tags/tags.component.html, docs/app/pages/components/components-sections/select/select/select.component.html, docs/app/pages/components/components-sections/select/select/snippets/app.html, src/components/select/select.component.html, src/components/select/select.component.ts, src/components/tag-input/tag-input.component.html, src/components/tag-input/tag-input.component.ts
* Also orrected the type of `value` on `ux-select` and updated the documentation
* Made some corrections to the Select documentation.
https://autjira.microfocus.com/browse/EL-3403
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3403-select-aria-label
=> Added ariaLabel property to ux-select and ux-tag-input

docs/app/pages/components/components-sections/tables/hover-actions/hover-actions.component.html, docs/app/pages/components/components-sections/tables/hover-actions/hover-actions.component.ts, docs/app/pages/components/components-sections/tables/hover-actions/snippets/app.html, docs/app/pages/components/components-sections/tables/hover-actions/snippets/app.ts, docs/app/pages/components/components-sections/utilities/tabbable-list/snippets/app.css, docs/app/pages/components/components-sections/utilities/tabbable-list/snippets/app.html, docs/app/pages/components/components-sections/utilities/tabbable-list/tabbable-list.component.html, docs/app/pages/components/components-sections/utilities/tabbable-list/tabbable-list.component.less, src/directives/accessibility/accessibility.module.ts, src/directives/accessibility/index.ts, src/directives/accessibility/managed-focus-container/managed-focus-container.directive.ts, src/directives/accessibility/managed-focus-container/managed-focus-container.service.ts, src/directives/accessibility/tabbable-list/tabbable-list-item.directive.ts, src/directives/hover-action/hover-action-container.directive.ts, src/directives/hover-action/hover-action.directive.ts, src/directives/hover-action/hover-action.service.ts, src/directives/selection/selection-item.directive.ts
* Created a new service to manage tabindex on child items of an element.
* Added the service into the following related directives:
- uxSelectionItem
- uxTabbableListItem
- uxHoverActionContainer
* Also created a wrapper directive `uxManagedFocusContainer` which is currently unused.
* Tests are to be added, if this technique is approved.
https://autjira.microfocus.com/browse/EL-3342
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3342-table-keyboard-navigation
=> EL-3342 - Table keyboard navigation

docs/app/pages/components/components-sections/page-header/page-header/page-header.component.html, src/components/page-header/navigation/navigation-dropdown-item/navigation-dropdown-item.component.html, src/components/page-header/navigation/navigation-dropdown-item/navigation-dropdown-item.component.ts, src/components/page-header/navigation/navigation-item/navigation-item.component.html, src/components/page-header/navigation/navigation-item/navigation-item.component.less, src/components/page-header/navigation/navigation-item/navigation-item.component.ts, src/components/page-header/navigation/navigation.component.ts, src/components/page-header/page-header.component.html, src/components/page-header/page-header.service.ts
Related PR: https://github.houston.softwaregrp.net/caf/quantum/pull/626 & https://github.houston.softwaregrp.net/caf/ux-aspects-micro-focus/pull/356
- Adding option to disabled masthead tabs
- Updating documentation
https://autjira.microfocus.com/browse/EL-3374
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3374-Disable-Masthead-Tabs
=> EL-3374 - Disable Masthead Tabs

package-lock.json, package.json, src/package.json
https://autjira.microfocus.com/browse/EL-3436
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3436-rollover-version-1.7.7
=> Rollover version to 1.7.7

src/package.json
Hopefully fixing the build issue this time..
https://autjira.microfocus.com/browse/EL-3430
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_Fixing-Build
=> EL-3430 - Timeline Chart - Fixing Build

docs/app/pages/charts/charts-sections/timeline-chart/timeline-chart/snippets/app.ts, docs/app/pages/charts/charts-sections/timeline-chart/timeline-chart/timeline-chart.component.ts
Making the timeline section reusable in the MF docs
https://autjira.microfocus.com/browse/EL-3430
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3430-Timline-Chart-Share
=> EL-3430 - Time Chart Improvements

configs/webpack.e2e.config.js, e2e/pages/app/dashboard/dashboard.module.ts, e2e/pages/app/dashboard/dashboard.testpage.component.html, e2e/pages/app/dashboard/dashboard.testpage.component.ts, e2e/tests/components/dashboard/dashboard.e2e-spec.ts, e2e/tests/components/dashboard/dashboard.po.spec.ts, src/components/dashboard/dashboard.component.ts, src/components/dashboard/grab-handle/grab-handle.directive.ts, src/components/dashboard/grab-handle/grab-handle.service.ts
* Changed from using `ContentChildren` to self-registering directives,
* Added protractor tests to verify tab behavior of grab handles.
* Reduced build log output (webpack informational output is making our jenkins logs very large).
https://autjira.microfocus.com/browse/EL-3412
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3412-dashboard-grab-handle
=> EL-3412 - Dashboard grab handle

docs/app/services/plunker/templates/config_js.txt
Specifying specific version of ng2-charts
https://autjira.microfocus.com/browse/EL-3430
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3430-Timeline-Chart-Plunker
=> EL-3430 - Timeline Chart Plunker Fix

src/ng1/directives/treegrid/treegridMultipleSelectItem.directive.js
* Click event will now set the selected state directly instead of calculating indeterminate state.
https://autjira.microfocus.com/browse/EL-3428
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3428-treegrid-indeterminate
=> EL-3428 - Tree grid toggle from indeterminate state

package-lock.json, package.json, src/package.json
=> Rollover version to 1.7.8

src/components/tabset/tabset.component.ts, src/components/tabset/tabset.service.ts
* Removed initial selection of tabs when creating.
https://autjira.microfocus.com/browse/EL-3443
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3443-masthead-redirect-loop
=> EL-3443 - Masthead redirect loop

docs/app/pages/components/components-sections/scrollbar/virtual-for/snippets/app.css, docs/app/pages/components/components-sections/scrollbar/virtual-for/virtual-for.component.less
Documentation styles were leaking and styling the input property list
https://autjira.microfocus.com/browse/EL-3442
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3442-Virtual-Scroll-QA
=> EL-3442 - Fixing Virtual Scroll Documentation

src/components/date-time-picker/day-view/day-view.component.html, src/components/date-time-picker/month-view/month-view.component.html, src/components/date-time-picker/year-view/year-view.component.html
Not showing active styling on an active date that is in the disabled range
https://autjira.microfocus.com/browse/EL-3445
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3445-Date-Picker-QA
=> EL-3445 - Date Picker QA improvements

docs/app/pages/components/components-sections/hierarchy-bar/hierarchy-bar/hierarchy-bar.component.html, src/components/hierarchy-bar/hierarchy-bar-collapsed/hierarchy-bar-collapsed.component.html, src/components/hierarchy-bar/hierarchy-bar-collapsed/hierarchy-bar-collapsed.component.less, src/components/hierarchy-bar/hierarchy-bar-collapsed/hierarchy-bar-collapsed.component.ts, src/components/hierarchy-bar/hierarchy-bar-node/hierarchy-bar-node.component.html, src/components/hierarchy-bar/hierarchy-bar-node/hierarchy-bar-node.component.less, src/components/hierarchy-bar/hierarchy-bar-standard/hierarchy-bar-standard.component.less, src/directives/accessibility/managed-focus-container/managed-focus-container.service.ts
Adding overflow checks and styling
https://autjira.microfocus.com/browse/EL-3433
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3433-Hierarchy-Bar-Small-Width
=> EL-3433 - Hierarchy Bar Small Width

docs/app/pages/css/css-sections/buttons/colored-buttons/colored-buttons.component.html, docs/app/pages/css/css-sections/buttons/colored-buttons/snippets/sample.html, src/components/page-header/navigation/navigation-item/navigation-item.component.html, src/components/page-header/navigation/navigation-item/navigation-item.component.ts, src/components/page-header/navigation/navigation.component.ts, src/components/page-header/navigation/navigation.service.ts, src/components/page-header/page-header.module.ts, src/components/select/select.component.ts, src/components/tag-input/tag-input.component.ts, src/components/typeahead/typeahead-key.service.ts, src/components/typeahead/typeahead.component.ts, src/directives/infinite-scroll/infinite-scroll.directive.ts
https://autjira.microfocus.com/browse/EL-3438
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3438-Keyboard-Focus-Issues
=> EL-3438 - Keyboard Focus Issues

src/components/hierarchy-bar/hierarchy-bar-popover-item/hierarchy-bar-popover-item.component.less
Fixing focus styling to only show on keyboard focus
https://autjira.microfocus.com/browse/EL-3433
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3433-Hierarchy-Bar-Hover
=> EL-3433 - Hierarchy Bar Focus

src/styles/buttons.less
Fixing addon focus styling
https://autjira.microfocus.com/browse/EL-2869
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-2869-Addon-Styles-QA
=> EL-2869-Addon-Styles-QA

e2e/tests/components/common/common.spec.ts, e2e/tests/components/floating-action-buttons/floating-action-buttons.e2e-spec.ts, e2e/tests/components/floating-action-buttons/floating-action-buttons.po.spec.ts
The FAB test error you encountered is caused when an element is not present in the DOM. Previously we were triggering a click but not waiting for the promise to resolve which could potentially lead to the expectation running before the click had completed.
Updated tests to use the async/await pattern for all events which should hopefully prevent test flakiness. 
N/A
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_FAB-Test-Improvements
=> Fab-Test-Improvements

package-lock.json, package.json, src/package.json
N/A
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_version-rollover-1.7.9
=> Version rollover 1.7.9

docs/app/pages/components/components-sections/scrollbar/scrollbar.module.ts, docs/app/pages/components/components-sections/scrollbar/virtual-for/snippets/app.html, docs/app/pages/components/components-sections/scrollbar/virtual-for/virtual-for.component.html, e2e/pages/app/virtual-for/virtual-for.module.ts, e2e/pages/app/virtual-for/virtual-for.testpage.component.html, e2e/tests/components/virtual-for/virtual-for.e2e-spec.ts, e2e/tests/components/virtual-for/virtual-for.po.spec.ts, src/components/virtual-scroll/virtual-for/virtual-for.component.ts, src/components/virtual-scroll/virtual-for/virtual-for.directive.ts, src/components/virtual-scroll/virtual-scroll.module.ts, src/directives/accessibility/accessibility.module.ts, src/directives/accessibility/focus-indicator/focus-indicator.ts, src/directives/accessibility/managed-focus-container/managed-focus-container.service.ts, src/directives/accessibility/tabbable-list/tabbable-list-item.directive.ts, src/directives/accessibility/tabbable-list/tabbable-list.directive.ts, src/directives/accessibility/tabbable-list/tabbable-list.service.ts
- Updated example to use tabbable list
- Updated uxVirtualFor and Tabbable List directives to work as expected
- Added tests
https://autjira.microfocus.com/browse/EL-3465
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3465-Virtual-Scroll-Tabbable
=> EL-3465 - Virtual Scroll Tabbable

CONTRIBUTING.md, README.md
* Made a few changes to clarify and include missing information in the contribution and development processes.
* Moved the build instructions from README to CONTRIBUTING.
* Removed the Bower section in README since we are no longer updating bower.
N/A
N/A (no code changes)
=> Contributing update

docs/app/pages/components/components-sections/tables/column-resizing/column-resizing.component.html, docs/app/pages/components/components-sections/tables/column-resizing/column-resizing.component.less, docs/app/pages/components/components-sections/tables/column-resizing/column-resizing.component.ts, docs/app/pages/components/components-sections/tables/column-resizing/snippets/app.html, docs/app/pages/components/components-sections/tables/column-resizing/snippets/app.ts, src/components/table/table-column-resize/resizable-table.directive.ts, src/components/table/table-column-resize/resizable-table.service.ts
=> Added setDefaultWidths function to resizable table

docs/app/pages/components/components-sections/tree-view/tree-view-ng1/tree-view-ng1.component.html, src/ng1/directives/templateOutlet/template-outlet.directive.js, src/ng1/directives/treeView/treeView.controller.js, src/ng1/directives/treeView/treeView.module.js, src/ng1/directives/treeView/treeView.partial.html
- Refactored the TreeView controller, just changed it to be a class to make it more readable
- Added option to provide a template for both icon and node content
- Updated documentation to include new `template` options
https://autjira.microfocus.com/browse/EL-3459
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3459-Tree-View-Custom-Template
=> EL-3459 - Tree View Custom Template

package-lock.json, package.json, pom.xml, release-notes-1.7.10.md, release-notes-1.7.9.md, src/package.json
https://autjira.microfocus.com/browse/EL-3473
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_rollover-version-1.7.10
=> Rollover version 1.7.10

package-lock.json, package.json, src/package.json
=> Rollover version to 1.7.11

e2e/pages/app/virtual-for/virtual-for.testpage.component.html, e2e/pages/app/virtual-for/virtual-for.testpage.component.ts, e2e/tests/components/virtual-for/virtual-for.e2e-spec.ts, e2e/tests/components/virtual-for/virtual-for.po.spec.ts, src/components/virtual-scroll/virtual-for/virtual-for.directive.ts
- Ensure the virtual rows are updated when the dataset changes
- Added test to cover sorting
Plunker showing column sorting not working before:
https://plnkr.co/edit/OcmTt7cv0JmVXoHtYfOr?p=preview
Showing after fix:
https://plnkr.co/edit/J861sDiPrZ9Gl2Emjc17?p=preview
https://portal.digitalsafe.net/browse/EL-3474
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3474-Virtual-For-Sorting
=> EL-3474 - Virtual For Sorting

docs/app/data/charts-page.json, docs/app/pages/charts/charts-sections/donut-charts/donut-charts.module.ts, docs/app/pages/charts/charts-sections/donut-charts/nested-donut-chart-ng1/nested-donut-chart-ng1.component.html, docs/app/pages/charts/charts-sections/donut-charts/nested-donut-chart-ng1/nested-donut-chart-ng1.component.ts, docs/app/pages/charts/charts-sections/donut-charts/nested-donut-chart/nested-donut-chart.component.html, docs/app/pages/charts/charts-sections/donut-charts/nested-donut-chart/nested-donut-chart.component.less, docs/app/pages/charts/charts-sections/donut-charts/nested-donut-chart/nested-donut-chart.component.ts, docs/app/pages/charts/charts-sections/donut-charts/nested-donut-chart/snippets/app.css, docs/app/pages/charts/charts-sections/donut-charts/nested-donut-chart/snippets/app.html, docs/app/pages/charts/charts-sections/donut-charts/nested-donut-chart/snippets/app.ts, src/components/nested-donut-chart/index.ts, src/components/nested-donut-chart/nested-donut-chart.component.html, src/components/nested-donut-chart/nested-donut-chart.component.less, src/components/nested-donut-chart/nested-donut-chart.component.spec.ts, src/components/nested-donut-chart/nested-donut-chart.component.ts, src/components/nested-donut-chart/nested-donut-chart.module.ts, src/components/tooltip/tooltip.component.ts, src/components/tooltip/tooltip.module.ts, src/index.ts, src/services/color/color.service.ts, src/styles/ux-aspects.less
- Added Nested Donut Chart
- Added documentation section and plunker
- Added tests
Also made a few tweaks to the tooltip component. I wanted to use a tooltip in the chart but currently the tooltip can only be launched using the tooltip directive (which cannot be applied to dynamically generated SVG elements). I have changed the tooltip component to allow properties to be set using inputs as well, so I can reuse the existing tooltip component without the directive.
https://portal.digitalsafe.net/browse/EL-3431
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3431-Nested-Donut-Chart
=> EL-3431 - Nested Donut Chart

CONTRIBUTING.md, docs/app/pages/features/features.component.html, docs/app/pages/features/features.component.less, docs/app/pages/features/features.component.ts, docs/app/pages/features/features.module.ts
Adding table of supported browsers to features page. If you have an alternative presentation in mind let me know and I can change it.
https://portal.digitalsafe.net/browse/EL-3464
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3464-Browser-Support
=> EL-3464 - Browser Support

docs/app/data/charts-page.json, docs/app/pages/charts/charts-sections/organization-chart/organization-chart.module.ts, docs/app/pages/charts/charts-sections/organization-chart/organization-chart/organization-chart.component.html, docs/app/pages/charts/charts-sections/organization-chart/organization-chart/organization-chart.component.less, docs/app/pages/charts/charts-sections/organization-chart/organization-chart/organization-chart.component.ts, docs/app/pages/charts/charts-sections/organization-chart/organization-chart/snippets/app.css, docs/app/pages/charts/charts-sections/organization-chart/organization-chart/snippets/app.html, docs/app/pages/charts/charts-sections/organization-chart/organization-chart/snippets/app.ts, src/components/hierarchy-bar/hierarchy-bar.service.ts, src/components/organization-chart/index.ts, src/components/organization-chart/organization-chart.component.html, src/components/organization-chart/organization-chart.component.less, src/components/organization-chart/organization-chart.component.ts, src/components/organization-chart/organization-chart.module.ts, src/index.ts, src/styles/ux-aspects.less
- Adding organization chart component
- Adding documentation and plunker
- Added a few additional safety checks to the hierarchy bar
https://portal.digitalsafe.net/browse/EL-3116
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3116-Organization-Chart
=> EL-3116 - Organization Chart

docs/app/pages/components/components-sections/date-time-picker/date-range-picker/date-range-picker.component.html, src/components/date-range-picker/date-range-picker.component.html, src/components/date-range-picker/date-range-picker.component.ts
- Adding input to customize the `duration` text.
https://portal.digitalsafe.net/browse/EL-3504
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3504-Date-Range-Picker-Localisation
=> EL-3504 - Date Range Picker Localization

configs/webpack.docs.dev.config.js, configs/webpack.docs.prod.config.js, configs/webpack.e2e.config.js
Similar to the changes made for the other repo, aiming to reduce the size of logfiles on the build machine.
See https://jenkins.hpeswlab.net/job/SEPG/job/UXAspects/job/UXAspects~UXAspects~reduce-log-output~CI/.
N/A
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_reduce-log-output
=> Reduce log output

src/components/side-panel/side-panel-animations.ts
Fixing the issue with Angular < 7.
N/A
N/A
=> Adding explicit type for sidePanelStateAnimation

src/plugins/chartjs/timeline/timeline-chart.module.ts
- Previously the left and right handles could be tabbed to. Now adding a tab option for the range. This is tabbed to after the left and right handles as mentioned in the ticket.
- Left, Right, Home and End keys will move the entire range accordingly
https://portal.digitalsafe.net/browse/EL-3448
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3448-Timeline-Chart-Keyboard
=> EL-3448- Timeline Chart Keyboard

src/directives/drag/drop.directive.ts
- Adding option to disable dropping an item on a drop zone
https://portal.digitalsafe.net/browse/EL-3454
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3513-Calendar-Drag-Enhancement-2
=> EL-3513 - Calendar Drag Enhancements

src/components/organization-chart/organization-chart.component.ts
- Reverting change from yesterday
https://portal.digitalsafe.net/browse/EL-3515
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3503-Organization-Chart-Fix
=> EL-3503 - Reverting Organization Change

docs/app/pages/charts/charts-sections/organization-chart/organization-chart/organization-chart.component.html, src/components/organization-chart/organization-chart.component.ts
- Adding transition end output to know when the nodes have finished animating
https://portal.digitalsafe.net/browse/EL-3503
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3503-Organization-Chart-Showcase-3
=> EL-3503 - Org Chart Transition

.github/PULL_REQUEST_TEMPLATE.md
* Added ITLS checklist.
https://portal.digitalsafe.net/browse/EL-3509
N/A
=> EL-3509 - ITLS update to PR template

docs/app/pages/charts/charts-sections/organization-chart/organization-chart/organization-chart.component.html, src/components/organization-chart/organization-chart.component.ts
https://portal.digitalsafe.net/browse/EL-3503
- Adding function to allow node to be programmatically focused
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3503-Org-Chart-QA
=> EL-3503 - Org Chart Focus

src/ng1/directives/searchBuilder/searchGroup.controller.js, src/ng1/directives/searchBuilder/searchGroup.directive.js, src/ng1/directives/searchBuilder/searchGroup.html, src/styles/controls.less
https://portal.digitalsafe.net/browse/EL-3520
* Added `read-only` which will hide the add and remove controls within the group.
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3520-search-builder-ng1-read-only
=> EL-3520 - Search Builder (AngularJS) - Disable Add/Remove

docs/app/pages/components/components-sections/date-time-picker/date-range-picker/date-range-picker.component.html
https://portal.digitalsafe.net/browse/EL-3518
Added clarification to date range picker min/max documentation.
=> EL-3518 - Date Range Picker - min and max (QA)

docs/app/pages/components/components-sections/date-time-picker/date-range-picker/date-range-picker.component.html
https://portal.digitalsafe.net/browse/EL-3518
Added seconds to the min/max documentation.
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3518-date-picker-min-max-doc2
=> EL-3518 - Date Range Picker - min and max (QA#2)

src/components/sankey-chart/sankey-chart.component.html, src/components/sankey-chart/sankey-chart.component.ts
https://portal.digitalsafe.net/browse/EL-3119
- Added support for passing colours by name from the color set
- Fixed issue with focus colour and box shadow
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_Sankey-Fix
=> EL-3119 - Sankey Chart Fix

src/ng1/directives/marqueeWizard/marqueeWizard.html, src/ng1/directives/scrollIntoViewIf/scrollIntoViewIf.directive.js, src/ng1/directives/scrollIntoViewIf/scrollIntoViewIf.module.js, src/ng1/ux-aspects-ng1.module.js
https://portal.digitalsafe.net/browse/EL-3529
* Added new directive for scrolling an element into view.
* Added the directive to the marquee wizard step list.
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3529-marquee-scroll
=> EL-3529 - Marquee Wizard (AngularJS) - scroll active step into view

src/ng1/plugins/jasny-bootstrap/jasny-bootstrap.js
https://portal.digitalsafe.net/browse/EL-3508
Added modification notice to jasny-bootstrap.
N/A
=> EL-3508 - ITLS update

package-lock.json, package.json
GitHub reported a security warning for the marked dependency.
Bumped the dependency as recommended.
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_audit-fix
=> Fixed audit warning for marked

docs/app/pages/charts/charts-sections/organization-chart/organization-chart/organization-chart.component.html, docs/app/pages/components/components-sections/tables/column-picker/column-picker.component.html, docs/app/pages/components/components-sections/tables/column-sorting/column-sorting.component.html, src/components/column-sorting/column-sorting.component.html, src/components/column-sorting/column-sorting.component.ts, src/components/column-sorting/column-sorting.directive.ts, src/components/column-sorting/column-sorting.module.ts, src/components/organization-chart/organization-chart.component.html, src/components/organization-chart/organization-chart.component.ts, src/components/table/column-picker/column-picker.component.html, src/components/table/column-picker/column-picker.component.ts
https://portal.digitalsafe.net/browse/EL-3554
Adding templating options options to the:
Column Picker: https://plnkr.co/edit/wVr9IbhDPFMgIKVYOC0c?p=preview
Column Sorting: https://plnkr.co/edit/9d968WJEOLdgs0iM5Uso?p=preview
Organization Chart: https://plnkr.co/edit/SFrQRWt6PtXxJMvY5iTz?p=preview
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3554-Template-Icons
=> EL-3554 - Icon Templates

docs/app/pages/css/css-sections/icons/ux-icons/ux-icons.component.html, docs/app/pages/css/css-sections/icons/ux-icons/ux-icons.component.ts
https://portal.digitalsafe.net/browse/EL-3512
- Detecting which site is being viewed and showing the appropriate select component variant
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3512-Icon-Dropdown-Fix-2
=> EL-3512 - Icon Dropdown Fix

docs/app/data/components-page.json, docs/app/pages/components/components-sections/buttons/dropdowns/dropdowns.component.html, docs/app/pages/components/components-sections/buttons/dropdowns/dropdowns.component.less, docs/app/pages/components/components-sections/buttons/dropdowns/snippets/app.css, docs/app/pages/components/components-sections/buttons/dropdowns/snippets/app.html, src/components/menu/menu/menu.component.html, src/components/menu/menu/menu.component.less
https://portal.digitalsafe.net/browse/EL-3543
- Updated documentation section title to match MF docs
- Set Mark As menu width to fix IE issue
- Also fixed a small animation issue when the menu placement was `top`
**Before:**
[![Image from Gyazo](https://i.gyazo.com/6fdca1aea54344ca466fd049cc670904.gif)](https://gyazo.com/6fdca1aea54344ca466fd049cc670904)
**After:**
[![Image from Gyazo](https://i.gyazo.com/c080b21d5078079c55e1cbb932b3fbe0.gif)](https://gyazo.com/c080b21d5078079c55e1cbb932b3fbe0)
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3543-Menu-Component-2
=> EL-3543 - Menu Component Fix

src/ng1/directives/fixedHeaderTable/fixed-header-table.controller.js
https://portal.digitalsafe.net/browse/EL-3584
- Scrolling to load more now works when there is a horizontal scrollbar
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-358-fixed-table-header
=> EL-3568 - Fixed table header

src/components/icon/icon.component.ts, src/directives/accessibility/focus-indicator/focus-indicator.directive.ts
https://portal.digitalsafe.net/browse/EL-3577
- Exposing a few private functions as they are required for the side menu
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3577-Side-Navigation
=> EL-3577 - Side Navigation

src/components/page-header/page-header.component.html, src/components/page-header/page-header.component.ts
https://portal.digitalsafe.net/browse/EL-3564
- Making logo focusable/clickable only when logoClick event is emitted
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3564-masthead-clickable-logo
=> masthead clickable updates

docs/app/pages/components/components-sections/input-controls/tags/snippets/app.html, docs/app/pages/components/components-sections/input-controls/tags/snippets/app.ts, docs/app/pages/components/components-sections/input-controls/tags/tags.component.html, docs/app/pages/components/components-sections/input-controls/tags/tags.component.ts
https://portal.digitalsafe.net/browse/EL-3575
1.  Changed to <code>ux-number-picker-inline</code>.
2.  Removed <code>addTagIcon</code> in custom example and plunker and fixed layout
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_tag-input-qa-updates
=> update to ux-number-picker-inline

src/ng1/directives/dynamicSelect/dynamicSelect.controller.js
https://portal.digitalsafe.net/browse/EL-3596
- Previously we were always trying to find a scrollpane and attach a mutation observer, however if the scroll option is false then there may not be a scrollpane. Added a check to ensure a scrollpane is present before attaching the mutation observer to prevent the error
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3596-Dynamic-Select-Error
=> EL-3596 - Dynamic Select Error

docs/app/components/navigation-bar/navigation-bar.component.html, docs/app/data/team-page.json, docs/app/data/top-navigation.json, docs/app/pages/team/team.component.html, package.json, src/package.json
https://portal.digitalsafe.net/browse/EL-3524
- Created a team member card for myself
- Removed hiring card
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3524-new-team-member
=> Updating Team Member Page

src/components/select/select.component.html, src/components/select/select.component.less, src/components/select/select.component.ts, src/components/tag-input/tag-input.component.html, src/components/tag-input/tag-input.component.less, src/components/tag-input/tag-input.component.ts
https://portal.digitalsafe.net/browse/EL-3608
- removed tab index on clear is disabled
- greyed out clear button when disabled
- returned focus to input when clear button is activated via keyboard
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3608-select-clear-button-follow-up
=> El 3608 select clear button follow up

e2e/tests/components/page-header/page-header.e2e-spec.ts
https://portal.digitalsafe.net/browse/EL-3620
Removed the offending tests since they are blocking progress.
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_disable-page-header-protractor-tests
=> EL-3620 - Disabled page header protractor tests

e2e/tests/components/page-header/page-header.e2e-spec.ts, e2e/tests/components/page-header/page-header.po.spec.ts
https://portal.digitalsafe.net/browse/EL-3620
Hard to diagnose properly since I was only able to reproduce it on the Jenkins environment. However it appears to be related to stale element references, so I changed the queries that can occur right after the `condensed` switch to not use the stored reference.
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3620-page-header-tests
=> EL-3620 - Page header tests

e2e/tests/components/page-header/page-header.e2e-spec.ts
https://portal.digitalsafe.net/browse/EL-3620
- Page header tests have been disabled we should re-enable them to verify EL-3620
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_enabling-page-header-tests
=> Enabling page header tests

e2e/tests/components/page-header/page-header.po.spec.ts
https://portal.digitalsafe.net/browse/EL-3620
Bringing over Ashley's fix to the tests since it is blocking progress.
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_page-header-test-fix
=> EL-3620 - Enabling page header tests

docs/app/pages/components/components-sections/input-controls/input-dropdown/input-dropdown.component.html
https://portal.digitalsafe.net/browse/EL-3621
Input fields are incorrectly styled in the Micro Focus site due to lacking the `type` attribute.
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3621-input-dropdown-customize
=> EL-3621 - Input dropdown documentation - added input type

docs/app/pages/css/css-sections/icons/ux-icons/icon-preview/icon-preview.component.html, src/styles/buttons.less
https://portal.digitalsafe.net/browse/EL-3552
- Adding hpe icons to iconset preview
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3552-hpe-icons
=> EL-3552 - adding hpe icons to iconset

src/common/icon/icon-type.ts
N/A
- `identifier` could might be null in some cases, in which case calling `trim` or `indexOf` would throw an error.
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_Fixing-Test-Issue
=> Fixing Test Failure

e2e/pages/index.html
N/A
- Preloading all fonts which should prevent any from missing in screenshots.
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_Fixing-Failing-Tests
=> Preloading fonts

karma.conf.js, src/components/select/select.component.html, src/components/select/select.component.spec.ts, src/components/select/select.component.ts, src/components/tag-input/tag-input.component.html, src/components/tag-input/tag-input.component.ts, src/components/tag-input/tag-input.spec.ts
https://portal.digitalsafe.net/browse/EL-3626
- inputChange and ValueChange no longer being called on initialization for select component
- Tests added for select component for inputChange, ValueChange and blurring the input
- InputChange and tagChange no longer being called on initialization in tags component
- Tests added for tag component for inputChange and tagsChange
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3626-select-subject
=> EL-3626 - select subject

src/components/select/select.component.spec.ts, src/components/select/select.component.ts
https://portal.digitalsafe.net/browse/EL-3626
- Updated to Subject rather than ReplaySubject
- Updated tests
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_select-change-updates-qa
=> Stop valueChange emitting on initialization

package.json
https://portal.digitalsafe.net/browse/EL-3629
- only including e2e/pages and e2e/tests for docs package
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3629-protractor-testing
=> Update package.json for e2e folder

docs/app/services/playground/utilities/system-helper.ts, src/directives/float-label/float-label.directive.ts, src/styles/ux-aspects.less
https://portal.digitalsafe.net/browse/EL-3637
- AutoFillMonitor added
- CSS for AutoFillMonitor Imported
- https://plnkr.co/edit/6k36pQ790o7r6MrmMP9t?p=preview - AutoFillMonitor plunker
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3637-float-label-autofill-issue
=> EL-3637 - Float Label AutoFill Issue

src/ng1/directives/fixedHeaderTable/fixed-header-table.controller.js
https://portal.digitalsafe.net/browse/EL-3635
Copied over the paging logic from uxInfiniteScroll. This will load the next page when the user scrolls within one table height of the end.
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3635-fixed-header-table-paging
=> EL-3635 - Buffer for paging in fixed header table

src/ng1/directives/spark/spark.spec.js
Build is currently broken.
Fixed a jshint error.
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_jshint-fix
=> Fixed jshint error

docs/app/data/hpe-icons.json, docs/app/data/ux-icons.json, src/components/icon/iconsets/common-icons.ts, src/icons/hpe/highlighting-remove.svg, src/icons/hpe/highlighting.svg, src/icons/ux/highlighting-remove.svg, src/icons/ux/highlighting.svg, src/styles/ux-icons.less
https://portal.digitalsafe.net/browse/EL-3653
- Added highlighting and highlighting remove icons
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3653-icon-request-highlighting
=> EL-3653 - highlight icons added

docs/app/pages/components/components-sections/select/select/select.component.html, docs/app/pages/components/components-sections/select/select/snippets/tag-template.html, src/components/select/select.component.html, src/components/select/select.component.ts
https://portal.digitalsafe.net/browse/EL-3471
- added tagTemplate input to select component
- forwarded tagTemplate to tag-input component
- updated documentation to include tagTemplate in select section
- Changes made per closed pull request - https://github.com/UXAspects/UXAspects/pull/1221
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_select-tag-updates
=> EL-3471 - Select tag updates

docs/app/pages/charts/charts-sections/sankey-chart/sankey-chart/sankey-chart.component.html
https://portal.digitalsafe.net/browse/EL-3650
Update to wording to make it clear that minHeight is ignored due to height of nodes vs height of chart
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3650-Sankey-doc-wording
=> Update to sankey doc wording

docs/app/pages/components/components-sections/search/search-builder-ng1/snippets/addFieldPanel.js, src/ng1/directives/searchBuilder/searchGroup.controller.js
Allow adding multiple component fields at once from the Add Field Panel.
Allow `vm.addNewField` to accept an array of components.
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/j-zhen_CI_UXAspects_search-group-components
=> Allow searchGroup to add multiple fields at once

docs/app/pages/components/components-sections/facets/facets-ng1/facets-ng1.components.html, package-lock.json, package.json, src/ng1/directives/facets/facet/facet.controller.js, src/ng1/directives/facets/facet/facet.directive.js, src/ng1/directives/facets/facet/facet.html
https://portal.digitalsafe.net/browse/EL-3657
* Added new property.
* Changed to `bindToController` to avoid polluting scope.
* Updated documentation.
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3657-facets-expanded-angularjs
=> EL-3657 - [AngularJS] Added expanded binding for facet

e2e/tests/components/select/standard/select.e2e-spec.ts
Jenkins build failing on 'should allow a custom icon' select screenshot test
- removed window.scroll which is no longer needed as there will be no scrolling since the customizable options are now alongside the select
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_scrolling-removal-select
=> Update for fixing select tests that are failing on screenshots

scripts/run-ci-local.js
https://portal.digitalsafe.net/browse/EL-3728
Use 1.3.0 release of buildenv
=> EL-3728: Update build env image

src/components/page-header/page-header.component.html, src/components/page-header/page-header.component.ts
https://portal.digitalsafe.net/browse/EL-3680
- Added in a logoTemplate for the product logo area
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3680-masthead-brand-update
=> EL-3680 - masthead brand update

.github/PULL_REQUEST_TEMPLATE.md
Downstream builds are now available, but sometimes are omitted from the PR, requiring manual lookup.
* Added a section to list downstream builds to aid the reviewer.
* Corrected spelling.
N/A
=> Downstream Builds info for pull requests

src/common/testing/dispatch-event.ts, src/components/select/select.component.spec.ts, src/components/select/select.component.ts
https://portal.digitalsafe.net/browse/EL-3724
- Removed one line of code causing issue
- Added in test
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3724-Select-Dropdown
* caf/ux-aspects-micro-focus: https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf%7Eux-aspects-micro-focus%7EEL-3724-Select-Dropdown%7ECI/
=> El 3724 select dropdown

src/components/date-range-picker/date-range-picker.spec.ts, src/components/date-time-picker/date-time-picker.spec.ts
Errors are being logged due to a couple of tests not having expectations.
Noticed some errors being logged in the Karma tests, this should resolve them.
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_fix-test-warnings
Not required since Karma tests are not run downstream.
=> Fixed some invalid tests

src/components/input-dropdown/input-dropdown.component.ts
Build was broken.
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_tslint
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~tslint~CI/)
=> Fix for tslint

src/components/checkbox/checkbox.component.html, src/components/checkbox/checkbox.component.spec.ts, src/components/checkbox/checkbox.component.ts, src/components/radiobutton/radio-button-group/radio-button-group.directive.ts, src/components/radiobutton/radiobutton.component.html, src/components/radiobutton/radiobutton.component.spec.ts, src/components/radiobutton/radiobutton.component.ts, src/components/toggleswitch/toggleswitch.component.html, src/components/toggleswitch/toggleswitch.component.spec.ts, src/components/toggleswitch/toggleswitch.component.ts
https://portal.digitalsafe.net/browse/EL-3780
- Making fixes to Checkbox, Radio Button and Toggle Switch
- Also making some performance improvements - `OnPush`, avoiding the use of getters in template etc..
- Updated tests
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3780-Double-Emit
https://jenkins.swinfra.net/job/SEPG/job/caf/view/Developer/job/caf~ux-aspects-micro-focus~EL-3780-Double-Emit/
https://jenkins.swinfra.net/job/SEPG/job/caf/view/Developer/job/caf~ux-aspects-micro-focus~EL-3780-Double-Emit~CI/
=> EL-3780 - Components double emit

src/components/select/select.component.ts
N/A
Use of `unknown` type not supported in Angular 6
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_fix-build
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~fix-build~CI/)
=> Fixing ng6 issue

docs/app/pages/components/components-sections/page-header/page-header/page-header.component.html, src/components/page-header/custom-menu/custom-menu.directive.ts
https://portal.digitalsafe.net/browse/EL-3736
Added `uxPageHeaderCustomItem` to make it clear that it's not only for adding menu content.
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3736-masthead-custom-content
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-3736-masthead-custom-content~CI/)
=> EL-3736 - Added alternative selector for PageHeaderCustomMenuDirective

e2e/tests/components/search-builder/search-builder.e2e-spec.ts
Builds are randomly failing on a search builder e2e screenshot.
Disable faulty screenshot until the issue can be resolved.
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_temp-remove-search-builder-screenshot
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~temp-remove-search-builder-screenshot~CI/)
=> Disable faulty screenshot until the issue can be resolved

e2e/pages/styles.css, e2e/tests/components/search-builder/search-builder.e2e-spec.ts, pom.xml
https://portal.digitalsafe.net/browse/EL-3917
Remove animations/transitions, similar to the MF e2e app.
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3917-e2e-failures
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-3917-e2e-failures~CI/)
=> EL-3917 - e2e failures

docs/app/data/ux-icons.json, src/components/icon/iconsets/common-icons.ts, src/icons/ux/export.svg, src/styles/ux-icons.less
https://portal.digitalsafe.net/browse/EL-3939
Add the export icon to ux-icons iconset.
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3939-export-icon
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-3939-export-icon~CI/)
=> EL-3939 - Add in export icon

docs/app/pages/components/components-sections/buttons/split-button-dropdowns/snippets/app.keppel.html, docs/app/pages/components/components-sections/buttons/split-button-dropdowns/snippets/app.microfocus.html, docs/app/pages/components/components-sections/buttons/split-button-dropdowns/split-button-dropdowns.component.html
https://portal.digitalsafe.net/browse/EL-3960
Based on UX feedback, the text and icons within the split button dropdown documentation have been updated to be more realistic.
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3960-update-text
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-3960-update-text~CI/)
=> Improve split button dropdown text documentation

docs/app/pages/components/components-sections/buttons/dropdowns/dropdowns.component.html
https://portal.digitalsafe.net/browse/EL-3911
Added missing class to the second flat icon
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3911-Dropdown-button-fix
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-3911-Dropdown-button-fix~CI/)
=> EL-3911 - Dropdown-button-fix

src/components/hierarchy-bar/hierarchy-bar-collapsed/hierarchy-bar-collapsed.component.html, src/components/hierarchy-bar/hierarchy-bar-collapsed/hierarchy-bar-collapsed.component.ts, src/components/hierarchy-bar/hierarchy-bar.component.spec.ts
https://portal.digitalsafe.net/browse/EL-3903
* Replace getters with properties populated from the observable.
* Add karma tests.
* Remove `tick` operator since it appears to be unnecessary now.
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3903-hierarchy-bar-change-detection
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-3903-hierarchy-bar-change-detection~CI/)
=> EL-3903 - Fix change detection in ux-hierarchy-bar-collapsed

docs/app/pages/components/components-sections/buttons/dropdowns/dropdowns.component.html, docs/app/pages/components/components-sections/buttons/dropdowns/dropdowns.component.ts, docs/app/pages/components/components-sections/buttons/dropdowns/snippets/app.html, docs/app/pages/components/components-sections/buttons/dropdowns/snippets/app.ts, src/components/menu/menu-item/menu-item.component.ts, src/components/menu/menu.spec.ts
https://portal.digitalsafe.net/browse/EL-3972
* Add `activate` output which emit on click or enter keypress, removing the need to specify both click and keydown.enter bindings.
* Documentation of the new output.
* Karma tests for the new output.
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3972-Dropdown-menu-keyboard
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-3972-Dropdown-menu-keyboard~CI/)
=> EL-3972-Dropdown-menu-keyboard

docs/app/pages/components/components-sections/input-controls/number-picker/number-picker.component.html
https://portal.digitalsafe.net/browse/EL-3989
updated documentation for number picker placeholder property
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3989-Number-Picker-Placeholder-V1
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-3989-Number-Picker-Placeholder-V1~CI/)
=> EL-3989 - Number-Picker-PlaceholderV1

configs/webpack.docs.dev.config.js, configs/webpack.docs.prod.config.js, package-lock.json, package.json
https://portal.digitalsafe.net/browse/EL-3986
As we previously discussed, the Angular Package Format now drops the es5 bundles as downleveling is now done as part of the application build rather the libraries.
The same is true of the Angular packages themselves, they no longer include es5 bundles. We did not have a downleveling pass as part of our webpack builds, so it broke in IE as it retained native JavaScript classes in the code.
After diving into the CLI code, they appear to use babel to do a downleveling pass, so I have implemented the same functionality in our builds. Currently I have limited it to only downlevel Angular packages as it does increase built time and quite significantly if we were to apply it to all node modules. This works fine for now, we may have to downlevel …
=> EL-3986 - Angular 10 - Internet Explorer fix

docs/app/pages/components/components-sections/tables/column-picker/column-picker.component.html, docs/app/pages/components/components-sections/tables/column-picker/snippets/sort.ts, e2e/tests/components/column-picker/column-picker.e2e-spec.ts, src/components/table/column-picker/column-picker.component.html, src/components/table/column-picker/column-picker.component.spec.ts, src/components/table/column-picker/column-picker.component.ts, src/components/table/column-picker/column-picker.service.ts, src/components/table/column-picker/interfaces/column-picker-group-item.interface.ts, src/components/table/column-picker/interfaces/column-picker-tree-node.interface.ts, src/components/table/index.ts
https://portal.digitalsafe.net/browse/EL-4014
- Fixed issue where deselected array is not modified when columns are moved
- Remove default sorting
- Allow sorting via `sort` input
- Documented `sort` input
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4014-deselected-updating-sorting
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-4014-deselected-updating-sorting~CI/)
=> EL-4014 Column Picker: deselected not updating; unexpected sorting

src/components/dashboard/dashboard.service.ts
Reverts UXAspects/UXAspects#1398
This PR was targeting Master when it should have been targeting develop
=> Revert "Removing widget size constraint"

src/components/dashboard/dashboard.service.ts
This was previously reviewed and merged, however the target branch had been mistakenly set to master. Master has been reverted and this is just making those changes on develop
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_dashboard-pr
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~dashboard-pr~CI/)
=> Retargetting Dashboard PR

docs/app/pages/components/components-sections/tables/filters/filters.component.html, src/components/filters/filter-container.component.ts, src/components/filters/filter-dropdown/filter-dropdown.component.html, src/components/filters/filter-dropdown/filter-dropdown.component.spec.ts, src/components/filters/filter-dropdown/filter-dropdown.component.ts, src/components/filters/filter-dynamic/filter-dynamic.component.html, src/components/filters/filter-dynamic/filter-dynamic.component.spec.ts, src/components/filters/filter-dynamic/filter-dynamic.component.ts, src/components/filters/interfaces/filter.interface.ts
https://portal.digitalsafe.net/browse/EL-3957
- Adding id Input to filter dropdown and filter dynamic component.
- Adding `id` property to the `Filter` interface
-  Updating documentation
- Adding karma tests to assert IDs
- Updated components to use `OnPush` change detection
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3957-Filter-Ids
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-3957-Filter-Ids~CI/)
=> EL-3957 - Filter IDs

docs/app/pages/components/components-sections/dashboard/dashboard/dashboard.component.html, src/components/dashboard/dashboard.component.ts, src/components/dashboard/dashboard.service.ts, src/components/dashboard/dashboard.spec.ts
https://portal.digitalsafe.net/browse/EL-3905
- Adding new `refreshLayout` method
- Updating documentation
- Adding new test cases
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3905-Dashboard-Relayout
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-3905-Dashboard-Relayout~CI/)
=> EL-3905 - Dashboard Layout Method

src/directives/selection/selection-item.directive.ts, src/directives/selection/selection.directive.spec.ts, src/directives/selection/selection.directive.ts, src/directives/selection/selection.service.ts
https://portal.digitalsafe.net/browse/EL-4083
The uxSelection directive and the uxSelectionItemDirective were both emitting far too often. The following changes have been made:
- Prevented the directives from emitting on init
- Prevented the directives from emitting when an input changes
- Prevented directives from emitting when an event has occurred but the value doesn't change
- Prevent directives from emitting until the output value has stabilized, for example, in row mode when a selection is made we first deselect all items, then select the newly selected item. The newly selected item should not emit the event when we initially deselect it.
- Added logic to ensure clicking on something like a checkbox emits as expected, e.g. when clicking a checkbox the selected input value may …
=> EL-4083 - Selection Issue

src/components/dashboard/dashboard.service.ts, src/components/menu/menu-item/menu-item.component.ts, src/components/menu/menu.spec.ts, tslint.json
https://portal.digitalsafe.net/browse/EL-3934
Made use of the host binding 'attr.disabled' to ensure that click events are not triggered when the menu-item is disabled
Added in a karma test to assert that no click event is emitted when disabled is true.
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3934-menu-disabled-property
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-3934-menu-disabled-property~CI/)
=> EL-3934 - menu-disabled-property

src/directives/fixed-header-table/fixed-header-table.directive.ts
https://portal.digitalsafe.net/browse/EL-4028
Added new class to achieve fixed header box-shadow.
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4028-Fixed-Header
https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-4028-Fixed-Header~CI/
=> EL-4028-FixedHeader

src/directives/selection/selection-item.directive.ts, src/directives/selection/selection.directive.spec.ts
This reverts commit c73905291488c2bf966d8049788a645b271f0dcd.
=> Revert "EL-4085 - Row Selection (#1413)"

src/components/marquee-wizard/marquee-wizard-test-wrapper.ts, src/components/marquee-wizard/marquee-wizard.component.spec.ts, src/components/wizard/wizard-step.component.ts, src/components/wizard/wizard-test-wrapper.ts, src/components/wizard/wizard.component.spec.ts, src/components/wizard/wizard.component.ts
https://portal.digitalsafe.net/browse/EL-4109
* `visitedChange` is emitted when visited changes via user action.
* Expanded karma test coverage of wizard and marquee wizard.
* Refactored some common test functionality.
I have raised EL-4120 to investigate the use of test harnesses as a possible means to eliminate test duplication between these two related components.
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4109-wizard-visitedChange
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-4109-wizard-visitedChange~CI/)
=> EL-4109 - Wizard visitedChange

docs/app/services/playground/strategies/themes/microfocus-2020-strategy.ts
https://portal.digitalsafe.net/browse/EL-4106
Import font-weight 900.
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4106-Typography-2020-update
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-4106-Typography-2020-update~CI/)
=> EL-4106 - Typography - 2020 Update font-weight

docs/app/pages/components/components-sections/tables/hover-actions/hover-actions.component.html, docs/app/pages/components/components-sections/tables/hover-actions/snippets/app.html
https://portal.digitalsafe.net/browse/EL-4059
Removed theme="chart2" in hover action doc so that the default theme will get applied.
=> List hover action

docs/app/pages/components/components-sections/wizard/marquee-wizard/marquee-wizard.component.html, docs/app/pages/components/components-sections/wizard/wizard/wizard.component.html, src/components/marquee-wizard/marquee-wizard.component.html, src/components/marquee-wizard/marquee-wizard.component.spec.ts, src/components/marquee-wizard/marquee-wizard.component.ts, src/components/wizard/wizard.component.html, src/components/wizard/wizard.component.ts
https://portal.digitalsafe.net/browse/EL-4100
Updated the documentation to add the new sequential input in both sites
Added karma tests for the new input 
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4100-Marquee-Wizard-steps
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-4100-Marquee-Wizard-steps~CI/)
=> EL-4100 - Marquee-Wizard-steps

e2e/tests/components/tags/tags.e2e-spec.ts, e2e/tests/components/tags/tags.po.spec.ts, src/components/tag-input/tag-input.component.ts
https://portal.digitalsafe.net/browse/EL-4042
- Fix dropdown not closing when using OnPush
- Added test that covers this scenario
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4042-tag-dropdown
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-4042-tag-dropdown~CI/)
=> EL-4042 - Tag Input: dropdown not closing when using OnPush

src/components/input-dropdown/input-dropdown.component.spec.ts, src/components/input-dropdown/input-dropdown.component.ts
https://portal.digitalsafe.net/browse/EL-4051
Fixed the `resetValue` function and made sure the `selectedChange` event emitter is emitting when a value is changed.
Added karma tests to ensure that the value is clear and the event emitter fires once with the correct value
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4051-Input-dropdown-wont-clear
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-4051-Input-dropdown-wont-clear~CI/)
=> EL-4051 - Input-dropdown-wont-clear

e2e/pages/app/page-header/page-header.module.ts, e2e/pages/app/page-header/page-header.testpage.component.html, e2e/pages/app/page-header/page-header.testpage.component.ts, e2e/pages/app/page-header/page.component.ts, e2e/tests/components/page-header/page-header.e2e-spec.ts, e2e/tests/components/page-header/page-header.po.spec.ts, src/components/breadcrumbs/breadcrumbs.component.html, src/components/page-header/page-header.component.spec.ts
https://portal.digitalsafe.net/browse/EL-4086
- Only add `href` when `routerLink` has been specified
- Add karma test for checking presence of `href`
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4086-masthead-breadcrumbs
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-4086-masthead-breadcrumbs~CI/)
=> EL-4086 - Masthead Breadcrumbs: remove unwanted href

docs/app/pages/components/components-sections/dashboard/dashboard/dashboard.component.html, src/components/dashboard/dashboard.spec.ts, src/components/dashboard/widget/dashboard-widget.component.ts
https://portal.digitalsafe.net/browse/EL-4160
- Correctly set the row/column values on init
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4160-dashboard-colrow-inputs
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-4160-dashboard-colrow-inputs~CI/)
=> EL-4160 - Fix dashboard widget col and row inputs not working correctly on init

docs/app/pages/components/components-sections/tree-view/tree-grid/snippets/app.ts, docs/app/pages/components/components-sections/tree-view/tree-grid/tree-grid.component.ts
https://portal.digitalsafe.net/browse/EL-3990
Updated the documentation example so that it deselect parent items when all child items have been deselected.
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3990-tree-grid-selection-behaviour-update
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-3990-tree-grid-selection-behaviour-update~CI/)
=> EL-3990-tree grid selection behaviour update

package-lock.json, package.json, src/package.json
Updated versions
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_ux-aspects-3.0.0
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~ux-aspects-3.0.0~CI/)
=> Version change

docs/app/pages/components/components-sections/tables/custom-filters-component/sample/sample-filter.component.html, e2e/pages/app/item-display-panel/item-display-panel.testpage.component.html, e2e/pages/app/item-display-panel/item-display-panel.testpage.component.ts, e2e/tsconfig.app.json, e2e/tsconfig.e2e.json, src/tsconfig-build.json, tsconfig.json
https://portal.digitalsafe.net/browse/EL-3870
Enabled full template type check in config files
Removed any code that was unused which was highlighted by the enabling of the template check
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3870-full-template-type-check
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-3870-full-template-type-check~CI/)
=> EL-3870 - Enable full template type check

BREAKING_CHANGES.md, docs/app/pages/components/components-sections/file-upload/file-upload/file-upload.component.html, docs/app/pages/components/components-sections/input-controls/input-mask/input-mask.component.html, src/package.json
https://portal.digitalsafe.net/browse/EL-3314
Added installation instructions for the packages which need to be installed manually.
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3314-list-3rd-party-components
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-3314-list-3rd-party-components~CI/)
=> 3314-install third party packages manually

docs/app/pages/components/components-sections/input-controls/number-picker/number-picker.component.html, src/components/number-picker/number-picker.component.spec.ts, src/components/number-picker/number-picker.component.ts
https://portal.digitalsafe.net/browse/EL-4003
- Allow function to be specified as the `step` input of the number picker
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4003-step-function
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-4003-step-function~CI/)
=> EL-4003 - Number Picker - Step Function

e2e/tests/components/select/standard/select.e2e-spec.ts
https://portal.digitalsafe.net/browse/EL-4193
Temporarily disable the failing check until the problem can be resolved.
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4193-disable-failing-test
N/A
=> EL-4193 - Disable randomly failing screenshot check: select-recent-multi

e2e/tests/components/dashboard/dashboard.e2e-spec.ts, src/components/dashboard/dashboard.service.ts
https://portal.digitalsafe.net/browse/EL-4187
- Fix issue where resizing would not occur when it should
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4187-resize-fix
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-4187-resize-fix~CI/)
=> EL-4187 - Dashboard Widget - fix for keyboard resizing

src/directives/reorderable/reorderable.directive.ts
https://portal.digitalsafe.net/browse/EL-3701
Fix the CDK drag in v9
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3701-cdk-drag-version-fix
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-3701-cdk-drag-version-fix~CI/)
=> EL-3701-cdk-drag-version-fix

src/components/toggleswitch/toggleswitch.component.html
https://portal.digitalsafe.net/browse/EL-4189
Removed role to allow required attribute on toggle switch when using screen reader
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_Support-the-required-attribute-toggle-switch
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~Support-the-required-attribute-toggle-switch~CI/)
=> EL-4189-Support-the-required-attribute-toggle-switch

e2e/pages/app/dashboard/dashboard.testpage.component.html, e2e/tests/components/dashboard/dashboard.e2e-spec.ts, src/components/dashboard/widget/dashboard-widget.component.ts
https://portal.digitalsafe.net/browse/EL-4210
When we use dashboard widget we may pass undefined col and row values which will break the functionality. Since we use coerceNumber  property, the falsy values  are considered as 0.
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4210-dashboard-undefined-col-row-inputs
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-4210-dashboard-undefined-col-row-inputs~CI/)
=> EL-4210 - Dashboard-undefined col and row values should not be treated as 0

docs/app/pages/components/components-sections/input-controls/tags/tags.component.html, src/components/tag-input/tag-input.component.html, src/components/tag-input/tag-input.component.ts, src/components/tag-input/tag-input.spec.ts
https://portal.digitalsafe.net/browse/EL-4011
Updated the documentation to include new input 
Added a karma test 
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4011-Tag-input-add-tags-on-blur
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-4011-Tag-input-add-tags-on-blur~CI/)
=> EL-4011-Tag input add tags on blur

docs/app/pages/changelog/changelog.component.ts, docs/app/pages/changelog/logs/release-v3.8.1.md
- add release notes, remove 3.8.0 release notes.
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_release-3.8.1
N/A
=> Release 3.8.1

src/pipes/date-formatter/date-formatter.pipe.ts
https://portal.digitalsafe.net/browse/EL-4241
Injected LOCALE_ID into the date-formatter-pipe.ts and based this as the third parameter in formatDate
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4241-date-range-picker-locale-data/#/landing
[ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/view/Developer/job/caf~ux-aspects-micro-focus~EL-4241-date-range-picker-locale-data~CI/)
=> EL-4241: Date Range Picker: "Missing locale data" error

src/services/color/color-sets/micro-focus-color-set.ts
https://portal.digitalsafe.net/browse/EL-4246
1. adding colour to color set
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4246-tag-support-non-palette-colors
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-4246-tag-support-non-palette-colors~CI/)
=> EL-4246: Tag: support non-palette colors

package-lock.json, package.json, src/package.json
=> Rollover version to 4.1.1

src/styles/typography.less
https://portal.digitalsafe.net/browse/EL-4259
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4259-strong-font-family
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-4259-strong-font-family~CI/)
=> EL-4259 - "Source Sans Pro" font is applied to the <strong> element

src/components/marquee-wizard/marquee-wizard.component.html, src/components/marquee-wizard/marquee-wizard.component.spec.ts
https://portal.digitalsafe.net/browse/EL-4256
1. Added classes
2. Updated unit tests to cover tests
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4256-marquee-wizard-buttons-class
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-4256-marquee-wizard-buttons-class~CI/)
=> EL-4256 - Marquee Wizard: cannot identify buttons for test automation

src/components/color-picker/color-picker.component.less
https://portal.digitalsafe.net/browse/EL-4248
- Added flex to position the checkmark center
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4248-color-picker-misaligned-checkmark
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-4248-color-picker-misaligned-checkmark~CI/)
=> EL-4248 - Color picker - misalignment of checkmark

src/components/popover/popover.component.html
https://portal.digitalsafe.net/browse/EL-4296
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4296-parition-map-showcase
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-4296-parition-map-showcase~CI/)
=> EL-4296 - Partition Map showcase example hangs the browser tab

docs/app/pages/components/components-sections/panels/side-panel/side-panel.component.html
https://portal.digitalsafe.net/browse/EL-4272
https://internal.almoctane.com/ui/entity-navigation?p=131002/7002&entityType=work_item&id=374517
- Updated documentation
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4272-side-panel-documentation
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-4272-side-panel-documentation~CI/)
=> EL-4272 - Side Panel documentation - animate default value is noted as true but should be false

src/plugins/chartjs/timeline/timeline-chart.module.ts
https://portal.digitalsafe.net/browse/EL-4279
https://internal.almoctane.com/ui/entity-navigation?p=131002/7002&entityType=work_item&id=372606
- Added handleMouseMove call to mouseOut listener
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4279-timeline-chart-tooltip
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-4279-timeline-chart-tooltip~CI/)
=> EL-4279 - Timeline Chart: Tooltip doesn't disappear

e2e/tests/components/menu/menu.e2e-spec.ts, e2e/tests/components/menu/menu.po.spec.ts, src/components/menu/menu-trigger/menu-trigger.directive.ts
https://internal.almoctane.com/ui/entity-navigation?p=131002/7002&entityType=work_item&id=382092
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_382092-dropdown-menu-space-focus
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~382092-dropdown-menu-space-focus~CI/)
=> 382092 - Dropdown Menu: Space and focus issues

src/package.json
https://internal.almoctane.com/ui/entity-navigation?p=131002/7002&entityType=work_item&id=398386
Updating src/package.json with exports
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_398386-adding-exports
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~398386-adding-exports~CI/)
=> 398386 - Adding exports to src

package-lock.json, package.json, protractor.conf.js
Attempting to work around the chromedriver crashes which occasionally kill our builds.
Use [protractor-retry](https://www.npmjs.com/package/protractor-retry) to attempt to recover from a random crash.
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_protractor-retry
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~protractor-retry~CI/)
=> protractor retry

package-lock.json, package.json
Build error due to updated version of npm.
Change arguments to npm pack in the build script.
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_fix-npm-pack
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~fix-npm-pack~CI/)
=> fix npm pack on release

src/components/select/select.component.ts
https://internal.almoctane.com/ui/entity-navigation?p=131002/7002&entityType=work_item&id=375017
1. Added detect changes after value observable to detect changes sooner.
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_375017-select-delay
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~375017-select-delay~CI/)
=> 375017 - Select: delay after clicking an option

docs/app/pages/components/components-sections/tree-view/tree-grid/tree-grid.component.html, src/components/radiobutton/radiobutton.component.ts
https://internal.almoctane.com/ui/entity-navigation?p=131002/7002&entityType=work_item&id=478249
- remove deprecated content
- un-deprecate radio button tabindex since it's still being used in the template
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_478249-remove-deprecated
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~478249-remove-deprecated~CI/)
=> 478249 - remove deprecated content

src/components/date-time-picker/day-view/day-view.component.html
https://internal.almoctane.com/ui/entity-navigation?p=131002/7002&entityType=work_item&id=1
adding gridcell back
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_adding-gridcell
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~adding-gridcell~CI/)
=> adding gridcell back

docs/app/pages/components/components-sections/search/search-builder/search-builder.component.html, src/components/search-builder/search-builder-group/search-builder-group.component.html, src/components/search-builder/search-builder-group/search-builder-group.component.ts, src/components/search-builder/search-components/date-range/date-range.component.html, src/components/search-builder/search-components/date-range/date-range.component.ts, src/components/search-builder/search-components/date/date.component.html, src/components/search-builder/search-components/date/date.component.ts
https://internal.almoctane.com/ui/entity-navigation?p=131002/7002&entityType=work_item&id=532094
add input to search group component
updated date and date range configs to allow for aria label
updated documentation 
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_532094-search-builder-a11y
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~532094-search-builder-a11y~CI/)
=> 532094 - search builder aria labels

LICENSE.md, docs/app/components/page-footer/page-footer.component.html, docs/app/data/footer-navigation.json, docs/app/data/team-page.json, docs/app/pages/licenses/licenses.component.html, docs/app/pages/licenses/licenses.component.ts, grunt/usebanner.js, pom.xml
https://github.houston.softwaregrp.net/caf/ux-aspects-micro-focus/issues/938
- Update copyright text in License. footer
- Update footer to accommodate longer copyright text
- Update team to use OpenText emails
- Update grunt usebanner task
- Update pom
=> Update copyright and remove references to Micro Focus

src/plugins/chartjs/timeline/timeline-chart.module.ts
N/A
Lazy loading chart.js to prevent eager loading
=> fix: timeline chart tree-shakability

docs/app/pages/components/components-sections/tree-view/tree-view/tree-view.component.html
https://github.houston.softwaregrp.net/caf/ux-aspects-micro-focus/issues/980
- update alert to recommend other libraries 
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_tree-view-warning
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~tree-view-warning~CI/)
=> 980 - tree view update alert

docs/app/pages/components/components-sections/tables/column-picker/column-picker.component.html, src/components/table/column-picker/column-picker.component.html, src/components/table/column-picker/column-picker.component.ts
https://github.houston.softwaregrp.net/caf/ux-aspects-micro-focus/issues/978
Adding inputs for buttons to add aria labels
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_column-picker-aria-labels
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~column-picker-aria-labels~CI/)
=> 978 - Adding aria labels

docs/app/pages/getting-started/getting-started.component.html, package-lock.json
**https://github.houston.softwaregrp.net/caf/ux-aspects-micro-focus/issues/973**
- Removing references to the seed project
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_remove-seed-references
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~remove-seed-references~CI/)
=> Removing references to seed project

src/components/tabset/tab/tab.component.html, src/components/tabset/tab/tab.component.ts
https://github.houston.softwaregrp.net/caf/ux-aspects-micro-focus/issues/927
Fix undefined id issue
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_tab-accessibililty
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~tab-accessibililty~CI/)
=> 927 - Tab accessibility issue

src/components/page-header/navigation/navigation.component.ts, src/components/page-header/page-header.component.spec.ts
https://internal.almoctane.com/ui/entity-navigation?p=131002/7002&entityType=work_item&id=979
Removed role="menubar" from the page header navigation when there are no child menuitems
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_979-page-header-accessibility
* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~979-page-header-accessibility~CI/)
=> 979 - Page Header accessibility

src/components/partition-map/partition-map.component.ts, src/components/tooltip/tooltip.directive.ts
N/A - reported by Andrew Jolly, but no ticket raised
When displaying large numbers of items in the partition map, performance can become incredibly slow. There were two key issues I discovered:
1. We recompute the x position and width of segments many times as this runs on change detection and it is calculated multiple times within each change detection cycle. These calculations are reasonably expensive, so I have added a caching mechanism to only calculate the values once, until they may have changed giving a large speed boost.
2. The tooltip (which is often used in conjunction with the partition map) when `hide` is called it will run change detection. This happens regardless of whether the tooltip is actually open or not. Adding a check to only run the hide logic if the tooltip is …
=> fix: partition map performance issues

pom.xml, release-notes-11.0.1.md, src/components/date-range-picker/date-range-picker.component.ts, src/components/date-time-picker/date-time-picker.component.ts, src/components/date-time-picker/date-time-picker.spec.ts, src/components/time-picker/time-picker.component.html, src/components/time-picker/time-picker.component.ts
=> fix: adding support for undefined dates
